### ISSUE TITLE
Sometimes prompted for password rather than PIN

### ISSUE THREAD

**Issue by bdube** [drduh/YubiKey-Guide#102]
Thank you for this guide!

I use the setup described in this guide at work and at home. At work, I'm prompted for the smartcard PIN and everything works fine. At home, more often than not I am prompted for the passphrase rather than the PIN. I followed the guide to generate a long, random passphrase so this means I am prompted for something I don't have in my limited memory.

Does anyone know why I would be prompted for the passphrase rather than the PIN?

I do use the recommended .bashrc lines to set `GPG_TTY` and call `gpg-connect-agent updatestartuptty /bye`. Both systems are Debian testing.

Thanks.

**Comment by drduh** [comment]
Did you generate the master keys on your home machine? If so, did you remove them after moving subkeys over? Run `gpg --list-keys` and see if you get `sec#` for the Master and `ssb>` for subkeys when YubiKey is plugged in.

**Comment by bdube** [comment]
Thanks for your response.

I did generate the keys on the home machine. From `gpg --list-keys` I have only `pub`, `uid`, and `sub` in the first column. From `gpg --card-status` I have `sec` and `ssb` rather than `sec#` and `ssb>`. So there's something I need to remove on my home machine?

**Comment by bdube** [comment]
I must not have followed the guide as closely the second time I did this at home. I'm going back through the steps now.

**Comment by drduh** [comment]
I recommend using a live, non-persistent image for creating the keys. Take a look at this thread, too: https://lists.gnupg.org/pipermail/gnupg-users/2010-November/039892.html

**Comment by bdube** [comment]
Thank you. I must have been impatient the second time through and skipped steps. Going back through the guide has fixed whatever I mangled last time. Sorry for the noise and thanks again for this guide and your responses.
