### ISSUE TITLE
Primary key paper backup guide

### ISSUE THREAD

**Issue by matheusmoreira** [drduh/YubiKey-Guide#104]
Hello! Thank you for writing this detailed guide. I see that `paperkey` is mentioned in the backup section:

> Also consider using a [paper copy] of the keys as an additional backup measure.

It would be wonderful if the guide had a detailed section about this. It is easy to export and print secret keys for offline storage but it is not so obvious how to get them back online. Given the importance of the primary key, I think it is important to know how to correctly restore and test the backup in order to prevent accidental loss of the key.

[paper copy]: https://www.jabberwocky.com/software/paperkey/

**Comment by drduh** [comment]
Added more verbose and thorough back-up instructions in a recent commit. With storage being so cheap (and small), I personally prefer digital copies over paper ones. Others are welcome to color in more detail if a paper key is something they use.
