### ISSUE TITLE
How to sign third party keys?

### ISSUE THREAD

**Issue by Levino** [drduh/YubiKey-Guide#106]
I cannot "trust" third party pgp keys because trusting them needs signature which is only possible with the offline master key. I do not want to bring the master key hot for every signature that I plan to make. Is there a workaround?

**Comment by drduh** [comment]
You shouldn't need YubiKey to mark someone's GPG key as trusted. Signing oughtn't require the master key either. Are you using `gpg --edit-key $KEYID` and the `trust` command?

**Comment by Levino** [comment]
Maybe the problem is that my master key is also for signing? It says [SC] after it, what is potentially wrong I guess. Can I "remove" the S somehow with restoring the master key, etc?
```
/home/levin/.gnupg/pubring.kbx
------------------------------
sec#  rsa4096/0xA1708E375E4295F8 2018-05-24 [SC]
      Key fingerprint = 6774 B058 0DA2 4DB8 6557  A285 A170 8E37 5E42 95F8
uid                   [ultimate] Levin Keller (private address) <post@levinkeller.de>
uid                   [ultimate] Levin Keller (business address) <levin@hardfork.io>
ssb>  rsa4096/0x935A36742EC8C6AE 2018-05-24 [S] [expires: 2020-05-23]
ssb>  rsa4096/0xD5F295030F68218B 2018-05-24 [E] [expires: 2020-05-23]
ssb>  rsa4096/0xA6123E551DA47812 2018-05-24 [A] [expires: 2020-05-23]

```

**Comment by Levino** [comment]
But even when I try to sign with the hot signing key I get this:
```
gpg -u 0x935A36742EC8C6AE --sign-key 0x863A77D4F797B8AC 

pub  rsa4096/0x863A77D4F797B8AC
     created: 2019-04-19  expires: never       usage: C   
     trust: full          validity: unknown
sub  rsa4096/0x70376FAF3783278D
     created: 2019-04-19  expires: 2020-04-18  usage: S   
sub  rsa4096/0x39C8554B5E2DEC93
     created: 2019-04-19  expires: 2020-04-18  usage: E   
sub  rsa4096/0xFDCDF1C75E37C6C5
     created: 2019-04-19  expires: 2020-04-18  usage: A   
[ unknown] (1). Kilian Wimmer <kilocheat@gmail.com>


pub  rsa4096/0x863A77D4F797B8AC
     created: 2019-04-19  expires: never       usage: C   
     trust: full          validity: unknown
 Primary key fingerprint: 00C9 E62E 4407 DF56 BB4C  C595 863A 77D4 F797 B8AC

     Kilian Wimmer <kilocheat@gmail.com>

Are you sure that you want to sign this key with your
key "Levin Keller (private address) <post@levinkeller.de>" (0xA1708E375E4295F8)

Really sign? (y/N) y
gpg: signing failed: No secret key
gpg: signing failed: No secret key
```

**Comment by moonmeister** [comment]
Signing a key would require the master key. If you want to trust a third-party then you're doing the wrong thing. See @drduh 's comment. Signing means you're allowing that key to represent you...trust means you trust the authenticity of the key.

**Comment by Levino** [comment]
Hm? I just want to sign a key of a friend and say, that I trust it fully (not ultimately) and then upload the signature to a keyserver.

**Comment by moonmeister** [comment]
You just need the trust command as @drduh suggested...and there's nothing to upload, trust is a local thing. 

If you signed his key it would be the equivalent of one of your keys and he could cryptographically represent you. His key would be a sub-key of your master key just like you have on your yubikey.

**Comment by moonmeister** [comment]
https://www.gnupg.org/gph/en/manual/x334.html

**Comment by moonmeister** [comment]
The more I read that article the more I'm confused...they kept saying "sign" but the example uses the trust command...try trust...I think that's what you want.

**Comment by Levino** [comment]
No. I am talking about key signing as in key signing parties https://en.wikipedia.org/wiki/Key_signing_party

**Comment by Levino** [comment]
I think the issue is the "signing capability" of the master key. GPG somehow wants to take the master key instead of the subkey. Funnily enough I can perfectly sign messages...

**Comment by juanii** [comment]
I'm a complete newbie at this so I might be talking nonsense, but I'm pretty sure I read somewhere about this confusion and the purpose of each key. Certify and Sign keys both "sign", but the first can be used to sign (certify the authenticity, or the identity of) other peoples' keys and the latter for signing your own messages. So I think your reasoning is correct: you can sign messages without bringing your master key hot, but you can't sign other peoples' keys without doing it. At least with the master key/subkeys configuration proposed by drduh in his excellent guide.

Regards

**Comment by mjbnz** [comment]
> You just need the trust command as @drduh suggested...and there's nothing to upload, trust is a local thing.
> 
> If you signed his key it would be the equivalent of one of your keys and he could cryptographically represent you. His key would be a sub-key of your master key just like you have on your yubikey.

This is not correct - key signing is a public declaration of trust, where you are stating that you trust and [C]ertify the other key. This is how the web of trust works. It is **_not_** declaring that the key you're signing speaks for you.

And yes, you'd need to bring your master key online to do this, it's not something you should be doing with a subkey.

**Comment by Levino** [comment]
So I have to put all keys I want to sign as textfiles on a usb stick and then bring them to the offline system to sign (aka "certify") them and then move the certified keys back on my hot system and upload them to a keyserver. Quite a bummer but seems to be the only way. Thanks to everyone helping out. Closing.

**Comment by netflash** [comment]
That's exactly what I do (except the offline system, cuz I'm stupidly not that paranoid) - restore a master key from backup, sign someone else's key, send that key back to key servers and remove the master key from the workstation.
