### ISSUE TITLE
Windows ssh-add -L replacment 

### ISSUE THREAD

**Issue by mikart143** [drduh/YubiKey-Guide#108]
I am trying to get my ssh key with ssh-add -L but I am unable to do this. I am getting the agent has no identities. Then I changed my gpg agent to use putty and i exported my key with gpg --export-ssh-key but I get key with end opengpg which is different then cardno as in example. I change manually key to cardno:..... (of course i changed number to card number) and uploaded to github but I am getting error:

![image](https://user-images.githubusercontent.com/4084564/57762907-a7c63180-7700-11e9-9cad-bfea340fc69d.png)

**Comment by drduh** [comment]
Sorry, I have not used Yubikey with Windows and don't plan on it. Maybe someone else can help us out.

**Comment by mjbnz** [comment]
```gpg --export-ssh-key <user-id>```
