### ISSUE TITLE
Q: Storing backup disk image in the cloud

### ISSUE THREAD

**Issue by mikem** [drduh/YubiKey-Guide#111]
First of all, thank you for this document, it's awesome.

In the guide, you write:

> **Important** The master key should be kept offline at all times and only accessed to revoke or issue new sub-keys.

I intend to back the secret keys up to a USB drive on a LUKS-encrypted partition as you describe. I then plan on taking an image of that drive (with `dd`, for example) and backing it up to the cloud (AES encrypted, FWIW).

I take your statement to mean that the master key should only ever be decrypted in a live CD environment without an Internet connection. But storing an image of the backup drive in the cloud as I plan to do should be fine.

Does that make sense? Am I missing something and incurring risk?

**Comment by drduh** [comment]
It sounds like a fine, convenient idea to me. One could store the LUKS header detached with another provider, or encrypted to a friend's key, for additional peace of mind.
