### ISSUE TITLE
Edit uid after moving private key to yubikey

### ISSUE THREAD

**Issue by shoshin71** [drduh/YubiKey-Guide#114]
Thank you for this guide. I followed it and got a basic setup working. I'm trying to add a uid to my key with --edit-key, but I keep seeing "Need the secret key to do this." Is there something simple that I am missing?

**Comment by drewwestrick** [comment]
Try doing a `gpg --card-status` followed by a gpg` -K` if you see a `sec#` before your primary key, it means that the private key isn't loaded in the keyring. Generally once you load your keys onto your device, the instructions have you remove the private key from your keyring (this is good practice). If this is the cause, you won't be able to add a UID to your public key without your private key. Access your (hopefully offline and/or encrypted) private key and do a `gpg --import $PRIVATEKEY`. Add your UID, then re-export your public key using `gpg --armor --export $KEYID`.

**Comment by shoshin71** [comment]
Thank you. That's the solution.
