### ISSUE TITLE
Ubuntu software instructions require enabling universe or multiverse repository

### ISSUE THREAD

**Issue by afk11** [drduh/YubiKey-Guide#116]
I tried the instructions from the readme on a plain Ubuntu live CD and there were several errors about missing packages. I got around this by adding 'universe multiverse' to each networked repo in /etc/apt/sources.list before doing apt update. After this the procedure worked.

It was an ubuntu 18.04.2 live cd.

**Comment by drduh** [comment]
I have only used Debian Live for this setup, but this is good to know. Feel free to make a PR adding a note for Ubuntu users.

**Comment by lucaszanella** [comment]
Isn't it a bad thing to add "community maintaned" software to the repo list? Who compiles these softwares?

**Comment by lattice0** [comment]
still thinking about the community maintained issue
