### ISSUE TITLE
no-symkey-cache : invalid option

### ISSUE THREAD

**Issue by xkra** [drduh/YubiKey-Guide#117]
Following the guide with
`gpg --gen-random -a 0 24`
I receive the feedback that there is an invalid option on line 38 of gpg.conf, which is `no-symkey-cache`.

If I exlude this line with #, I am able to generate a random passphrase. How is the process affected by this - should I continue with this or should I fix without disabling `no-symkey-cache`?

**Comment by drduh** [comment]
`no-symkey-cache` just disables caching of symmetric passwords used for encrypting files or text. It should have no effect on any steps in this guide as there are no symmetric encryption operations done. What version of gpg are you using?

**Comment by chaosbunker** [comment]
GnuPG >= 2.2.7 is required for `no-symkey-cache`

See [https://lists.gnupg.org/pipermail/gnupg-announce/2018q2/000424.html](https://lists.gnupg.org/pipermail/gnupg-announce/2018q2/000424.html)
