### ISSUE TITLE
yubikey-neo-manager is deprecated

### ISSUE THREAD

**Issue by snario** [drduh/YubiKey-Guide#124]
The guide makes mention of the YubiKey NEO Manager:

> Windows Use the YubiKey NEO Manager to enable CCID functionality.

Linking to this invalid URL: https://www.yubico.com/products/services-software/download/yubikey-neo-manager/

The correct URL is: https://developers.yubico.com/yubikey-neo-manager/

However at the top of that website it states:

> This project is deprecated and is no longer being maintained. Use YubiKey Manager (GUI, CLI) to configure a YubiKey device.

**Comment by vorburger** [comment]
#129 will fix this.
