### ISSUE TITLE
Debian Key Retrieval Issues

### ISSUE THREAD

**Issue by johnsoga** [drduh/YubiKey-Guide#131]
In this section https://github.com/drduh/YubiKey-Guide#download-os-image the following command, at least for me, doesn't work:
```
gpg --recv DF9B9C49EAA9298432589D76DA87E80D6294BE9B
```

Per Debian's own instructions on performing this [here](https://www.debian.org/CD/verify) and [here](https://keyring.debian.org/) this should be:

```
gpg --keyserver keyring.debian.org --recv-keys DF9B9C49EAA9298432589D76DA87E80D6294BE9B
```

<img width="755" alt="Screen Shot 2019-09-25 at 12 23 46 AM" src="https://user-images.githubusercontent.com/1448547/65569246-debc1780-df2a-11e9-9906-10e39a64b4ee.png">
<img width="1074" alt="Screen Shot 2019-09-25 at 12 24 12 AM" src="https://user-images.githubusercontent.com/1448547/65569247-debc1780-df2a-11e9-8f30-cac2b29a8862.png">

**Comment by drduh** [comment]
That looks right - mind submitting a PR to update? Thanks!
