### ISSUE TITLE
VM for Key Generation

### ISSUE THREAD

**Issue by johnsoga** [drduh/YubiKey-Guide#132]
I'm not sure I see the point of this:

> Shut down the computer and disconnect internal hard drives and all unnecessary peripheral devices.

With the machine booted from a USB any attached storage wouldn't be able to run any type of software. Since the main point of security is accepting levels of risk I would think that creating a vm would suffice just as well as booting a live image on a physical machine. Assuming the user trusts their machine has not been compromised. So i would think it appropriate to be able add a note stating that opposed to booting from the USB a VM would suffice as well

**Comment by drduh** [comment]
> With the machine booted from a USB any attached storage wouldn't be able to run any type of software.

I believe the storage device firmware could still execute code, granted that's an extremely paranoid threat model.

> Since the main point of security is accepting levels of risk I would think that creating a vm would suffice just as well as booting a live image on a physical machine.

Agreed, that is probably an acceptable trade off for most users.

> Assuming the user trusts their machine has not been compromised. So i would think it appropriate to be able add a note stating that opposed to booting from the USB a VM would suffice as well

VM is certainly a viable option - please go ahead and drop that note in a PR, if you don't mind.
