### ISSUE TITLE
gpg-agent ignores cache-ttl options

### ISSUE THREAD

**Issue by sunknudsen** [drduh/YubiKey-Guide#135]
Thanks for the amazing guide!

Installed `gpg` using `brew install gnupg`.

Added the following to `~/.gnupg/gpg-agent.conf` to enable SSH support.

```shell
enable-ssh-support
default-cache-ttl-ssh 60
max-cache-ttl-ssh 120
default-cache-ttl 60
max-cache-ttl 120
pinentry-program /usr/local/bin/pinentry
```

Added the following to `~/.zshrc` as suggested [here][1].

```
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye > /dev/null
```

Everything works fine except `cache-ttl` options are ignored resulting in passphrases being cached for over 120 seconds.

What am I doing wrong?

  [1]: https://github.com/drduh/YubiKey-Guide#create-configuration

**Comment by sunknudsen** [comment]
I think I found the issue.

I believe the pin is cached by the YubiKey vs gpg-agent (see [this](https://dev.gnupg.org/T3362)).

If this assumption is correct, it means `cache-ttl` entries don’t apply when using a YubiKey to store GPG keys.

Perhaps this should be reflected in the [Create configuration](https://github.com/drduh/YubiKey-Guide#create-configuration) section or the guide?

```
default-cache-ttl-ssh 60
max-cache-ttl-ssh 120
default-cache-ttl 60
max-cache-ttl 120
```

**Comment by shibumi** [comment]
Hey,

I am running into this problem over and over again since at least 2022 maybe even earlier. My gpg-agent config looks as follows:
```
# pinentry-program /usr/bin/pinentry-curses
allow-loopback-pinentry
pinentry-program /home/chris/.local/bin/pinentry-bemenu
max-cache-ttl 34560000
default-cache-ttl 34560000
```

The Yubikey is set on signature policy "once", but the gpg-agent will still ask for a pin for EVERY signing operations. It's really annoying, especially when signing more than 2 files..

any idea?

**Comment by p3l1** [comment]
Same here, @shibumi. I had it working before on macos, but I switched my configuration to nix and now something has changed. I cannot figure out what it is. My yubikey has not been altered and the gpg config is also the same as far as I can see.
