### ISSUE TITLE
Undocumented OSX Python Dependency

### ISSUE THREAD

**Issue by skaht** [drduh/YubiKey-Guide#137]
Per https://developers.yubico.com/yubikey-manager/ there is an additional Python3 package dependency. Without performing `pip install yubikey-manager`, the **ykman** will never function.  The following error resulted:
 
```
% ykman info -c
dyld: Library not loaded: @executable_path/../.Python
```

It appears https://support.yubico.com/support/solutions/articles/15000012643-yubikey-manager-cli-ykman-user-guide is the closest thing to a man page for **ykman**.

**Comment by thisconnect** [comment]
`brew install ykman` worked fine for me. 

```
$ ykman info -c
Usage: ykman [OPTIONS] COMMAND [ARGS]...
Try "ykman -h" for help.

Error: No YubiKey detected!
```
