### ISSUE TITLE
Decrypt and mount the offline volume

### ISSUE THREAD

**Issue by Vilux** [drduh/YubiKey-Guide#144]
I'm having issues with rotating keys. I would like to get my master key off of my encrypted usb so that I can generate keys for another yubikey device, however I don't seem to be able to decrypt the volume. I have tried 
`sudo cryptsetup luksOpen /dev/sdb1 usb `
however nothing seems to happen. No errors and no prompts. What is the correct way to decrypt and mount the offline volume created earlier so that new devices can be loaded with keys?

**Comment by drduh** [comment]
`luksOpen` doesn't return any output on successful unlock. The next step is to mount the decrypted volume with something like `sudo mount /dev/mapper/usb /mnt`. Can you try that and see if it works? I can update the guide if so.

**Comment by Vilux** [comment]
Isn't luksOpen supposed to prompt for a passphrase? After running 
`sudo mount /dev/mapper/usb /mnt`
I get 
`mount: /mnt: special device /dev/mapper/usb does not exist`

**Comment by drduh** [comment]
Yes, it should. What does `lsblk /dev/sdb` or `sudo fdisk -l /dev/sdb` say?

**Comment by Vilux** [comment]
`lsblk /dev/sdb` returns
`NAME     MAJ:MIN   RM   SIZE   RO   TYPE   MOUNTPOINT`
`sdb                8:16          1  14.4G     0    disk`
`| --sdb1          8:17          1    10M      0    part`
`|---sdb2          8:18          1    10M      0    part   /media/user/556238eb-b372-4ac3-b249-af46485e71aa`
sorry for the formatting

**Comment by Vilux** [comment]
`sudo fdisk -l /dev/sdb` returns
`Disk /dev/sdb: 14.4 GiB, 15502147584 bytes, 30277632 sectors`
`Units: sectors of 1 * 512 = 512 bytes`
`Sector size (logical/physical): 512 bytes / 512 bytes`
`I/O size (minimum/optimal): 512 bytes / 512 bytes`
`Disklabel type: dos`
`Disk identifier: 0x139a746d`

`Device     Boot  Start      End  Sectors  Size  Id  Type`
`/dev/sdb1             2048  22527  20480    10M  83  Linux`
`/dev/sdb2           22528  43007  20480    10M  83  Linux`

**Comment by drduh** [comment]
Try the other partition - `sudo cryptsetup luksOpen /dev/sdb2 usb`

**Comment by Vilux** [comment]
Same thing as the first partition. No prompt for a passphrase and no errors.

**Comment by Vilux** [comment]
Got it to work by using VeraCrypt
