### ISSUE TITLE
ssh-add -L failing

### ISSUE THREAD

**Issue by Vilux** [drduh/YubiKey-Guide#145]
I don't seem to be able to add my yubikey's public key to ssh. When I run 
`ssh-add -L` I get `The agent has no identities.`
`sudo ssh-add -L` returns `Could not open a connection to your authentication agent.`
My yubikey seems to be recognized with `lsusb` but is not listed with `sudo fdisk -l`

**Comment by drduh** [comment]
Is `gpg-agent` running?

Try this: `pkill pinentry ; pkill gpg ; pkill ssh-agent; eval $(gpg-agent --daemon --enable-ssh-support)`

**Comment by Vilux** [comment]
`gpg-agent[8986]: gpg-agent is running and available`
When I run the commands you suggested it returns 
`gpg-agent: a gpg-agent is already starting - not starting a new one`
and I'm still getting the same error with ssh-add -L

**Comment by Vilux** [comment]
Fixed this by installing scdaemon
