### ISSUE TITLE
Use LUKS to encrypt the new partition failed.

### ISSUE THREAD

**Issue by Pagliacii** [drduh/YubiKey-Guide#149]
Hi, @drduh, I'm following the guide and stuck on "Backup > Use LUKS to encrypt the new partition". 

When I using `sudo cryptosetup luksFormat /dev/sdb1`, it failed with somethings like this:
```shell
WARNING: Data offset is outside of currently available data device.
Cannot wipe header on device /dev/sdb.
```

And I google it and find this [answer](https://askubuntu.com/questions/706585/cryptsetup-cannot-wipe-header-on-device), it seems looks like the partition size must be more than 10MB.

I try to remove the 10MB partition and recreate a new partition that size is 20MB. And I rerun the encrypt command, this time it works correctly.

I think you should know about this situation, so I open this issue. If I make mistakes, please tell me! Thanks!

**Comment by Pagliacii** [comment]
Btw, I am using the Debian standard live image which version is `10.2.0`, and the version of `cryptosetup` is `2.1.0`.

**Comment by drduh** [comment]
Thanks, nice catch. Fix incoming.

**Comment by Muhammad5232** [comment]
> Hi, @drduh, I'm following the guide and stuck on "Backup > Use LUKS to encrypt the new partition".
> 
> When I using `sudo cryptosetup luksFormat /dev/sdb1`, it failed with somethings like this:
> 
> ```shell
> WARNING: Data offset is outside of currently available data device.
> Cannot wipe header on device /dev/sdb.
> ```
> 
> And I google it and find this [answer](https://askubuntu.com/questions/706585/cryptsetup-cannot-wipe-header-on-device), it seems looks like the partition size must be more than 10MB.
> 
> I try to remove the 10MB partition and recreate a new partition that size is 20MB. And I rerun the encrypt command, this time it works correctly.
> 
> I think you should know about this situation, so I open this issue. If I make mistakes, please tell me! Thanks!

but i have 500mb size still persues the same issue
