### ISSUE TITLE
Your key can be imported on other machines without having a public key

### ISSUE THREAD

**Issue by avemilia** [drduh/YubiKey-Guide#150]
"Using keys" section seemingly requires a copy of public key, but in fact, things are much simpler: you just do `gpg --edit-card` and `fetch`. This will import your key even if its URL is not set. Then you just set the trust and it's all done.

Usually, when I configure a new installation I always have yubikey by my hand, but not the usb with backed up gpg files. Only yubikey is required to get and set up your key on a new machine.

**Comment by drduh** [comment]
This only works if the public key was uploaded to a keyserver though, right?

**Comment by avemilia** [comment]
Yes, seems like you are right: https://stackoverflow.com/questions/46689885/how-to-get-public-key-from-an-openpgp-smart-card-without-using-key-servers . Perhaps in my case the key was already uploaded, and gpg looked it up regardless of an empty URL field.
