### ISSUE TITLE
"save" drops back to shell (on Raspbian) & possible inconsistency in master key usage flags

### ISSUE THREAD

**Issue by Paraphraser** [drduh/YubiKey-Guide#151]
I'm following your excellent guide on a Raspberry Pi 4B.

I am finding that:

```
gpg> save
```

always drops me back to the shell, after which I need to:

```
$ gpg --expert --edit-key $KEYID
```

before proceeding to the next step.

I have not tested on other platforms so for all I know this may just be a Raspbian thing.

Also, in several places (eg "Add extra emails") the examples show "usage: SC" which seems to be inconsistent with earlier material. I've only seen "usage: C" since "S" was toggled off when the master key was first generated.

**Comment by drduh** [comment]
`usage: SC` is a minor cosmetic mistake - the master key should only have Certify capability. Feel free to fix it and make a note about Raspbian behavior in a PR. Thanks!
