### ISSUE TITLE
"throw-keyids" in gpg.conf can cause issues

### ISSUE THREAD

**Issue by patrickhanft** [drduh/YubiKey-Guide#152]
First thank you for your fantastic Yubikey-Guide! It was very helpful for me, when I moved to a new GPG key with the start of the new year.

However, as I also use GPG for my password manager (using https://passwordstore.org), I ran into an issue caused by a config parameter within your suggested gpg.conf. The issue was the same as it is documented here: https://github.com/android-password-store/Android-Password-Store/issues/173

It took me some days, to figure out, that the reason, that Android Password Store stopped working for me, had been caused by the way, my passwords had been encrypted using your hardened gpg.conf.

I do not suggest to change your defaults, but it would be great, if there was a little hint within your documentation, that this might be something to look into, when using pass on Android devices and that users should make an informed decission, if they want to have "throw-keyids" in their gpg.conf or not.

Thanks again and best regards!

**Comment by drduh** [comment]
I think it's up to Password Store to provide a meaningful error message for this situation.

**Comment by patrickhanft** [comment]
If you think so. It is your Guide and your project of course.

But I have to admit, that I did not expect a change of behaviour of GnuPG and there is no explanation given, what the hardened configuration for gpg.conf means. I just don't think it is wise to conceal, that there is a potential for side effects. I think, it is good to hint, that users might want to review this configuration.

I agree however, that it is not up to you to give piece of advice for special cases such as mine.

**Comment by drduh** [comment]
If you feel strongly about it, please send a pull request with the desired warning.

**Comment by apiraino** [comment]
Hi @patrickhanft I kind of stumbled on the same confusing behaviour (although in another context, I'm not using android-password-store) when encrypting with the suggested parameter `--throw-keyids` and thus encrypting the file anonymously (the KEYID will not show when inspecting the ecncypted file with `gpg --list-packets file.gpg`).

After a closer look at the gpg documentation, I understood that encrypted files with the recipient stripped away are then decrypted trying all keys (I assume in the order as they appear in `--list-secret-keys`), [explained here](https://www.gnupg.org/gph/en/manual/r2110.html).

In the latest version of @drduh suggested [gpg.conf](https://github.com/drduh/config/blob/d80601adb31efd51b59547ad51c7bd0f5445727d/gpg.conf#L44) there's a new parameter `default-key` that may improve this behaviour. Setting a preferred key when blindly decrypting a file might speed up the process (esp. when you have secret keys shielded with a passphrase of a PIN).

I think this could be a valuable mention in the guide, what do you think? I can produce a small PR for that

**Comment by fjerhammer** [comment]
A simple solution is to let Pass explicitly disable "throw-keyids" whenever it calls GPG:
`export PASSWORD_STORE_GPG_OPTS="--no-throw-keyids"`

**Comment by tweax-sarl** [comment]
I just would like to mention that I had a similar issue when I sent encrypted mails using GPG Mail to a recipient using Thunderbird. Until a couple of days ago (https://github.com/rnpgp/rnp/issues/1275), Thunderbird (with built-in gpg support) was unable to deal with encrypted mails where the key ID has been stripped.
