### ISSUE TITLE
Passphrase for imported ssh keys

### ISSUE THREAD

**Issue by mredaelli** [drduh/YubiKey-Guide#153]
The guide states:

> When using the key pinentry will be invoked to request the key's passphrase. The passphrase will be cached for up to 10 minutes idle time between uses, to a maximum of 2 hours.

I was wondering if there's any way to avoid having to enter a key passphrase (either when using they key, or even when importing it), and rely only on the physical presence of the YubiKey and its PIN.

If so, would it be severely insecure?

**Comment by peckeltw** [comment]
As far as I read this section of the guide correctly, it is "only" about importing a SSH key to the GPG agent, and NOT the YubiKey itself. So the imported key is not anyhow related to the YubiKey.

Maybe the section's title should read "Import SSH keys to GPG agent".

**Comment by mredaelli** [comment]
True.

My question is if, since the YubiKey is also available, can the passphrase be somehow skipped? Afterall, we are already protected by the key itself and its pin.

**Comment by peckeltw** [comment]
If you like to protect your (private) SSH key with a YubiKey and entering the PIN, you need to use a PGP key on the YubiKey and then use the `authentication` subkey of it for SSH purposes, as stated in this excellent guide. A key that is imported to GPG agent will never be protected by a YubiKey.
