### ISSUE TITLE
Are servers receiving the private key on upload?

### ISSUE THREAD

**Issue by Danrancan** [drduh/YubiKey-Guide#156]
Hi, I'm a bit of a newbie when it comes to the Yubikey, but I noticed something strange after following your guide, and if it's what I suspect, then it could potentially be pretty harmful. I BELIEVE, that I followed your guide to the tee. However, after doing so, I noticed that if I log into a clean Mac, install gpg-suite, and open up gpg keychain to search for and download my public key. THIS,  seems to work just fine, until I inspect further. With the GPG keychain showing the type as "pub", I double click on my pub key, open up the "key Details" panel, and then, right clicking my name in the signatures box, and clicking the "Download key" menu item. After downloading the sig3 key, my gpg keychain now shows my key type as "sec/pub". Did I do something incorrect to be able to download the secret key from the server? Or is there an error in the guide? Please note, my Yubikey is not plugged in when receiving this key (public and private). Please advise if you can!

**Comment by Paraphraser** [comment]
Hi - also a newbie, feeling my way where Macs are part of the deal.

Your issue worried me but I can't replicate your experience.

I also believe I followed the YubiKey-Guide, pretty much to the letter. My departures from the guide were:

1. I did not set an expiration on any of the sub keys; and
2. I used a different approach to storing a recovery copy of the master directory (encrypted DMG on the Mac).

I've just tried to follow in your footsteps on a High Sierra Mac that did not have gpg installed (ie a cleanskin).

Confirm GPG not installed:

```
$ which gpg
$
```

Install GPG:

```
$ brew update
$ brew upgrade
$ brew install gnupg yubikey-personalization hopenpgp-tools ykman pinentry-mac
$ brew cleanup
```

Confirm GPG now installed:

```
$ which gpg
/usr/local/bin/gpg
```

Run a command to initialise everything:

```
$ gpg -k
gpg: directory '/Users/home/.gnupg' created
gpg: keybox '/Users/home/.gnupg/pubring.kbx' created
gpg: /Users/home/.gnupg/trustdb.gpg: trustdb created
$ gpg -K
$
```

Everything set up but no keys present. Fetch the public key from a keyserver (all appropriately anonymised, of course):

```
$ gpg --keyserver hkps://keyserver.ubuntu.com:443 --recv 0123456789ABCDEF
gpg: key 0123456789ABCDEF: public key "My Name (Comment) <someone@one.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

Look at the state of play:

```
$ gpg -k
/Users/home/.gnupg/pubring.kbx
----------------------------------
pub   rsa4096 2019-12-24 [C]
      AABBCCDDEEFF0011223344550123456789ABCDEF
uid           [ unknown] My Name (Comment) <someone@one.com>
uid           [ unknown] My Name (Comment) <someone@two.com>
uid           [ unknown] My Name (Comment) <someone@six.com>
sub   rsa4096 2019-12-24 [A]
sub   rsa4096 2019-12-24 [E]
sub   rsa4096 2019-12-24 [S]

$ gpg -K
$
```

To me, the first command that says the public key has been installed and that it knows about three sub-keys, while the second command says "no private keys are known".

> I see this same pattern on a cleanskin Raspberry Pi. Install the required tools, import the public key, list the public and private keys. Identical output to the Mac.

Then I wondered about the "I double click on my pub key" part of your post.

```
$ ls -alR *
srwx------  1 home  staff     0 Jan 18 19:16 S.dirmngr
srwx------  1 home  staff     0 Jan 18 19:16 S.gpg-agent
srwx------  1 home  staff     0 Jan 18 19:16 S.gpg-agent.browser
srwx------  1 home  staff     0 Jan 18 19:16 S.gpg-agent.extra
srwx------  1 home  staff     0 Jan 18 19:16 S.gpg-agent.ssh
-rw-r--r--  1 home  staff  6701 Jan 18 19:16 pubring.kbx
-rw-------  1 home  staff    32 Jan 18 19:16 pubring.kbx~
-rw-------  1 home  staff  1200 Jan 18 19:16 trustdb.gpg

crls.d:
total 8
drwx------   3 home  staff  102 Jan 18 19:16 .
drwx------  13 home  staff  442 Jan 18 19:21 ..
-rw-r--r--   1 home  staff    5 Jan 18 19:16 DIR.txt

private-keys-v1.d:
total 0
drwx------   2 home  staff   68 Jan 18 19:16 .
drwx------  13 home  staff  442 Jan 18 19:21 ..
```

I didn't expect it to work but I opened that folder in the Finder then double-clicked on pubring.kbx and trustdb.gpg. Finder chucked up the dialog that means "don't know how to open that".

Basically, this is the point where I cease to be able to follow in your footsteps so - dunno. Looks to me like there is only **public** key material on this machine.

Moving the goal-posts slightly to a machine where I did the same as the above but then proceeded to connect and use the YubiKey:

```
$ gpg -k
/Users/home/.gnupg/pubring.kbx
----------------------------------
pub   rsa4096/0x0123456789ABCDEF 2019-12-24 [C]
      Key fingerprint = AABB CCDD EEFF 0011 2233  4455 0123 4567 89AB CDEF
uid                   [ultimate] My Name (Comment) <someone@one.com>
uid                   [ultimate] My Name (Comment) <someone@two.com>
uid                   [ultimate] My Name (Comment) <someone@six.com>
sub   rsa4096/0xF0123456789ABCDE 2019-12-24 [S]
sub   rsa4096/0xEF0123456789ABCD 2019-12-24 [E]
sub   rsa4096/0xDEF0123456789ABC 2019-12-24 [A]

$ gpg -K
/Users/home/.gnupg/pubring.kbx
----------------------------------
sec#  rsa4096/0x0123456789ABCDEF 2019-12-24 [C]
      Key fingerprint = AABB CCDD EEFF 0011 2233  4455 0123 4567 89AB CDEF
uid                   [ultimate] My Name (Comment) <someone@one.com>
uid                   [ultimate] My Name (Comment) <someone@two.com>
uid                   [ultimate] My Name (Comment) <someone@six.com>
ssb>  rsa4096/0xF0123456789ABCDE 2019-12-24 [S]
ssb>  rsa4096/0xEF0123456789ABCD 2019-12-24 [E]
ssb>  rsa4096/0xDEF0123456789ABC 2019-12-24 [A]

```

Based on the YubiKey-Guide, I take that to mean that the public keys are present, the master key is not present ("sec#") and the private keys for signing, encryption and authentication are to be found on the YubiKey ("ssb>").

I also interpret the difference in output between a machine where the YubiKey has **never** been connected and a machine where it **has**, as implying that the YubiKey is the source of all the extra information.

I hope this helps.

**Comment by peckeltw** [comment]
@Danrancan the behaviour you mention is correct and as intended. When moving the keys to the YubiKey, stub keys are created: https://wiki.debian.org/GnuPG/StubKeys

They are just pointers to the private key on the YubiKey, so nothing to worry about that. I use Thunderbird from time to time, and Enigmail, the GPG plugin, lists my key as "pub/sec" as well because of the stub keys. So @Paraphraser is right: the private key is on the YubiKey. Everything is correct.

You should check your setup with `gpg -K` which should give you are similar output as it did for @Paraphraser :

```
$ gpg -K
/Users/home/.gnupg/pubring.kbx
----------------------------------
sec#  rsa4096/0x0123456789ABCDEF 2019-12-24 [C]
      Key fingerprint = AABB CCDD EEFF 0011 2233  4455 0123 4567 89AB CDEF
uid                   [ultimate] My Name (Comment) <someone@one.com>
uid                   [ultimate] My Name (Comment) <someone@two.com>
uid                   [ultimate] My Name (Comment) <someone@six.com>
ssb>  rsa4096/0xF0123456789ABCDE 2019-12-24 [S]
ssb>  rsa4096/0xEF0123456789ABCD 2019-12-24 [E]
ssb>  rsa4096/0xDEF0123456789ABC 2019-12-24 [A]
```

Check for the`#` and the `>` as documented [here](https://wiki.debian.org/GnuPG/StubKeys).

**Comment by Danrancan** [comment]
> @Danrancan the behaviour you mention is correct and as intended. When moving the keys to the YubiKey, stub keys are created: https://wiki.debian.org/GnuPG/StubKeys
> 
> They are just pointers to the private key on the YubiKey, so nothing to worry about that. I use Thunderbird from time to time, and Enigmail, the GPG plugin, lists my key as "pub/sec" as well because of the stub keys. So @Paraphraser is right: the private key is on the YubiKey. Everything is correct.
> 
> You should check your setup with `gpg -K` which should give you are similar output as it did for @Paraphraser :
> 
> ```
> $ gpg -K
> /Users/home/.gnupg/pubring.kbx
> ----------------------------------
> sec#  rsa4096/0x0123456789ABCDEF 2019-12-24 [C]
>       Key fingerprint = AABB CCDD EEFF 0011 2233  4455 0123 4567 89AB CDEF
> uid                   [ultimate] My Name (Comment) <someone@one.com>
> uid                   [ultimate] My Name (Comment) <someone@two.com>
> uid                   [ultimate] My Name (Comment) <someone@six.com>
> ssb>  rsa4096/0xF0123456789ABCDE 2019-12-24 [S]
> ssb>  rsa4096/0xEF0123456789ABCD 2019-12-24 [E]
> ssb>  rsa4096/0xDEF0123456789ABC 2019-12-24 [A]
> ```
> 
> Check for the`#` and the `>` as documented [here](https://wiki.debian.org/GnuPG/StubKeys).

Thank you so much for getting back to me and confirming that this is indeed what is supposed to happen. This answer helped me greatly and indeed will help other newbs noticing this and flagging it as a possible issue. I am glad to know I didn't upload my private key to the key server and glad to know that I can disregard the post from @Paraphraser , as he could not recreate the issue entirely. Which had me frightened. Also, I dearly apologize for the late response to your post. I have just been swamped with life and it took a while to get back to you. Better late than never, and I'm always late. lol. Thanks so much again! Cheers!

**Comment by Danrancan** [comment]
@peckeltw 
> @Danrancan the behaviour you mention is correct and as intended. When moving the keys to the YubiKey, stub keys are created: https://wiki.debian.org/GnuPG/StubKeys
> 
> They are just pointers to the private key on the YubiKey, so nothing to worry about that. I use Thunderbird from time to time, and Enigmail, the GPG plugin, lists my key as "pub/sec" as well because of the stub keys. So @Paraphraser is right: the private key is on the YubiKey. Everything is correct.
> 
> You should check your setup with `gpg -K` which should give you are similar output as it did for @Paraphraser :
> 
> ```
> $ gpg -K
> /Users/home/.gnupg/pubring.kbx
> ----------------------------------
> sec#  rsa4096/0x0123456789ABCDEF 2019-12-24 [C]
>       Key fingerprint = AABB CCDD EEFF 0011 2233  4455 0123 4567 89AB CDEF
> uid                   [ultimate] My Name (Comment) <someone@one.com>
> uid                   [ultimate] My Name (Comment) <someone@two.com>
> uid                   [ultimate] My Name (Comment) <someone@six.com>
> ssb>  rsa4096/0xF0123456789ABCDE 2019-12-24 [S]
> ssb>  rsa4096/0xEF0123456789ABCD 2019-12-24 [E]
> ssb>  rsa4096/0xDEF0123456789ABC 2019-12-24 [A]
> ```
> 
> Check for the`#` and the `>` as documented [here](https://wiki.debian.org/GnuPG/StubKeys).

> @Danrancan the behaviour you mention is correct and as intended. When moving the keys to the YubiKey, stub keys are created: https://wiki.debian.org/GnuPG/StubKeys
> 
> They are just pointers to the private key on the YubiKey, so nothing to worry about that. I use Thunderbird from time to time, and Enigmail, the GPG plugin, lists my key as "pub/sec" as well because of the stub keys. So @Paraphraser is right: the private key is on the YubiKey. Everything is correct.
> 
> You should check your setup with `gpg -K` which should give you are similar output as it did for @Paraphraser :
> 
> ```
> $ gpg -K
> /Users/home/.gnupg/pubring.kbx
> ----------------------------------
> sec#  rsa4096/0x0123456789ABCDEF 2019-12-24 [C]
>       Key fingerprint = AABB CCDD EEFF 0011 2233  4455 0123 4567 89AB CDEF
> uid                   [ultimate] My Name (Comment) <someone@one.com>
> uid                   [ultimate] My Name (Comment) <someone@two.com>
> uid                   [ultimate] My Name (Comment) <someone@six.com>
> ssb>  rsa4096/0xF0123456789ABCDE 2019-12-24 [S]
> ssb>  rsa4096/0xEF0123456789ABCD 2019-12-24 [E]
> ssb>  rsa4096/0xDEF0123456789ABC 2019-12-24 [A]
> ```
> 
> Check for the`#` and the `>` as documented [here](https://wiki.debian.org/GnuPG/StubKeys).

Thank you so much for getting back to me and confirming that this is indeed what is supposed to happen. This answer helped me greatly and indeed will help other newbs noticing this and flagging it as a possible issue. I am glad to know I didn't upload my private key to the key server and glad to know that I can disregard the post from @Paraphraser , as he could not recreate the issue entirely. Which had me frightened. Also, I dearly apologize for the late response to your post. I have just been swamped with life and it took a while to get back to you. Better late than never, and I'm always late. lol. Thanks so much again! Cheers!
