### ISSUE TITLE
Creating new Subkeys after Expiration

### ISSUE THREAD

**Issue by psebening** [drduh/YubiKey-Guide#162]
I run into problems with expiration dates soon and wanted to ask: how is the process to add new subkeys after the first set of subkeys expired.

Can I do this with the yubikey itself?

When I run
`gpg —expert —edit-key KEYID_OF_MASTERKEY` the output is
`Secret Key is available`

After this when I run the `addkey` command however the output is `This requires your secret key.`

Is this an issue of the gpg-client relying on the stub of the secret key in the keychain or can I explicitly ask gpg to use the secret key that is on the smartcard?

**Comment by donnex** [comment]
I recently did this after having my YubiKey for a year now as well :)

See the section about rotating keys in the guide https://github.com/drduh/YubiKey-Guide#rotating-keys

You need the master key to update sub keys and that'll only be available if you setup the isolated offline environment and import your GPG backup files. This is of course dependent on how you setup the original key and how you backed it up.

This is how I did it:
- imported my master key and subkeys offline
- changed/updated my sub keys and extended expire date
- backed everything up
- used `keytocard` and send the new keys to the YubiKey
- exported the updated public key and imported on the machines where I use the YubiKey

You can also generate a whole new set of subkeys but that is more work. The section in the guide explains this.

**Comment by snajby** [comment]
s

Dne út 28. 1. 2020 20:25 uživatel Daniel Johansson <notifications@github.com>
napsal:
