### ISSUE TITLE
Alternative way to create multiple yubikeys / smartcard / retain key on host

### ISSUE THREAD

**Issue by murphy83** [drduh/YubiKey-Guide#163]
Hi,
Thanks for this great tutorial!

Transfering keys to a smartcard is normally destructive, as you mention. But you may just abort all operations after the transfer is complete (eg. after the third key for authentification). It is possible to use CTRL+C to quit gpg directly. Afterwards, plug in the next key you want to use and repeat until all devices are equipped.

This way you may also create a complete backup of your whole setup for save storage: I a clean and isolated environment to manage my keys, as it is already written in the tutorial. Therefore I boot to this environment via USB-Stick or SDCard (it depends on your preferences and hardware which one works out better).
In addition to the normal backup to an external media (eg. SDCard) as proposed I also store the complete SDCard/USB Stick in a save place (for security reasons, the backup is stored in another place)

I can write a pull request if you like to have theses changes included.

**Comment by drduh** [comment]
Tips and usability suggestions are most welcome in a pull request!
