### ISSUE TITLE
"Rotating Keys" section discusses renewing keys but does not provide instructions

### ISSUE THREAD

**Issue by codesections** [drduh/YubiKey-Guide#164]
The "Rotating Keys" section describes the trade offs between renewing or rotating sub-keys, and then sounds as though it will provide instructions for either:
> To renew or rotate sub-keys, follow the same procedure to boot to a secure environment.

However, the actual instructions given ("Follow the original steps to generate each sub-key. Previous sub-keys may be kept or deleted from the identity.  Finish by exporting new keys:" and following text) apply only to rotating sub-keys, not to renewing them.

I believe that the steps for renewing sub-keys are significantly less involved (something like `--edit-key`, `expire`, select new expiration date) and – I believe – does not require changing the master key in any way.  If that is correct, then any other master key backups would not need to be updated (unlike when rotating subkeys), correct?  If I were slightly more confident in my understanding of this process, I would have submitted a PR instead of opening an issue.

Even if renewing keys is less complicated than rotating them, it would be very helpful to have the full process documented in this guide – as my confusion about the details above might illustrate.

Thanks so much for the guide, by the way!

**Comment by drduh** [comment]
Should be fixed in the recent PR, feel free to author additional improvements as you see fit. Thanks!

**Comment by oblitum** [comment]
Hi, as a newbie I'm a bit confused by the new "renew" section. It just states that nothing is necessary except for renewing the subkeys, exporting and then importing on the machines you use. No need to push keys to the yubikey or servers. I did this for two machines and it's fine, but I'll always need the exported public key file for that, shouldn't there be an explanation for the case I have just the yubikey at hand and internet on a new machine?
