### ISSUE TITLE
Security Keys support on OpenSSH 8.2p1

### ISSUE THREAD

**Issue by mhalano** [drduh/YubiKey-Guide#166]
OpenSSH 8.2p1 was just released and this version has support to generate keypairs using FIDO/U2F keys like YubiKey itself, so would be nice to have some document about this feature.

**Comment by peckeltw** [comment]
@mhalano I guess a PR is more than welcome!

**Comment by drduh** [comment]
Sounds interesting! Can you link to any documentation or introduce a PR with more information? Thanks.

**Comment by mjbnz** [comment]
Also of note is that RSA SHA-1 keys will be being deprecated in a future release. I'm not familiar enough to know what gnupg is presenting via it's agent, but that might rule out OpenPGP use for SSH in the future?

**Comment by mjbnz** [comment]
More details here: [https://www.openssh.com/txt/release-8.2](https://www.openssh.com/txt/release-8.2)

**Comment by exussum12** [comment]
Command used to save scrolling `ssh-keygen -t ecdsa-sk -f ~/.ssh/id_ecdsa_sk`

**Comment by crash5** [comment]
> Also of note is that RSA SHA-1 keys will be being deprecated in a future release. I'm not familiar enough to know what gnupg is presenting via it's agent, but that might rule out OpenPGP use for SSH in the future?


from here: https://levelup.gitconnected.com/demystifying-ssh-rsa-in-openssh-deprecation-notice-22feb1b52acd?gi=dd2ed6e2c3

> As a key format, “ssh-rsa” has no relation to SHA1. It can be found in files such as authorized_keys, known_hosts and id_rsa.pub. And, as encoded string within the public key blob. These won’t be deprecated.

**Comment by drduh** [comment]
If this works well for you, please document it along with your OS version in the guide using a PR.
