### ISSUE TITLE
PKCS#11 cards

### ISSUE THREAD

**Issue by mhalano** [drduh/YubiKey-Guide#167]
The guide so far explains how to use OpenPGP card function, but would be nice to learns how to use the actually smart card using the standard PKCS#11. There are some differences about how to use because the modules, but it's possible to use SSH with PKCS#11 modules.

**Comment by drduh** [comment]
What are some advantages of doing this? Is there benefit over using OpenPGP?

**Comment by dragon788** [comment]
I believe for Active Directory environments there is an AD attribute where a user can store a certificate or they can request one from the CA for the domain and then use that as their user certificate, or maybe I'm conflating a couple technologies of LDAP and AD. PKCS#11 and PKCS#12 are only one digit apart....

The main thing is I think it is better supported as a smart card user login mechanism in some operating systems without requiring special shims.

**Comment by rcaught** [comment]
> What are some advantages of doing this? Is there benefit over using OpenPGP?

https://ruimarinho.gitbooks.io/yubikey-handbook/content/piv/use-cases.html

The whole handbook above is an excellent resource and I would personally love to see a convergence these two excellent guides (@ruimarinho).

I've always thought that the ideal setup is both GPG and PIV applications running, with:
- The GPG interface primarily used for Git signing
- The PKCS#11 interface used for SSH login (no need for gpg-agent), OS logins and OpenVPN

**Comment by TheDarkTrumpet** [comment]
Personally, I'd be interested in how to use PKCS for ssh over gpg.  I'm not sure if there's a strict advantage, but as it stands I have both PKCS and GPG on my yubikey.  PKCS for login into OSX, and GPG for ssh/git/emails/etc.  While the steps for SSH GPG aren't super long, if it could be simplified with PKCS, then that could be useful when setting up new machines.

**Comment by patbel-pwr** [comment]
@drduh @TheDarkTrumpet You have advantages as well as drawbacks of PIV described here: 
https://developers.yubico.com/PIV/Guides/Securing_SSH_with_OpenPGP_or_PIV.html#piv
and setup guide here:
https://developers.yubico.com/PIV/Guides/SSH_user_certificates.html

**Comment by drduh** [comment]
To anyone using this method: please send a PR creating an "Alternatives" or similar section in the guide and document your experience, pro/cons, and make your recommendation.
