### ISSUE TITLE
gpg: decryption failed: No secret key and gpg: signing failed: PIN blocked

### ISSUE THREAD

**Issue by lucaszanella** [drduh/YubiKey-Guide#168]
I'm getting these errors:

```
user@social:~$ gpg --list-keys
/home/user/.gnupg/pubring.kbx
-----------------------------
pub   rsa4096/0xD7C5BA02E4FC5B75 2020-02-29 [C]
      Key fingerprint = 85D5 B129 3B72 4C81 84EA  EA9B D7C5 BA02 E4FC 5B75
uid                   [ultimate] Lucas Zanella <me@lucaszanella.com>
uid                   [ultimate] Lucas Zanella <eu@lucaszanella.com>
sub   rsa4096/0x2DAB5FDB8F7ED9D6 2020-02-29 [S] [expires: 2022-02-28]
sub   rsa4096/0x1E5F5325044FB8DA 2020-02-29 [E] [expires: 2022-02-28]
sub   rsa4096/0xBA31C8521902C756 2020-02-29 [A] [expires: 2022-02-28]

user@social:~$ echo "test message string" | gpg --encrypt --armor --recipient $KEYID -o encrypted.txt
File 'encrypted.txt' exists. Overwrite? (y/N) y
user@social:~$ gpg --decrypt --armor encrypted.txt
gpg: anonymous recipient; trying secret key 0x1E5F5325044FB8DA ...
gpg: encrypted with RSA key, ID 0x0000000000000000
gpg: decryption failed: No secret key
user@social:~$ echo "test message string" | gpg --armor --clearsign > signed.txt
gpg: signing failed: PIN blocked
gpg: [stdin]: clear-sign failed: PIN blocked
user@social:~$ echo "test message string" | gpg --armor --clearsign > signed.txt
gpg: signing failed: PIN blocked
gpg: [stdin]: clear-sign failed: PIN blocked
user@social:~$ echo "test message string" | gpg --encrypt --armor --recipient $KEYID -o encrypted.txt
File 'encrypted.txt' exists. Overwrite? (y/N) y
user@social:~$ gpg --decrypt --armor encrypted.txt
gpg: anonymous recipient; trying secret key 0x1E5F5325044FB8DA ...
gpg: encrypted with RSA key, ID 0x0000000000000000
gpg: decryption failed: No secret key
user@social:~$ echo "test message string" | gpg --armor --clearsign > signed.txt
gpg: signing failed: PIN blocked
gpg: [stdin]: clear-sign failed: PIN blocked
user@social:~$ echo "test message string" | gpg --armor --clearsign > signed.txt
gpg: signing failed: PIN blocked
gpg: [stdin]: clear-sign failed: PIN blocked

```

after setting everything in my yubikey. Do you have any idea? it looks like I have the keys in my yubikey, but it says "no secret key". Then in the signing attempt it says "PIN blocked"

**Comment by lucaszanella** [comment]
If I open yubico manager and go to "PIV" I see:

PIN: 3 retries left
PUK: PIN unlock key

**Comment by jsfrederick** [comment]
> If I open yubico manager and go to "PIV" I see:
> 
> PIN: 3 retries left
> PUK: PIN unlock key

The YubiKey Manager ONLY manages the PIN's on the PIV module, NOT the GPG module.  You will need to reset the GPG Module to reset the PIN.  If you don't have backups of your GPG keys, you'll need to recreate.

**Comment by lucaszanella** [comment]
@jsfrederick do you know how to do it? Can t find on google

**Comment by jsfrederick** [comment]
The Yubico web site is your friend.

https://support.yubico.com/support/solutions/articles/15000006421-resetting-the-openpgp-applet-on-the-yubikey

**Comment by lucaszanella** [comment]
@jsfrederick thank you and sorry, I was trying to do with ykman but couldn't install on debian9 in any way. Ended up having to manually do everything.
Now I don't know how to import my backup back into the yubikey. Could you help me? I'll write a pull request with the instructions because I couldn't find on google

**Comment by lucaszanella** [comment]
How to use these files:

```
gpg.conf
mastersub.key
openpgp-recovs.d
private-keys-v1.d (contains 4 .key files)
pubring.kbx
random_seed
reader_0.status
sub.key
tofu.db
trustdb.gpg
```
to put keys back into my yubikey?

**Comment by michael-k** [comment]
@lucaszanella boot the live OS, mount your backup, and
- `export GNUPGHOME=$(mktemp -d)`
- copy the files from your backup to `$GNUPGHOME`: `cp -avi /path/to/backup/* $GNUPGHOME/`
- umount your backup
- `gpg -K` should list your keys
- transfer the keys and follow the relevant parts of the rest of the tutorial (esp. *Verify card*, *Cleanup*, and *Using keys*): https://github.com/drduh/YubiKey-Guide#transfer-keys

**Comment by drduh** [comment]
Thanks for everyone's help on this issue!

**Comment by tacticalpacket** [comment]
I just wanted to thank you guys for covering this!  I have been stuck on this for a week now and haven't been able to find anything helpful.  

While this explains _HOW_ to fix this it doesn't say _WHY_ it happened.  If I wanted to learn more about the difference in the gpg PIN module retries vs. the yubikey PIN module retries where would I go?  I am not sure I wont break it again immediately after fixing it.  I don't know what PIN to enter when pinentry-mac pops up on me.

I am not sure if replying on a closed issue is poor etiquette but I wasn't sure how to summarize all of this otherwise.  Please let me know if I should have done something differently.

Lastly, I can't believe @drduh is on here!  Thank you so much for your guide.  I could probably recite it from memory at this point.  Its been so helpful in my gpg and yubikey learning.

**Comment by slwst** [comment]
I'm not sure if this is a recent development, but I was able to reset a blocked pin via `gpg` without resetting the GPG module on the yubikey.  To do this:

- `gpg --edit-card`
- `admin`
- `passwd`
- select option `2 - unblock PIN`
- enter your admin PIN and set the user PIN again

To verify, run `gpg --card-status` and check that PIN retry counter is `3 0 3`
