### ISSUE TITLE
How to recover a backup?

### ISSUE THREAD

**Issue by lucaszanella** [drduh/YubiKey-Guide#169]
This is something very important and it's missing. I've searched google but couldn't find anything. Asked on some forums and I'm waiting for an answer. If someone knows how to do it, please help me, so I can write a pull request and also do in mine.

**Comment by johnholden** [comment]
I'm not an expert but I was verifying my back up YubiKey and had the following experiences:

* You can switch between devices for GPG purposes using [these commands](https://github.com/drduh/YubiKey-Guide#multiple-keys).
* If you need to restore from the encrypted backup (a flash drive, SD card, etc) to a new YubiKey, you'll need to [mount that filesystem and copy the files](https://github.com/drduh/YubiKey-Guide#multiple-yubikeys), then you can repeat the [Configure Smartcard](https://github.com/drduh/YubiKey-Guide#configure-smartcard) steps.
* To my knowledge, the only way to have a "backup" for a U2F login is through whatever the website/service provides. Some let you add multiple keys, others allow for backup via OTP/SMS, and some don't have anything.

**Comment by drduh** [comment]
The recovery mechanism is mounting your offline master secret key, which gives you full authority over the PGP identity. The rotating keys section now has more detail about doing this. Hope that helps!
