### ISSUE TITLE
Signing Github commits with the master key

### ISSUE THREAD

**Issue by Sebazzz** [drduh/YubiKey-Guide#171]
Early in the guide, `$KEYID` is assigned as being the identifier of the master key.

Later on, in the [Github section](https://github.com/drduh/YubiKey-Guide#github), the signing key is configured:

    git config --global user.signingkey $KEYID

Does this automatically use the signing sub-key created earlier, or does `KEYID` in this case need to point to the signing key ID? For the layman it looks like we're now signing commits using the master key!

**Comment by CyberiumShadow** [comment]
It'll automatically use the Signing key
