### ISSUE TITLE
Are both export and backup necessary?

### ISSUE THREAD

**Issue by Ch00k** [drduh/YubiKey-Guide#173]
I don't understand why _both_ export and backup are necessary. From what I understand, the use cases for doing either of them are transferring keys to a different yubikey, generating other subkeys, modifying existing subkeys (e.g. their expiration). All of these should be possible after importing the previously exported master and/or subkeys. Why would a backup of the whole `.gnupg` directory be necessary then?

**Comment by michael-k** [comment]
Not necessary but: It's always good to use multiple ways when creating backups.  (And ideally also test them.¹)

¹ Setting the expiration date on the sub keys to 1 year as suggested in https://github.com/drduh/YubiKey-Guide#sub-keys, forces you to “test” at least one of them once a year.

**Comment by drduh** [comment]
Backup isn't necessary and there may even be benefit in skipping it - it all depends on your use case and threat model. The guide recommends doing both to strike a balance of usability and is perhaps overly conservative when it comes to recovery planning.
