### ISSUE TITLE
How to use nodejs or webusb read smartcard and unlock pin ?

### ISSUE THREAD

**Issue by athlona64** [drduh/YubiKey-Guide#174]
how to use nodejs or webusb read smartcard and unlock pin for read PIV unlock gpg 

like this
```gpg --decrypt --armor pgp.key```

**Comment by dragon788** [comment]
Check out the Chrome Smart Card Connector extension which is used by the Secure Shell extension/app. It can access the Yubikey smartcard/CCID interface to use view the public key and supply the pin to access the private key for authentication.

**Comment by drduh** [comment]
If you figure it out, please send a PR detailing the process. Thanks!
