### ISSUE TITLE
Add warning to Backup section when using a USB LiveOS

### ISSUE THREAD

**Issue by 05nelsonm** [drduh/YubiKey-Guide#176]
Executing the command `sudo dd if=/dev/urandom of=/dev/sdb bs=4M status=progress` targeted the LiveUSB OS of Tails that I was using, requiring me to restart everything from scratch.

**Comment by apiraino** [comment]
Well, that section mentions "Attach another external storage device and *check its label*" (emphasys mine).

I assume you're suggesting the warning is not prominent enough?

**Comment by 05nelsonm** [comment]
For sure. It was definitely my bad for moving too quickly.

Yes, a more prominent warning would be beneficial to prevent wiping the wrong USB (in my case, the one that was running Tails).
