### ISSUE TITLE
"Key does not match the card's capability" on Yubikey Neo - not just a 4096/2048 issue

### ISSUE THREAD

**Issue by smcl** [drduh/YubiKey-Guide#18]
I encountered this error even though I knew to select 2048 bit keys. The version of ```gpg``` I have is 1.4.20 - and if I switch to using ```gpg2``` (version 2.1.11) the keys save correctly.

**Comment by drduh** [comment]
I'm not really sure about this one. I do recommend the newer, more feature-rich gnupg2 as the package candidate in the guide, in both the installation and troubleshooting sections; gnupg1 users are on their own. Let me know if you do figure out what specifically about version 1.4.20 is incompatible.
