### ISSUE TITLE
Possibly add a ChromeOS section if users have access to one of these inexpensive devices that is easy to wipe

### ISSUE THREAD

**Issue by dragon788** [drduh/YubiKey-Guide#182]
Another possibility I thought of recently if you wanted a cheap candidate for mostly airgapped GPG key generation is using a Chromebook in Developer Mode and the Crouton chroot utility to create a Debian (Buster) or Ubuntu (Xenial) filesystem where you can generate your keys and then delete the chroot and powerwash the system to securely eliminate all traces of the activities that occurred. The additional benefit of using a Chromebook is once you've reset it you sign into your Google account again and all your bookmarks and everything else are back.

The reason you need Crouton is the Crostini "Linux apps" environment available on newer Chromebooks is a container inside a secure VM that doesn't have direct access to USB devices of any sort so you can't put your backup on a USB key and you can't access the smartcard/CCID interface of the Yubikey to `keytocard` the GPG keys onto it.

**Comment by drduh** [comment]
Sounds like a fine idea. Maybe add a hardware section that explains the process in more detail and why it might be worth doing?

**Comment by TheDarkTrumpet** [comment]
I think this would be helpful.  Another thing is to describe the reasons for some of the security surrounding key creation on an airgapped machine.  TBH, I ended up doing mine on my main workstation since I don't have really an airgapped PC.

The chromebook came up in a separate conversation that has me thinking it may be worth picking one of those up, installing qubes, and using it for stuff like this.

**Comment by dragon788** [comment]
Installing Qubes on a Chromebook could be an exercise in patience and creativity, but if you get it working definitely document it!

**Comment by drduh** [comment]
Closing for now due to inactivity, but definitely interested in seeing more hardware documentation in the future. Please send us your PRs!
