### ISSUE TITLE
Add Yubikey Agent

### ISSUE THREAD

**Issue by exussum12** [drduh/YubiKey-Guide#186]
https://github.com/FiloSottile/yubikey-agent

This has wider support than openSSH 8.2 as it doesnt require a new key type.
An alternative which is easier to set up than the gpg agent.

Currently its not a package manager install away, so not sure if thats worth documenting here or pointing to the readme

**Comment by drduh** [comment]
I'll get around to this eventually, or beat me to it with a PR.
