### ISSUE TITLE
Question on git signing

### ISSUE THREAD

**Issue by TheDarkTrumpet** [drduh/YubiKey-Guide#188]
Hello,

First, I wanted to thank you for the excellent guide.  Took me about 3 hours, but I was able to follow it and things are working very well.

One question I had was regarding signing of commits.  If I want to, by default, sign all commits and make many of them, I have to currently enter my pin every time I commit.  This can be quite a bit in an hour.  Is there a way to prompt on initial insert and not again til ejected?  Similar to how it works with SSH, that caches just fine and as long as I don't eject it, it won't prompt for the pin again.

Thanks again.

**Comment by michael-k** [comment]
I have to enter the pin the first time it's needed and then never again until I remove the YubiKey.

`gpg --card-status` says `Signature PIN ....: not forced`.  Your config probably says `Signature PIN ....: forced`, right?

**Comment by TheDarkTrumpet** [comment]
Thanks for the help, you're right - it was set to forced sign

One thing I ended up also having to do to get things working properly on other machines is run "gpg -card-edit" and "fetch".  Strangely enough, I had to do that also on my machine I set this up under to get my email signing (through Evolution) to work properly.  Once I did the fetch on the macbook pro (I set this up on arch linux first), both git and email worked there, too.  I don't know if this is useful anywhere in your guide, but figured I'd mention it

Again, thank you very much for the fantastic writeup.  This whole thing was an amazing read, very seamless, and incredibly helpful.

I don't know if you plan on doing any other guides, but maybe some more advanced uses for the yubikey would be nice.  Right now using it as a google auth replacement, login into my mac, signing git commits,  signing emails, and some yubi-auth options into sites (like Github).  Little else outside that.  If you're using it for other really cool stuff, I think a lot of us would like to hear those options.  Really diving into security lately, and really want to find more ways of using this.  I'm glad you also mentioned areas such as encryption of files and the like in your article.

On a side note.  I'm planning on developing some scripts to help make the encryption/decryption easier.  Similar to what you provided, but not dropping stuff in the home directory.  So, overall minor changes.  I don't know if you accept pull requests, but I can provide those tweaks when I finish them.  Please let me know!

**Comment by TheDarkTrumpet** [comment]
@drduh - Noticed you weren't brought into this, wanted to ping you regarding the ability to help and some expansion ideas.
