### ISSUE TITLE
Cannot dowload hardened gpg.conf with Tails 4.6

### ISSUE THREAD

**Issue by foundationer** [drduh/YubiKey-Guide#192]
Hi

I'm using Tails 4.6 on a 16 GB USB drive with persistence configured. I'm getting this error when I try to download the hardened gpg.conf file:

root@amnesia:~# wget -O $GNUPGHOME/gpg.conf https://raw.githubusercontent.com/drduh/config/master/gpg.conf
--2020-05-31 17:43:25--  https://raw.githubusercontent.com/drduh/config/master/gpg.conf
Resolviendo raw.githubusercontent.com (raw.githubusercontent.com)... 1590947006 PERROR torsocks[16185]: socks5 libc connect: Conexión rehusada (in socks5_connect() at socks5.c:202)
falló: Fallo irrecuperable en la resolución del nombre.
wget: no se pudo resolver la dirección del equipo “raw.githubusercontent.com”

The error is in spanish. Basically says "connection refused" and that it couldn't resolve the address. The Tails documentation says that everything you download goes through Tor. Is there a way to download the file through a Tor proxy?

**Comment by jakommo** [comment]
You can use the "unsafe browser" to download content from none tor sites. See https://tails.boum.org/contribute/design/Unsafe_Browser/Am 31.05.2020 19:56 schrieb Lucas Godoy <notifications@github.com>:

Hi

I'm using Tails 4.6 on a 16 GB USB drive with persistence configured. I'm getting this error when I try to download the hardened gpg.conf file:

root@amnesia:~# wget -O $GNUPGHOME/gpg.conf https://raw.githubusercontent.com/drduh/config/master/gpg.conf

--2020-05-31 17:43:25--  https://raw.githubusercontent.com/drduh/config/master/gpg.conf

Resolviendo raw.githubusercontent.com (raw.githubusercontent.com)... 1590947006 PERROR torsocks[16185]: socks5 libc connect: Conexión rehusada (in socks5_connect() at socks5.c:202)

falló: Fallo irrecuperable en la resolución del nombre.

wget: no se pudo resolver la dirección del equipo “raw.githubusercontent.com”

The error is in spanish. Basically says "connection refused" and that it couldn't resolve the address. The Tails documentation says that everything you download goes through Tor. Is there a way to download the file through a Tor proxy?

**Comment by foundationer** [comment]
Thanks @jakommo, this gets the job done. However, I'm not sure if using the Unsafe Browser goes with the underlying philosophy of going through this whole process. I'll keep the issue open in case somebody has a better solution (if using the Unsafe Browser is the only way, then I'll close it as well).

> You can use the "unsafe browser" to download content from none tor sites. See https://tails.boum.org/contribute/design/Unsafe_Browser/Am

**Comment by foundationer** [comment]
Ok, that's a simple way to do it. Thanks, I'm closing the issue.
