### ISSUE TITLE
Question about keys expiration

### ISSUE THREAD

**Issue by foundationer** [drduh/YubiKey-Guide#193]
Hi

I noticed you set the expiration of the subkeys to one year. My question is: what happens after that? Will I be able to upload a new set of subkeys to the Yubikey? If that's the case, how many times can I repeat the process until it runs out of space?

Notice that I'm far from being an expert on encryption keys, so I may be unaware of things relevant to this question.

**Comment by exussum12** [comment]
The yubikey can only hold one set at a time. Should be able to update as many times as needed. I've not hit a limit

**Comment by foundationer** [comment]
Great, thanks @exussum12.
