### ISSUE TITLE
Add keys.openpgp.org to the keyservers

### ISSUE THREAD

**Issue by dominickpastore** [drduh/YubiKey-Guide#194]
The "Export Public Keys" section has a few sample commands to upload keys to keyservers. The new keyserver, keys.openpgp.org, was [launched roughly a year ago](https://keys.openpgp.org/about/news#2019-06-12-launch) and [has quickly been adopted](https://keys.openpgp.org/about/news#2019-09-12-three-months-later) by several projects. It might be a good idea to add it to the list:

```
gpg --keyserver hkps://keys.openpgp.org --send-key $KEYID
```

**Comment by klausenbusk** [comment]
> `gpg --keyserver hkps://keys.openpgp.org --send-key $KEYID`

For the record: The key isn't searchable before the mail has been verified, more info here: https://keys.openpgp.org/about

**Comment by dominickpastore** [comment]
From @drduh:
> Definitely a good suggestion. Feel free to send a PR or I'll include it in the next major update.

If you don't beat me to it, I will probably send one in the not-too-distant future.

From @klausenbusk:
> For the record: The key isn't searchable before the mail has been verified, more info here: https://keys.openpgp.org/about

That's a good point. There are also some other pretty significant differences from more traditional keyservers (see [FAQ]):

- There is currently no support for third party signatures, inhibiting the web-of-trust. But not for no reason: bad things can happen if anyone can sign a user's key (and thus attach arbitrary data) without their permission.
- Keys cannot be revoked (also not for no reason, see the above FAQ for their explanation). But they can be removed.

I found these differences concerning at first, but after some reading about the things that can go wrong with traditional keyservers, I understand why they are there. In addition to the above FAQ, [this answer on the Information Security Stack Exchange has some links to informative reading.](https://security.stackexchange.com/a/192948)

For that matter, it might be worth considering whether the other more traditional keyservers should still be recommended, or maybe some words of warning or links to further reading should be added, but of course, that is entirely up to @drduh.

[FAQ]: https://keys.openpgp.org/about/faq

**Comment by drduh** [comment]
@dominickpastore having given it some thought, can you hit us with a PR?
