### ISSUE TITLE
pyopenssl 19.1.0 has requirement cryptography>=2.8, but you'll have cryptography 2.6.1 which is incompatible.

### ISSUE THREAD

**Issue by bengim** [drduh/YubiKey-Guide#202]
On Debian 10.5.0, after "sudo apt -y install python-pip python-pyscard" I get "pyopenssl 19.1.0 has requirement cryptography>=2.8, but you'll have cryptography 2.6.1 which is incompatible." (see the attached screen shot)
![Screen1](https://user-images.githubusercontent.com/68807980/90958985-a4dff200-e4a8-11ea-8e6d-edb16dfd5589.png)

Possible solution, I've found might be putting "pip install PyOpenSSL" before "pip install yubikey-manager". Like so:
$ sudo apt -y install python-pip python-pyscard
$ pip install PyOpenSSL
$ pip install yubikey-manager

or (based on dragon788's pulls request about Python2 EOL https://github.com/drduh/YubiKey-Guide/pull/201):
$ sudo apt -y install python3-pip python3-pyscard
$ pip3 install PyOpenSSL
$ pip3 install yubikey-manager

It seems, installing PyOpenSSL explicitly installs also the the right version of cryptography.
See also pull request https://github.com/drduh/YubiKey-Guide/pull/203 for the solution

**Comment by turjoy-real** [comment]
Noice!
