### ISSUE TITLE
rng-tools does not work with "HRNGDEVICE=/dev/ttyACM0" in /etc/default/rng-tools

### ISSUE THREAD

**Issue by bengim** [drduh/YubiKey-Guide#204]
after running 
```
$ echo "HRNGDEVICE=/dev/ttyACM0" | sudo tee /etc/default/rng-tools
```
restarting rng-tools in the following line doesn't work (Debian 10.5):
```
$ sudo service rng-tools restart
```
It gives the following output:
```
Job for rng-tools.service failed because the control process exited with error code.
See "systemctl status rng-tools.service" and "journalctl -xe" for details.
```

Running "systemctl status rng-tools.service" with sudo:
```
$ sudo systemctl status rng-tools.service
● rng-tools.service
   Loaded: loaded (/etc/init.d/rng-tools; generated)
   Active: failed (Result: exit-code) since Sun 2020-08-23 13:26:21 +04; 12s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4217 ExecStart=/etc/init.d/rng-tools start (code=exited, status=1/FAILURE)

Aug 23 13:26:21 myhome-pc systemd[1]: Starting rng-tools.service...
Aug 23 13:26:21 myhome-pc rng-tools[4217]: Starting Hardware RNG entropy gatherer daemon: (Hardware RNG device inode not found)
Aug 23 13:26:21 myhome-pc rng-tools[4217]: /etc/init.d/rng-tools: Cannot find a hardware RNG device to use.
Aug 23 13:26:21 myhome-pc systemd[1]: rng-tools.service: Control process exited, code=exited, status=1/FAILURE
Aug 23 13:26:21 myhome-pc systemd[1]: rng-tools.service: Failed with result 'exit-code'.
Aug 23 13:26:21 myhome-pc systemd[1]: Failed to start rng-tools.service.
```

If I change "/dev/ttyACM0" to "/dev/urandom", it works. Does putting /dev/urandom instead of /dev/ttyACM0 make any sense? I mean, changing the above mentioned line to this:
```
$ echo "HRNGDEVICE=/dev/urandom" | sudo tee /etc/default/rng-tools
```

**Comment by dragon788** [comment]
Using `/dev/urandom` doesn't make sense in this context as that is using a kernel device (software) not the HRNG ( *hardware* random number generator) you presumably wanted to use if you are following the OneRNG directions.

What hardware RNG device are you using, a OneRNG or WhiteNoise or something else?

I recently discovered while looking through some documentation on my Nitrokey that there is a way to use a smartcard (like a Yubikey or Nitrokey) as a hardware RNG rather than requiring a separate device which is probably the situation that most folks are in unless they are truly paranoid and have invested in a separate HRNG.

**Comment by bengim** [comment]
>>there is a way to use a smartcard (like a Yubikey or Nitrokey) as a hardware RNG

A-Ha! Thanks. So it is possible to use Yubikey as a HRNG. 
So according to this
```
echo "HRNGDEVICE=/dev/ttyACM0" | sudo tee /etc/default/rng-tools
```
it turns out the README.md, we are currently discussing, assumes, that we use the yubikey itself as hardware RNG. And  "/dev/ttyACM0" in the README.md refers to my yubikey plugged into usb port. Am I right? 
If so, then something doesn't allow the rng-tools to get access to the yubikey. May be my yubikey should be somehow preconfigured/prepared to serve as a HRNG?

**Comment by dragon788** [comment]
The README here does not assume you are using the Yubikey, it specifically mentions using a separate hardware device, but should maybe be made more explicit about the options.

https://github.com/drduh/YubiKey-Guide#entropy

If you want to know more about the differences between sources of randomness the ArchLinux Wiki has a pretty good intro, https://wiki.archlinux.org/index.php/Random_number_generation#Kernel_built-in_RNG


I'm working on making a write-up on using the `scdrand` tool I found to have an alternate source of entropy that CAN use the Yubikey, but as is usual I have a lot of irons in the fire.

To quickly grab and install scdrand you can follow the directions here (Debian/Ubuntu oriented for now) or even more quickly use my Gist that utilizes Docker.
https://git.incenp.org/damien/scdtools/issues/2

https://gist.github.com/dragon788/54eb8592136192787e6f997e1ed0917a

The Nitrokey mention with a link to the software is here:
https://www.nitrokey.com/documentation/applications#p:nitrokey-pro&os:linux&a:true-random-number-generator-trng

**Comment by bengim** [comment]
>The README here does not assume you are using the Yubikey, it specifically mentions using a separate hardware device, but should maybe be made more explicit about the options.

Oops. Sorry. My bad. I totally missed the "A hardware random number generator like OneRNG will increase the speed of entropy generation and possibly the quality" part. Thank you!

Thanks for the other links and resources, too.

**Comment by dragon788** [comment]
I also updated the README for more clarity around that in #201 and reverted the OneRNG specific package changes that didn't work.

**Comment by bengim** [comment]
Thank you!
