### ISSUE TITLE
Export Random Passphrase to Secure Backup

### ISSUE THREAD

**Issue by borgmanJeremy** [drduh/YubiKey-Guide#206]
Hello,

I followed the directions on this guide but then I wanted to create a second yubikey with the same keys.I mounted the encrypted USB Drive, copied the keys to a tempfs, then I went to import the keys to a second Yubikey. 

At that point I realized per the instructions I created a random passphrase and then did not think to export this passphrase to the USB stick. At this point I think I'll need to wipe both yubikeys and create new keys.

I recommend adding a step to export the random passphrase to the secure USB drive.

**Comment by drduh** [comment]
I wouldn't recommend storing the PGP key credential on the same USB drive, because storing them separately adds an additional layer of defense. We can certainly make a note about saving the PGP key password appear more prominent, however.
