### ISSUE TITLE
/tmp not necessarily a ramdisk, data potentially saved onto non-volatile storage

### ISSUE THREAD

**Issue by mirko** [drduh/YubiKey-Guide#210]
Reading
> Create a temporary directory which will be cleared on reboot and set it as the GnuPG directory:
> $ export GNUPGHOME=$(mktemp -d)

I had to double-check. And indeed /tmp/ - where mktemp creates temporary directories by default - is not a ramdisk - at least not on Debian.
Yes, it's getting cleared on reboot, however it was once written to persistent storage, meaning the storage device (thumb drive, spinning disk, memory card, you name it..) once had this data being saved on.

I think this needs to be stated and/or the guide should include a setup for creating a ramdisk, e.g. via `mount -t tmpfs -o size=128M myramdisk /tmp/ramdisk` and `mktemp` being invoked with `-p /tmp/ramdisk`.

**Comment by mirko** [comment]
Happy to create a PR if agreed

**Comment by drduh** [comment]
Great idea - please send the PR!

**Comment by drduh** [comment]
Great idea - please send the PR!

**Comment by mjbnz** [comment]
I'd suggest checking for the existence of `/run/user/$(id -u)`, and set that as `$TMPDIR` for `mktemp` to use.

**Comment by mirko** [comment]
> I'd suggest checking for the existence of `/run/user/$(id -u)`, and set that as `$TMPDIR` for `mktemp` to use.

I lost track of what's standard and/or how distributions do it differently.
If you say `/run/user/$(id -u)` always exists and is always a ramdisk and us independant from systemd being used or not, I'm good and happy with using this one.

**Comment by dragon788** [comment]
I don't think `/run/user/$(id -u)` is guaranteed to be a `tmpfs` mount, and it tends to only exist on systems using `systemd` "user slices" in my experience, which is a lot of distributions but not all of them.

Making a custom `tmpfs` mount is probably the best way to ensure that you are operating in a ramdisk only.

**Comment by drduh** [comment]
If there's a better, yet compatible, way to do temporary files, let's document it in a PR.
