### ISSUE TITLE
Additions to "Required Software"

### ISSUE THREAD

**Issue by berwag** [drduh/YubiKey-Guide#215]
Many Thanks for the "YubiKey-Guide", which helped me much configuring my new YubiKey.

Regarding "Required Software" for Ubuntu/Debian: In addition to the packages indicated in the text, I needed libssl-dev, swig and libpcsclite-dev (Ubuntu 18.04 on i386). Perhaps it may be helpful to add this to the apt install-statement.

**Comment by drduh** [comment]
Could you send a PR to include those packages for that specific version of Ubuntu, please?

**Comment by yubischiess** [comment]
Had the same issues during this section:

`$ pip3 install yubikey-manager`

Got the error:
```
unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyscard
```

After running:
`$ sudo apt -y install libssl-dev swig libpcsclite-dev`

...the errors were resolved!

Was running on:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

**Comment by berwag** [comment]
I have sent Pull Request #243 with the change.
This is my first "PR" so I hope it is ok.
