### ISSUE TITLE
Change PUK during initial setup.

### ISSUE THREAD

**Issue by captn3m0** [drduh/YubiKey-Guide#220]
The current version leaves the PUK with its default value - `12345678`.

Perhaps it could be recommended to be set to the same value as the PIN, similar to how `yubikey-agent` does it? 

https://github.com/FiloSottile/yubikey-agent

**Comment by Wheest** [comment]
Good point, this could be a security issue if the key falls into the hands of an adversary, since they would know the admin pin.

You could do a PR for say the [Change-Pin](https://github.com/drduh/YubiKey-Guide#change-pin) section?
