### ISSUE TITLE
keep-display in gpg-agent.conf

### ISSUE THREAD

**Issue by lukipuki** [drduh/YubiKey-Guide#223]
Thanks for a great tutorial! I have a comment that might help someone and should perhaps be added to the tutorial.

- I use FIDO2 functionality on the YubiKey for SSH, not PGP
- I also use PGP on remote servers

I've set up SSH forwarding and GPG agent forwarding for YubiKey but GPG got stuck on the remote machine once it needed a PIN. There was no popup on my local machine for the PIN. After some googling, I found [this post by a Gentoo developer](https://flameeyes.blog/2016/10/15/gnupg-agent-forwarding-with-openpgp-cards/) who recommends adding `keep-display` to the local `gpg-agent.conf`. This fixed my issue and now a pinentry popup window appears every time a PIN is required remotely.

**Comment by drduh** [comment]
This would probably be better suited in the agent forwarding or troubleshooting sections. @lukipuki could you send a PR for the same?

**Comment by drduh** [comment]
Please send a PR if you'd like to see this in the guide.
