### ISSUE TITLE
A better FAQ section about pinentry

### ISSUE THREAD

**Issue by jethrosun** [drduh/YubiKey-Guide#227]
Hi, 

I just follow the guide and set up my yubi keys. Thank you very much.

While setting up mine, I noticed that configuring pinentry is pretty tricky. For example, in my linux box, if I don't set up the GPG_TTY i can't see the notification for entering passphrase, while this won't be a problem in mac because there is  GUI. I am now using pinentry-rofi because I am also using rofi. 

I think it might be helpful if we can have a small section describing this issue and the options we have in the gpg conf. 

Best,

**Comment by drduh** [comment]
Resolving since adding this to https://github.com/drduh/config/blob/master/gpg-agent.conf#L4
