### ISSUE TITLE
simplified gpg.conf default preferences

### ISSUE THREAD

**Issue by basbebe** [drduh/YubiKey-Guide#228]
As far as my understanding goes, `default-preference-list` is a concatenation of `personal-cipher-preferences` and `personal-compress-preferences`.

So the current part of `gpg.conf`
```
personal-cipher-preferences AES256 AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256
personal-compress-preferences ZLIB BZIP2 ZIP Uncompressed
default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
cert-digest-algo SHA512
```

could be simplified to
```
personal-digest-preferences SHA512 SHA384 SHA256
default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
cert-digest-algo SHA512
```

[or replaced by](https://bettercrypto.org/#pretty_good_privacy)
```
personal-digest-preferences SHA512
cert-digest-algo SHA512
default-preference-list AES256 CAMELLIA256 AES192 CAMELLIA192 AES CAMELLIA128 TWOFISH SHA512 SHA384 SHA256 BZIP2 ZLIB ZIP
```

see
- https://bettercrypto.org/#pretty_good_privacy

**Comment by drduh** [comment]
It probably could be simplified. I would rather wait until there's a problem with the existing configuration before changing it though.
