### ISSUE TITLE
Off-device subkey

### ISSUE THREAD

**Issue by Wheest** [drduh/YubiKey-Guide#230]
I'm wondering what the right workflow for this use-case would be:

- I want to sign git commits while working on a remote machine
- I can only access the remote machine by hopping via an untrusted gateway server
- setting up agent forwarding is complicated, and (perhaps) dangerous given the gateway server in the middle

Thus, I was thinking of creating a GPG subkey from my master just for signing these git commits, storing a password protected version of the private key on the remote machine.  If it is compromised, I can revoke the subkey.

1.  is this the right approach, or is there a way I can conveniently do agent forwarding to this machine, while avoiding exposing my agent to the gateway server?
2.  if this is the best approach, how can I create a subkey that has its private key outside of the Yubikey, signed by my master key

**Comment by drduh** [comment]
You're aware of the agent forwarding risk, so I don't have much to add, except maybe this is possible with SSH tunneling? I would find a way to get untrusted data to the trusted host with YubiKey signing capability to pull this off, then pass the signed message back.
