### ISSUE TITLE
Same GPG keys in two yubikeys, but gpg always asks for first

### ISSUE THREAD

**Issue by fjhheras** [drduh/YubiKey-Guide#233]
Thank you for the guide. I have followed it and now I have two yubikeys with the same set of 3 gpg keys. I am successfully using one of the yubikeys to sign, encrypt, etc. However, I do not seem to find a way to use the second yubikey, as gpg always asks for the first device (by serial number) when using any of the keys. 

I have realised that when I do `gpg --card-status` with the **second** yubikey inserted, the card-no under each key in General key info is the serial number of the **first** yubikey. I guess I messed up somewhere..

**Comment by jakommo** [comment]
I think what you are looking for is described in this section https://github.com/drduh/YubiKey-Guide#using-multiple-keys

**Comment by fjhheras** [comment]
Ups, shame on me that I did not see that after skimming several times through the text...

I can confirm that `gpg-connect-agent "scd serialno" "learn --force" /bye` works. To work on SSH (for example, for github) seems to require something else, but if I reboot it seems to work.
