### ISSUE TITLE
GPG with Root 

### ISSUE THREAD

**Issue by Lsh0x** [drduh/YubiKey-Guide#235]
Hi guys ! 

I'm trying to setup the opening of my luks rootfs using the smardcard with GPG . 
Basically i encrypted with gpg the luks key and i'm now trying to decrypt it with my root user.
From my user i have no issue the decryption work fine, but with root don't know why it doesn't work. 

I first try to copied the gnupg directory from my user to root.
Then try to import the key and trust it with the root user.
And finally set the `GNUPGHOME` to the user one. 

I use `pkill -f gpg` to kill the gpg-agent and all.
I also try `gpg-connect-agent "scd serialno" "learn --force" /bye`

BUT everytime the same result : 
```
gpg-connect-agent "scd serialno" "learn --force" /bye
```

Is anyone already did that? Any advices?

**Comment by Lsh0x** [comment]
Happy new year btw ! :partying_face:

**Comment by jrathert** [comment]
Your question is hard to understand as you apparently did not copy in the result/error message, but the gpg-connect-agent command a second time.

Just guessing: You have just opened a new terminal in a graphical UI and switched to the root account using su -  or sudo -i or similar. Then, gpg-agent cannot ask for your passphrase (as it does not have access to the graphical environment). You need to either login into the graphical environment as root (???) or use a true separate command-line (Strg+Alt+F3, tty3). Just google for gpg-agent and tty to find out about the problem (and potential solutions). If my guess was wrong, then again: A bit more info on the problem would be helpful.

**Comment by drduh** [comment]
Thanks @jrathert

**Comment by johnalotoski** [comment]
FYI for others who may find this GH ticket while trying to resolve a similar issue, also see:
https://wiki.archlinux.org/title/GnuPG#su
