### ISSUE TITLE
throw-keyids in /gnupg/gpg.conf will break Password Manager with Openkeychain on Android

### ISSUE THREAD

**Issue by alci63** [drduh/YubiKey-Guide#245]
Hi, and thanks for this guide.

One thing to notice is that throw-keyids in gpg.conf will prevent Openkeychain to decrypt the passwords in password store on Android.
If you use pass on Linux, throw-keyids won't hurt, and gpg will happily decrypt the passwords, and ask for the yubikey when needed. But if you push the passwords to a git repository, and then pull them in Password store on Android, Openkeychain won't be able to make the link with your key on the Yubikey.

See https://github.com/android-password-store/Android-Password-Store/issues/173 and especially this comment https://github.com/android-password-store/Android-Password-Store/issues/173#issuecomment-453686599

Maybe the implications and potential drawbacks of using throw-keyids should be more emphasised...

**Comment by vorburger** [comment]
@alci63 did you see the previous issue #152 about this problem?

**Comment by alci63** [comment]
Sorry for the duplicate... Issue #152 is indeed similar. Thanks for pointing it out.
