### ISSUE TITLE
Github now supports security keys for Github Operations

### ISSUE THREAD

**Issue by gijswijs** [drduh/YubiKey-Guide#260]
I just read this blog post on the Github Engineering blog: <https://github.blog/2021-05-10-security-keys-supported-ssh-git-operations/>

I'm not sure whether it has direct impact in this guide, but it might have.

**Comment by michael-k** [comment]
> While it has long been possible to use the YubiKey for SSH via the OpenPGP or PIV features, the direct support in SSH is easier to set up, more portable, and works with any U2F or FIDO2 security key – even older ones like the FIDO U2F Security Key by Yubico.

https://www.yubico.com/blog/github-now-supports-ssh-security-keys/

As far as I can tell, this guide only covers the OpenPGP approach and could benefit from mentioning the direct support in SSH.

**Comment by crash5** [comment]
relevant PR: #258

**Comment by drduh** [comment]
https://github.com/drduh/YubiKey-Guide/pull/258 merged with link; more documentation about the new method is welcome.
