### ISSUE TITLE
weasel-pageant EOL

### ISSUE THREAD

**Issue by MTRNord** [drduh/YubiKey-Guide#261]
According to https://github.com/vuori/weasel-pageant it is not maintained anymore. Is there any guide how to use any of the mentioned alternatives?

**Comment by metcalfc** [comment]
I found something better. https://github.com/rupor-github/win-gpg-agent

I got it working with GPG4Win (because standard gnupg doesn't seem to work for me with yubikey). I followed the README plus made two changes. 

https://github.com/rupor-github/win-gpg-agent/issues/15

**Comment by drduh** [comment]
Would someone like to update the guide if you've got a working alternative?

**Comment by etd21** [comment]
is there someone i can hop on a microsoft team/discord to help me step by step, i can't solve this ssh authentication from windows command prompt to servers

**Comment by drduh** [comment]
Resolving to inactivity. Windows users, please send PRs.
