### ISSUE TITLE
Paper key might still be passphrase-protected

### ISSUE THREAD

**Issue by mpdude** [drduh/YubiKey-Guide#263]
First, thank you @drduh for your work maintaing this documentation! It's a great writeup of a topic that is daunting to newcomers, and it made my life a lot easier 💚 .

I know how important it is to keep good backups of keys and to make sure you can revoke them at a later time. A 1024 bit RSA key of mine is still on the keyservers, and since it has no expiration date and I lost the key two decades ago, there is no way to revoke it.

So, maybe you'd like to add a tip from the [Kernel Maintainer PGP Guide](https://www.kernel.org/doc/html/latest/process/maintainer-pgp-guide.html#back-up-your-master-key-for-disaster-recovery)  somewhere near the section where you recommend creating a paper key backup: They say that a `paperkey` backup is still protected by the passphrase. So, it might be valuable to write your passphrase on the paper (sic!) to make sure you still have it once the printout becomes useful.

**Comment by drduh** [comment]
@mpdude Thanks for pointing that out. May I ask you to send a PR to add this note to the relevant section?
