### ISSUE TITLE
Extra encryption key generated

### ISSUE THREAD

**Issue by stuaxo** [drduh/YubiKey-Guide#27]
When I generated the master key, an extra encryption key was generated, offsetting all the key numbers near the end by 1.

**Comment by drduh** [comment]
Please reopen with your version of GnuPG if you see it again.

**Comment by stuaxo** [comment]
I've given up using the yubikey for now, it's a massive hassle to setup and I never worked out if I'm supposed to just throw away my pre-gpg keys.

I might give this another go when I move computers in the new year.
