### ISSUE TITLE
Does PUK security note apply given guide references OpenPGP applet vs PIV applet?

### ISSUE THREAD

**Issue by sunknudsen** [drduh/YubiKey-Guide#271]
> Security Note: If you followed this guide before Jan 2021, your PUK (Pin Unblock Key) may be set to its default value of 12345678. An attacker can use this to reset your PIN and use your Yubikey. Please see the Change PUK section for details on how to change your PUK.

From YubiKey [docs](https://support.yubico.com/hc/en-us/articles/360013779219-Smart-Card-PIN-Unlock-Reset-Operational-Approaches), it appears PUK is part of [PIV applet](https://www.yubico.com/authentication-standards/smart-card/).

**Comment by AlekSi** [comment]
I came here to ask the same question. There is no PUK OpenPGP Card spec.

**Comment by AlekSi** [comment]
See also #248

**Comment by sunknudsen** [comment]
Here is Yubico’s answer:

> Hello Sun, 
> 
> Thank you for contacting Yubico support. 
> 
> It looks like that guide conflated the PIV functions with the GPG functions.
> 
> The PUK is just for the PIV functionality. On OpenPGP, the admin PIN (or a reset code, if one is set) can be used to reset the OpenPGP PIN. The PUK command listed is just for the PIV Smart card PIN, and does not reset the OpenPGP PIN.
> Sincerely,
> 
> Jane Doe* | Customer Support Specialist at Yubico

*I obfuscated customer support specialist name for privacy reasons.

**Comment by AlekSi** [comment]
Maybe we can close this one and go to #248?
