### ISSUE TITLE
Yubikey secure copy (scp) on ssh - Possible? No instructions

### ISSUE THREAD

**Issue by Danrancan** [drduh/YubiKey-Guide#272]
There is no mention of how to use the secure copy command when using the yubikey for your ssh connection. The notmal scp command will not work with a yubikey. Is it possible to use scp while using a yubikey to ssh into a remote machine or server?

**Comment by Danrancan** [comment]
Anyone have some input on this?

**Comment by donnex** [comment]
Can you describe what's not working? I've used my YubiKey for a long time now, following this guide, and I've never had any issues with `scp`. As far as I know it's authenticating the same way as a normal SSH connection does.

Log output and a proper description of your conf/setup is probably required if you want any additional help with troubleshooting.

**Comment by drduh** [comment]
@Danrancan it should just work as @donnex said. Look into [SSH multiplexing](https://github.com/drduh/config/blob/master/ssh_config#L23-L25) if you're being overly prompted for key presses to authenticate.

**Comment by Danrancan** [comment]
Well I should have read the scp man pages before posting here. As it turns out, I just didn't fully understand the scp command. As of now, I did get scp to properly work with the yubikey. Sorry for the miscommunicatino and inconvenience. Thanks for the help!

**Comment by Danrancan** [comment]
For anyone having difficulties with the scp command using yubikey, here is the proper syntax I used to copy a file from a local machine to a remote server:

SYNTAX:
`scp -i ~/.ssh/id_rsa_yubikey.pub -P 22 local_file_to_be_transferred.txt remote_username@local_server_ip_address:/remote/directory_of_server`

where -i = your yubikey identities file, -P = your ssh port, remote_username = your username that you use to log in to your server

In my case:
`scp -i ~/.ssh/id_rsa_yubikey.pub -P 40001 /Users/Danrancan/Downloads/myfile.zip boopi@192.168.1.2:/home/Danrancan`
