### ISSUE TITLE
Disable yubikey after setting up on a machine

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [drduh/YubiKey-Guide#280]
I setup yubikey on a machine with "keytocard" command for the key. But later I would like to disable yubikey on this machine but use my keys the standard way (inputting password each time). What should I be doing?

I have tried to delete the keys on my machine using Kgpg, and restored them with a backup. However I find that each time I tried to authorize or decrypt, it still asked me to input yubikey pin instead.

I guess that something in the .gnupg folder still telling the machine to use yubikey even if the keys are deleted and restored manually.

Hence the question, how to disable yubikey on a machine after setup?

**Comment by pol009900** [comment]
0

**Comment by pol009900** [comment]
0

**Comment by pol009900** [comment]
0

**Comment by iandstanley** [comment]
Was the backup made before or after using 'keytocard'?

If after, then GPG removes the actual key and replaces it with a 'stub' pointing to the Yubikey. This would explain GPG prompting you. 

If if backup was made before then you must remove the old private key before restoring the backup - otherwise the import will be ignored.

**Comment by GreatBigWhiteWorld** [comment]
> Was the backup made before or after using 'keytocard'?
> 
> If after, then GPG removes the actual key and replaces it with a 'stub' pointing to the Yubikey. This would explain GPG prompting you.
> 
> If if backup was made before then you must remove the old private key before restoring the backup - otherwise the import will be ignored.

When I say 'backup' I meant that I exported private key to a file **before** 'keytocard' command. Maybe you don't call that a backup but 'copying the .gpg folder'?
I later solved this by copying the whole .gpg folder from another computer that's using standard password authentication. Can you  tell me what is the 'stub' that's pointing to the yubikey? So next time I'll can try just delete the stub if I failed to backup the whole .gpg folder.

**Comment by xorcare** [comment]
When gpg detects the keys on the smart card (in this case yubikey) it creates special files in the directory `$HOME/ .gnupg/private-keys-v1.d/` to understand where to get the key from in the future. In order for gpg to stop requesting a smart card, delete one or more files in this directory.

@GreatBigWhiteWorld

**Comment by drduh** [comment]
Closing to inactivity, please reopen if there's additional stuff to discuss.
