### ISSUE TITLE
Change PUK link in top part of page is a broken link. Leads to nothing.

### ISSUE THREAD

**Issue by Danrancan** [drduh/YubiKey-Guide#287]
An attacker can use this to reset your PIN and use your Yubikey. Please see the Change PUK section for details on how to change your PUK.

In this sentance, the [Change PUK](https://github.com/drduh/YubiKey-Guide#change-puk) link is broken and directs you to nothing. Please fix.

**Comment by pedrohdz** [comment]
I’ll try and take a look this week.  Thanks!

**Comment by pedrohdz** [comment]
Fix is in: https://github.com/drduh/YubiKey-Guide/pull/295

**Comment by drduh** [comment]
Much appreciated!
