### ISSUE TITLE
gpg2 for Yubikey 4

### ISSUE THREAD

**Issue by paulbovbel** [drduh/YubiKey-Guide#29]
Great guide, but I found that I was unable to sign git commits using the signing key unless I repeated all these steps using gpg2 (and set gpg2 as the default program in .gitconfig), as recommended by the official docs (https://www.yubico.com/support/knowledge-base/categories/articles/use-yubikey-openpgp/).

**Comment by drduh** [comment]
Let me know what error the failed signing operation gave, and I'll add it to Troubleshooting. `gpg: decryption failed: secret key not available` is already there advising of the same.
