### ISSUE TITLE
SSH - git : from "UNPROTECTED PRIVATE KEY FILE!" to "invalid format"

### ISSUE THREAD

**Issue by RupertEverton** [drduh/YubiKey-Guide#298]
I carefully followed the guide to generate PGP keys, and then moved onto SSH. Specifically, I'm doing the following:

1. `$ wget -O ~/.gnupg/gpg-agent.conf https://raw.githubusercontent.com/drduh/config/master/gpg-agent.conf`
2. Following the tip, I added `pinentry-program /usr/bin/pinentry-gnome3` and commented `#pinentry-program /usr/bin/pinentry-curses`.
3. `$ gpg-connect-agent /bye`
4. `$ export GPG_TTY="$(tty)"`
5. `$ export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)`
6. `$ gpgconf --launch gpg-agent`
7. `$ ssh-add -L`
8. `$ ssh-add -L | grep "cardno:$CARDNO" > ~/.ssh/id_ed25519_yubikey.pub`
9. `$ cat << EOF >> ~/.ssh/config`
```
Host github.com
    IdentitiesOnly yes
    IdentityFile ~/.ssh/id_ed25519_yubikey.pub
EOF
```
10. `$ ssh git@github.com -vvv`

At this point I see, among other things, `debug1: Authentication succeeded (publickey).` and `Hi ***! You've successfully authenticated, but GitHub does not provide shell access.`
So I cd into the repo, but when I `$ git push` the following is shown:

```
WARNING: UNPROTECTED PRIVATE KEY FILE!
Permissions 0664 for '/home/user/.ssh/id_ed25519_yubikey.pub' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/home/user/.ssh/id_ed25519_yubikey.pub": bad permissions
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have tried changing the permissions with `chmod` as proposed [here](https://stackoverflow.com/a/217729) and [here](https://stackoverflow.com/a/25681412) and by doing that I get a different message:

```
Load key "/home/user/.ssh/id_ed25519_yubikey.pub": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

I've ran out of ideas, looking forward to your expertise.

Thank you.

**Comment by maxkratz** [comment]
(Just a side note about the last part: SSH usually expects a *private* keyfile in `~./ssh/id_rsa_blabla` [without the `.pub` at the end]. This is why you get `Load key "/home/user/.ssh/id_ed25519_yubikey.pub": invalid format`.)

**Comment by drduh** [comment]
@RupertEverton are you still having trouble? If so, let us know and we can try to help you out.

**Comment by hertg** [comment]
I had this problem too, turned out my Yubikey wasn't properly plugged in. Re-plugging it and restarting the gpg-agent with `gpg-connect-agent updatestartuptty /bye` solved my issue. If you have this issue too, check the following:
- Is the hardware key plugged in properly
- Does the USB port work
- Do the USB-Adapters work (if you use any)
- Does the hardware key itself still work

---

I only figured this out after running `gpg --card-status` and getting this output.
```
gpg: selecting card failed: No such device
gpg: OpenPGP card not available: No such device
```
