### ISSUE TITLE
Is it possible to use it for both GPG and SSH with a specific SSH key?

### ISSUE THREAD

**Issue by delucca** [drduh/YubiKey-Guide#299]
Hi (:

First, thanks for the amazing tutorial!

I know that this guide explain how to use SSH based on the GPG key we created. My question is, how can I use a **specific** SSH key (without using the GPG as SSH, like we're doing in the guide). Is that possible?

I've just found out [this tool](https://github.com/FiloSottile/yubikey-agent) and I was able to generate a custom SSH key, import it to Yubikey and use it as my SSH key. But, for some reason, it seems that the GPG is somehow "competing" with the SSH agent.

[I've explained it in more detail here](https://github.com/FiloSottile/yubikey-agent/issues/111), but what is happening is the following: if I plug my Yubikey, I can either use the GPG key or the SSH key, but never both. For example, assume that I want to run the following commands:
1. `git commit ...`
2. `git push`

The first one would use my GPG key to sign the commit. The second one would use the SSH key to send it to the server.

For some reason, I can run the `git commit` command and sign it with GPG, but as soon as I do so, I can't use the SSH anymore. I need to **physically** remove the Yubikey, them insert it again to use the SSH key. After doing so, I can use the SSH normally and multiple times, but as soon as I try to use the GPG key I got an error (like if the GPG key doesn't exist) and I need to remove and reinsert the Yubikey again.

Any ideas why this is happening?

**Comment by dabo-devconsole** [comment]
Hi delucca,

maybe the problem is already explained at the [yubikey-agent site](https://github.com/FiloSottile/yubikey-agent#conflicts-with-gpg-agent-and-yubikey-manager). Is it working, when you try to send a `killall -HUP yubikey-agent` between the two commands?

**Comment by delucca** [comment]
> Hi delucca,
> 
> maybe the problem is already explained at the [yubikey-agent site](https://github.com/FiloSottile/yubikey-agent#conflicts-with-gpg-agent-and-yubikey-manager). Is it working, when you try to send a `killall -HUP yubikey-agent` between the two commands?

Thanks!

I completely missed that part. In any case, now I can run a command to release yubikey-agent lock. But, what should I do in the opposite direction? I mean, after using Yubikey OpenPGP module, yubikey-agent can't acquire the lock, so it can't be used too.

Are there any similar command available?

**Comment by delucca** [comment]
@dabo-devconsole it seems that running `sudo systemctl restart pcscd.service` solved the issue on both ends.

Do you know if it is possible to hook this command to be executed right after (or before) using both the GPG and SSH keys? That would solve the issue for me =)

**Comment by dabo-devconsole** [comment]
@delucca, I didn't tested it, but is this what [githooks](https://git-scm.com/docs/githooks) are maybe also useful for? So you need to place an executable script for restarting/(maybe reloading works too) pcscd which is linked to pre-push and/or pre-commit/post-commit hookdir?

**Comment by delucca** [comment]
> @delucca, I didn't tested it, but is this what [githooks](https://git-scm.com/docs/githooks) are maybe also useful for? So you need to place an executable script for restarting/(maybe reloading works too) pcscd which is linked to pre-push and/or pre-commit/post-commit hookdir? But eventually there will be a timing issue for recognizing the yubikey again.

Hmmm

That is a pretty interesting idea! Since git is what I use the most, that would probably solve the issue! It isn't a big deal to restart pcscd (I've already created an alias for it) when I need to encrypt something, or even SSH in a server. The major issue is having to do it on EVERY commit haha

I'm going to give it a try. Thanks!

Closing this for now.
