### ISSUE TITLE
Paper backup instructions and pitfalls

### ISSUE THREAD

**Issue by VFS** [drduh/YubiKey-Guide#3]
@drduh, would you mind including instructions on best practices to perform a secure backup of the master key on paper? Would be wise to also store a copy of the subkeys (S E A) stored on the yubikey? How hard would it be to password-protect them with a different password?

**Comment by drduh** [comment]
Is that a good idea? How would one read/enter a long private key back from paper? I'm not sure what advantage this would have over storing copies on encrypted, offline media. It ought to be possible to use different passphrases for each key, though it seems overkill.

**Comment by thegroke** [comment]
I think convenience is a non-issue for paper backups. It's just a case of having the master key on a medium that can't have a mechanical or electronic failure (not that paper is itself indestructible!).

http://www.jabberwocky.com/software/paperkey/ makes a good case.
