### ISSUE TITLE
Oops: You're not authorized to access this page

### ISSUE THREAD

**Issue by peterbabic** [drduh/YubiKey-Guide#302]
The **non-exportable** link does not guide me to anything meaningful, even for registered and logged in user:

> Keys stored on YubiKey are [non-exportable](https://support.yubico.com/support/solutions/articles/15000010242-can-i-duplicate-or-back-up-a-yubikey-) (as opposed to file-based keys that are stored on disk) and are convenient for everyday use. Instead of having to remember and enter passphrases to unlock SSH/GPG keys, YubiKey needs only a physical touch after being unlocked with a PIN. All signing and encryption operations happen on the card, rather than in OS memory. [[source](https://github.com/drduh/YubiKey-Guide/blob/fe6434577bce964aefd33d5e085d6ac0008e17ce/README.md?plain=1#L3)]

![image](https://user-images.githubusercontent.com/3952052/147649042-bf595d8d-fcec-4d6a-bf81-00e6738b6c8c.png)

It is still available in the [web archive](http://web.archive.org/web/20201125172759/https://support.yubico.com/hc/en-us/articles/360016614880-Can-I-Duplicate-or-Back-Up-a-YubiKey-):

> For security, the firmware on the YubiKey does not allow for secrets to be read from the device after they have been written to the device. Therefore you cannot duplicate or back up a YubiKey or Security Key. For this reason, we recommend having a backup device and registering both with your accounts so that if one is lost or broken you can use the other to log in.
>
> The only exceptions to this are the few features on the YubiKey where if you backup the secret (or QR code) at the time of programming, you can later program the same secret onto a second YubiKey and it will work identically as the first. These features are listed below.
>
>- Static Password
>- HMAC-SHA1 Challenge-Response
>- OATH-TOTP (Yubico Authenticator)
>
> **Note:** When the Yubico PAM module is used in challenge-response mode (this is the way the Mac Logon Tool works), it uses the device serial to lookup the expected response, which prevents the module from working unless each YubiKey is registered ahead of time. Backing up the HMAC-SHA1 secret and restoring to a different YubiKey later does not work for this scenario as it will have a different serial. 

Suggestions?

**Comment by drduh** [comment]
Let's link to the archived page. Please send a PR or I can do it.

**Comment by peterbabic** [comment]
Here it is https://github.com/drduh/YubiKey-Guide/pull/315

I wonder why was the original article removed though.
