### ISSUE TITLE
Set forcesig when using YubiKey as SmartCard

### ISSUE THREAD

**Issue by codemonkee** [drduh/YubiKey-Guide#304]
A potential configuration to the YubiKey when using it as a SmartCard mentioned in https://github.com/drduh/YubiKey-Guide#create-configuration

> Important The cache-ttl options do NOT apply when using a YubiKey as a smartcard as the PIN is cached by the smartcard itself. Therefore, in order to clear the PIN from cache (smartcard equivalent to default-cache-ttl and max-cache-ttl), you need to unplug the YubiKey.

You can set the `forcesig` flag when editing the card if you want to be prompted for the PIN each time.

```
gpg --edit-card
admin
forcesig
```

**Comment by drduh** [comment]
That's a great tip - can you send a PR to include it?
