### ISSUE TITLE
KDF option not supported on pass for iOS or android Password Store

### ISSUE THREAD

**Issue by john-aperture** [drduh/YubiKey-Guide#307]
Pretty much summarizes it. Using a yubikey with KDF on these apps always results in "incorrect PIN" error and decrements the PIN retry counter. Disabling KDF allows PIN entry to work.

Tested error on both Pass for iOS beta (adding yubikey support) and Password Store for android. Fix tested on pass for iOS only.

Recommend adding a note on the KDF section showing this risk with KDF setups, and the disadvantages of having it off. It is possible for someone to use this guide with NFC Yubikeys, aiming to use PGP on their phones, and not notice the source of the problem.

Can send a pull request with the relevant changes.

**Comment by drduh** [comment]
Thank you for the PR!
