### ISSUE TITLE
Key Overwriting Attacks

### ISSUE THREAD

**Issue by fabiolucidi** [drduh/YubiKey-Guide#322]
Hi,
thank you for your guide, it's very helpful and a great starting point to understand many things around YK, PGP, SSH and - more in general - security.
I think it would be worth **stressing the importance of a safe storage of the backup** (USB device as well as paper backup) and the fact that MasterKey and LUKS passphrases are the only barrier to protect your MK from [Key Overwriting Attacks](https://www.kopenpgp.com/) as well as others. It doesn't change a thing about what to do, just gives more color about why we do it that way (and why not to skip those steps!)

Also, the `--force-aead` option could be used as an interim solution to the KO Attacks (proposed by the authors).

This is just an enhancement proposal.
Thank you,
Fabio

**Comment by drduh** [comment]
Thanks for the tip. Probably less of a concern with backups offline, would you agree? Either way, feel free to send a PR to include it in the guide.

**Comment by fabiolucidi** [comment]
I agree...I'll do it as soon as I can. Thanks
