### ISSUE TITLE
How to retrieve the public key from inside the yubikey?

### ISSUE THREAD

**Issue by lattice0** [drduh/YubiKey-Guide#323]
Suppose I changed computers and lost the public key file. How can I extract it from the yubikey?

**Comment by iandstanley** [comment]
See issue #305 where somebody has cut and pasted the output

**Comment by agent-kimbley** [comment]
Reconfigure you yubikey about the part of GPG, If you do not have any keyserver you was upload and any backup in sotre.

**Comment by drduh** [comment]
Duping to other issue.
