### ISSUE TITLE
WSL2: wsl2-ssh-pageant alternative SSH and GPG agent forwarding

### ISSUE THREAD

**Issue by MacLeodMike** [drduh/YubiKey-Guide#325]
Code: https://github.com/BlackReloaded/wsl2-ssh-pageant
Releases: https://github.com/BlackReloaded/wsl2-ssh-pageant/releases

wsl2-ssh-pageant is a maintained socket forwarding tool similar to wsl-ssh-pageant or weasel-pageant, however it supports both SSH and GPG agent forwarding.

**Comment by drduh** [comment]
Nice - can you a send a PR to include this in the guide? Thanks!
