### ISSUE TITLE
Visual feedback in Windows/Mac when waiting for touch?

### ISSUE THREAD

**Issue by xylo04** [drduh/YubiKey-Guide#326]
I prefer having the [Require Touch](https://github.com/drduh/YubiKey-Guide#require-touch) option enabled, but I would like to have some sort of visual feedback on the screen to remind me when the key is waiting for a touch. Does anyone know if that's supported? Obviously there may be different answers on console vs GUI, but `pinentry` already seems to have that worked out.

Thanks for the guide, it has been immensely helpful in setting up my keys!

**Comment by xylo04** [comment]
Never mind, I should have read all the way to the bottom, I would've seen [maximbaz/yubikey-touch-detector](https://github.com/maximbaz/yubikey-touch-detector). Any similar solutions for Windows or Mac?

**Comment by iandstanley** [comment]
It depends on what software is taking to the Yubikey

You can configure the Yubikey PAM module to prompt on things like a graphical login screen.

**Comment by drduh** [comment]
If anyone is aware for solutions on those platforms, please send PR.
