### ISSUE TITLE
Renewing subkeys fails: Error "make_keysig_packet failed: No secret key"

### ISSUE THREAD

**Issue by psebening** [drduh/YubiKey-Guide#333]
I'm trying to change the expiry date on my expired subkeys according to the guide and it fails with an error.

Let me first introduce the system I'm working on:
macOS 12.4
gpg (GnuPG) 2.3.6
libgcrypt 1.10.1

I use the config from the guide and things were working good in the past (although I do not very often use the PGP keys for encryption/decryption and so maybe this broke way earlier than now). My SSH using the Yubikey works perfect...

So, this is the output of `gpg card-status`:
```
gpg --card-status
Reader ...........: Yubico YubiKey OTP FIDO CCID
Application ID ...: D27600012401000000060123456780000
Application type .: OpenPGP
Version ..........: 2.1
Manufacturer .....: Yubico
Serial number ....: 123456789
Name of cardholder: My Name
Language prefs ...: de
Salutation .......: Hr.
URL of public key : [nicht gesetzt]
Login data .......: hello@foo.bar
Signature PIN ....: nicht zwingend
Key attributes ...: rsa4096 rsa4096 rsa4096
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 3 3
Signature counter : 20
UIF setting ......: Sign=off Decrypt=off Auth=off
Signature key ....: AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA 
      created ....: 2021-01-29 09:13:46
Encryption key....: BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB 
      created ....: 2021-01-29 09:14:44
Authentication key: CCCC CCCC CCCC CCCC CCCC CCCC CCCC CCCC CCCC 
      created ....: 2021-01-29 09:15:30
General key info..: sub  rsa4096/0xABCDEF12345678 2021-01-29 My Name <hello@foo.bar>
sec#  rsa4096/0x456789012  erzeugt: 2021-01-29  verfällt: niemals
ssb>  rsa4096/0x345678901  erzeugt: 2021-01-29  verfällt: 2022-01-29
                                  Kartennummer:0006 123456789
ssb>  rsa4096/0x234567890  erzeugt: 2021-01-29  verfällt: 2022-01-29
                                  Kartennummer:0006 123456789
ssb>  rsa4096/0x123456789  erzeugt: 2021-01-29  verfällt: 2022-01-29
                                  Kartennummer:0006 123456789
```

And here is what happens when I try to change expiry dates (I cut redundand information to keep the post concise):
```
gpg --edit-key $KEYID
Geheimer Unterschlüssel ist vorhanden.
# This is the german equivalent of "Secret Key is available."

pub  rsa4096/0xABCDEF12345678
     erzeugt: 2021-01-29  verfällt: niemals     Nutzung: C
     Vertrauen: ultimativ     Gültigkeit: ultimativ
ssb  rsa4096/0xBCDEF12345678A
     erzeugt: 2021-01-29  verfallen: 2022-01-29  Nutzung: S
     Kartennummer:0006 123456789
ssb  rsa4096/0xCDEF12345678AB
     erzeugt: 2021-01-29  verfallen: 2022-01-29  Nutzung: A
     Kartennummer:0006 123456789
ssb  rsa4096/0xDEF12345678ABC
     erzeugt: 2021-01-29  verfallen: 2022-01-29  Nutzung: E
     Kartennummer:0006 123456789
[ ultimativ ] (1). My Name <hello@1.de>
[ ultimativ ] (2)  My Name <hello@2.de>
[ ultimativ ] (3)  My Name <hello@foo.bar>
[ ultimativ ] (4)  My Name <Email>
[ ultimativ ] (5)  My Name <Email>
[ unbekannt ] (6)  My Name <Email>

gpg> key 1
[...]
gpg> key 2
[...]
gpg> key 3

pub  rsa4096/0xABCDEF12345678
     erzeugt: 2021-01-29  verfällt: niemals     Nutzung: C
     Vertrauen: ultimativ     Gültigkeit: ultimativ
ssb*  rsa4096/0xBCDEF12345678A
     erzeugt: 2021-01-29  verfallen: 2022-01-29  Nutzung: S
     Kartennummer:0006 123456789
ssb*  rsa4096/0xCDEF12345678AB
     erzeugt: 2021-01-29  verfallen: 2022-01-29  Nutzung: A
     Kartennummer:0006 123456789
ssb*  rsa4096/0xDEF12345678ABC
     erzeugt: 2021-01-29  verfallen: 2022-01-29  Nutzung: E
     Kartennummer:0006 123456789
[ ultimativ ] (1). My Name <hello@1.de>
[ ultimativ ] (2)  My Name <hello@2.de>
[ ultimativ ] (3)  My Name <hello@foo.bar>
[ ultimativ ] (4)  My Name <Email>
[ ultimativ ] (5)  My Name <Email>
[ unbekannt ] (6)  My Name <Email>
[...]

gpg> expire
Möchten Sie wirklich die Verfallsdaten aller Unterschlüssel ändern? (j/N): j
Bitte wählen Sie, wie lange der Schlüssel gültig bleiben soll.
         0 = Schlüssel verfällt nie
      <n>  = Schlüssel verfällt nach n Tagen
      <n>w = Schlüssel verfällt nach n Wochen
      <n>m = Schlüssel verfällt nach n Monaten
      <n>y = Schlüssel verfällt nach n Jahren
Wie lange bleibt der Schlüssel gültig? (0) 1y
Key verfällt am Di 20 Jun 22:19:26 2023 CEST
Ist dies richtig? (j/N) j
gpg: Beglaubigung fehlgeschlagen: No secret key
gpg: make_keysig_packet failed: No secret key
```

Are there insights into why this might happen? I do not get a dialogue requesting my PIN, although pinentry-mac seems to work just fine: When I use the SSH, pinentry shows up, I enter my PIN, everything is cool. 

Does anyone have an idea how I can investigate further or have you experienced this issue in the past and found a solution? I would love to hear from you :)

**Comment by psebening** [comment]
Maybe as additional info, when I run `gpg --list-secret-keys` the output is:
```
gpg --list-secret-keys
/Users/myname/.gnupg/pubring.kbx
-----------------------------------------
sec#  rsa4096/0x12345678ABCDEF 2021-01-29 [C]
  Schl.-Fingerabdruck = AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA 

[... all the UIDs here ...]
```

**Comment by iandstanley** [comment]
It looks like you may have created a master key (for auth) and subkeys (for ssh, signing and decryption)

The decoration “sec#” denotes that the master secret key is NOT present.  
If you have created a master key offline on day TailsOS then typically your master secret key is on wherever you backed it up and not on your daily driver machine. 

SSH will still work without the master auth secret key because it can and will use the encryption key together with your public key (which contains the public key of the master and subkeys)

But to change the expiry of either the master or a subkey you need the master secret key present. So you should boot up your TailsOS and restore the master key backup (or go back to the machine you have your master key on)

You should be then able to edit the keys and change the expiry. Don’t forget to re-export (and publish) the public key or else 3rd parties will get warnings.

**Comment by psebening** [comment]
I think you are absolutely right. Let me check this, oof I shortcircuited at that point. Will investigate tomorrow and close accordingly.

**Comment by psebening** [comment]
Thank you so much iandstanley. You are absolutely right. I got confused and did not go back to my assumptions. Thanks to your input I dug out the master key from the encrypted backup and voila, it worked as it has many times in the past. I set the expiry date on a few months to get more practice in the renewing process so I don't mess up again :)

Again, thank you for your elaborate explanation and fast reply! 👍 🥇

**Comment by iandstanley** [comment]
Don’t forget you can always create a dummy key to practice on. 

Despite MOST documentation y oh can put anything in the name as long as it has a space in it (to fool GPG into seeing first and second names) and any email-like address (even if it is invalid) GPG invalid expects a word followed by the @ and then one or more words separated by a “.” (So ***@***.*** is valid)

When I want to practice on something I first set the environment variable $GNUPGHOME to a dummy directory. Then I create a new key with a duration from 1d to 1w depending on what I am testing, how long I think I need to complete and how much spare time I have to devote to it. 

I have also got a couple of spare Yubikeys for playing around with and not for proper use.
