### ISSUE TITLE
--quick-add-key ... encrypt usage

### ISSUE THREAD

**Issue by willruggiano** [drduh/YubiKey-Guide#343]
When I try to generate an encryption key using the --quick-add-key command, I get the following error:
```
gpg: Key generation failed: Wrong key usage
```

Generating auth and sign subkeys works just fine, but I can't seem to find any documentation about what is going wrong here. Any suggestions?

**Comment by willruggiano** [comment]
It seems that the combination of ed25519 and encrypt is what is causing issues. Is it not possible to generate a ED25519 encryption key?

**Comment by iandstanley** [comment]
Could you add a transcript for context

**Comment by iandstanley** [comment]
Page 45 of the pdf manual says ….

If algo or usage are given, only the primary key is created and no prompts are shown. To specify an expiration date but still create a primary and subkey use “default” or “future-default” for algo and “default” for usage. For a description of these optional arguments see the command --quick-add-key. The usage accepts also the value “cert” which can be used to create a certification only primary key; the default is to a create certification and signing key

Without knowing what you had on the command line it could be that the entered command was defaulting to creating a certification and signing key 

OR …

And a bit later ….

To create an OpenPGP key from the keys available on the currently inserted smartcard, the special string “card” can be used for algo. If the card features an encryption and a signing key, gpg will figure them out and creates an OpenPGP key consisting of the usual primary key and one subkey. This works only with certain smartcards. Note that the interactive ‘--full-gen-key’ command al- lows to do the same but with greater flexibility in the selection of the smartcard keys.

This (the use of “card”) could suggest that if the word “card” was missing, GPG would not look at the smart card and be trying to figure out from the keys on the key ring which key to use (and failing)

Without knowing the command line used and also the contents of the card it is a bit difficult to interpret GPG’s terse errors

With errors like this it is best to give us the output of a GPG card status command to show us what is on the card, a key ring list and a cut and paste of the command entered plus output 

Without the context it is difficult with the terseness of GPG

**Comment by willruggiano** [comment]
I am using the exact commands from the guide, except with ed25519 instead of rsa4096.

```
gpg --batch --generate-key gen-params-ed25519
gpg --quick-add-key $FINGERPRINT ed25519 sign 1y
gpg --quick-add-key $FINGERPRINT ed25519 auth 1y
gpg --quick-add-key $FINGERPRINT ed25519 encrypt 1y
```

and the full error;
```
$ gpg --quick-add-key $FINGERPRINT ed25519 encrypt 1y        
gpg: Key generation failed: Wrong key usage
gpg: Key not changed so no update needed.
```

**Comment by hvhaugwitz** [comment]
You cannot use `ed25519` for encryption, use `cv25519` instead.

**Comment by willruggiano** [comment]
That is what I suspected. Thanks!
