### ISSUE TITLE
writing to /dev/random does not necessarily increase entropy count

### ISSUE THREAD

**Issue by mwette** [drduh/YubiKey-Guide#345]
I ran the example on "Prepare Environment" for my Ubuntu 22.04 system.  It did not increase the entropy count (as implied, as I read).  Then I read `man -s4 random`, I find
>        Writing to /dev/random or /dev/urandom will  update  the  entropy  pool
>        with  the  data  written,  but this will not result in a higher entropy
>        count.  This means that it will impact  the  contents  read  from  both
>        files, but it will not make reads from /dev/random faster.

Ref: https://github.com/drduh/YubiKey-Guide#entropy
Ref: https://github.com/drduh/YubiKey-Guide#yubikey

**Comment by mwette** [comment]
This is apparently due to update to Linux kernel: 
https://askubuntu.com/questions/1427470/entropy-is-stuck-at-256-after-upgrading-to-kernel-5-15-0-47

**Comment by bekcpear** [comment]
FYI:  https://bbs.archlinux.org/viewtopic.php?id=276734

I'm also confused. It looks like you don't need to pay attention to entropy_avail value anymore. But then I don't know how to tell if there is enough randomness, maybe the kernel promises it?

**Comment by drduh** [comment]
entropy_avail got a facelift in 5.18 and doesn't even provide a meaningful result anymore. We need to update the advice in this section.

**Comment by drduh** [comment]
Removed outdated advice, additional contributions to this section are welcome!
