### ISSUE TITLE
FYI Yubico is partnering with Cloudflare to sell Yubikeys from $10

### ISSUE THREAD

**Issue by iandstanley** [drduh/YubiKey-Guide#348]
Anybody looking to try out a Yubikey for 2FA and other security options or get one at big discounts should checkout Yubico's partnership with Cloudflare. They are currently doing an offer giving their customers heavy discounts on Yubikeys.

[The offer](https://www.cloudflare.com/products/zero-trust/phishing-resistant-mfa/) is open to any Cloudflare customer. Cloudflare customers can claim this offer for Yubico Security Keys directly in the Cloudflare dashboard.

Yubico is providing Security Keys at “Good for the Internet” pricing - as low as $10 per key. Yubico will ship the keys to customers directly.

I got mine code today.  The Voucher allows you to purchase upto 4 Yubikeys (5-NFC or 5C-NFC) from $10 plus VAT. I bought 4 5NFC keys for $140 discount (only $10 each) plus VAT and delivery. That's 4 for less than the price of 1 !

**Comment by drduh** [comment]
You got a good deal there. Feel free to link the offer in the guide with a PR!

**Comment by C0MM4ND3RT** [comment]
The blog said the offer ended on 3rd January 2023 8 AM PST however I still want one at same price is there any chance?

**Comment by iandstanley** [comment]
I suspect that the offer has ended as the process involves applying for the offer via cloudflare and then doing certain procedures like enabling one of their services for a domain you have enabled for them. Once enabled properly you get a voucher for Yubikey and a link where you could order upto 4 keys of a single type As this process required a cron job running on cloudflare to monitor progress of a config setup m and not just a voucher code, I suspect that the offer has properly terminated. Yubikey does these kinds of offers periodically, from the cloudflare offer to offers with magazine subscriptions. I’ve seen them every 18 months or so.  But the blurb by Yubikey seemed to indicate a bigger push than I’ve previously seen which suggests that once they have collated and evaluated the results of the offer they may consider doing it again sooner as their main thesis for the offer was to make it cheap for anyone to get on board. They regularly have a 2 for 1 offer. Also keep an eye on eBay were despite being plagued by overchargers (I’ve seen some people try and charge £90 for a £45 Yubikey 5NFC-A) you will always find cheap Yubikey 4 and 5 versions available below list price. You will typically pay £35-40 for a 5NFC-A or just £25-£30 for a Yubikey 4. Be aware that there is a significant performance and feature set difference between versions. Version 5 combined the features of both the Yubikey 4 and the Neo, added some extra crypto options (FIDO2, larger bit sizes, improved PIV and elliptic curves) and is significantly faster. I would generally avoid the Yubikey Neo on eBay as they are usually overpriced at the moment. EBay’s suggested price algorithm gets messed up and suggests £40 for a new Neo or £30-35 for a used. This is compounded by some ebayers buying them not knowing the difference, this pushing up the recommended price. I would recommend  looking for Neo’s at around the £18-25 mark USED (or upto £30 NEW) which seems to be the typical price the actually sell (ignoring the odd ignorant ebayer). I bought a lot of 5 for under £30 last year to use for training others. Again know your Yubikey models.  There are a number of Yubikey 2 (has a dot on the button) coming out for sale grossly overpriced. These models only support the Yubikey OTP and a static password and are generally useless for most people’s use cases as they don’t support FIDO/U2F nor PIV nor GPG. Again the eBay suggested price engine messes up and you see these being sold for £30-£35 where you should be going for a newer Yubikey 4. Feature wise these only really sell around the £15-£18 mark (usually for a static password key in the safe).  I bought one just to use as a WiFi password key. On 17 Jan 2023, at 08:30, Karsh Trivedi ***@***.***> wrote:﻿
The blog said the offer ended on 3rd January 2023 8 AM PST however I still want one at same price is there any chance?

**Comment by C0MM4ND3RT** [comment]
Thanks for the quick response and helpful information

Appreciate it.

Cheers
Karsh Trivedi
