### ISSUE TITLE
ROCA vunlerability?

### ISSUE THREAD

**Issue by simolina** [drduh/YubiKey-Guide#35]
from [THIS ARTICLE](https://arstechnica.com/information-technology/2017/10/crypto-failure-cripples-millions-of-high-security-keys-750k-estonian-ids/)

> The researchers also found 2,892 PGP keys used for encrypted e-mail, 956 of which were factorizable. The researchers speculated that the majority of the PGP keys were generated using the Yubikey 4, which allows owners to use the faulty library to create on-chip RSA keys. Other functions of the USB device, including U2F authentication, remain unaffected.

[From the researchers](https://crocs.fi.muni.cz/public/papers/rsa_ccs17)
[ONLINE KEY TESTS HERE](https://keychest.net/roca)

**Comment by robison** [comment]
It's a vulnerability in the underlying hardware, not in the directions outlined by this guide.

**Comment by simolina** [comment]
k. for ref here's YubiKey words:
[BLOG POST](https://www.yubico.com/2017/10/infineon-rsa-key-generation-issue/)
[SA](https://www.yubico.com/support/security-advisories/ysa-2017-01/)
