### ISSUE TITLE
kernel.random.poolsize is capped at 256 on newer kernels

### ISSUE THREAD

**Issue by zeorin** [drduh/YubiKey-Guide#351]
https://www.reddit.com/r/RNG/comments/wbd1eb/why_did_devrandom_decrease_their_poolsize_in/

Suggesting in the guide that users wait for 2000 bits of entropy, and having example values of `/proc/sys/kernel/random/entropy_avail` that are over 256 may trip some people up.

**Comment by drduh** [comment]
It should be cleaned up now.
