### ISSUE TITLE
WSL2 + Systemd running

### ISSUE THREAD

**Issue by drekinov** [drduh/YubiKey-Guide#352]
Hi
I have WSL2 + wsl2-ssh-pageant from #325 
However that agent has some issues and owner archive it because he is not on Windows anymore.

Considering that WSL2 is supporting systemd https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/
and it is working fine based on my tests except GPG forwarding from Windows.

With systemd enabled all services start as with normal VM / OS (cronjobs, ntp and etc) and gpg service is one of first so it creates its own local sockets.

Does anyone know what should be done or reference an article about topic ?
I will continue trying from time to time so i hope at some point that probably should become default behaviour .

**Comment by drduh** [comment]
Resolving to inactivity.

**Comment by moander** [comment]
@drduh this is still relevant.

All guides I have found did not work for me, and now I figured out why. It's because systemd is enabled. And for new WSL users, systemd is enabled by default.

**Comment by moander** [comment]
https://learn.microsoft.com/en-us/windows/wsl/connect-usb
