### ISSUE TITLE
gpg: key operation not possible: not an OpenGPG card

### ISSUE THREAD

**Issue by georgewhewell** [drduh/YubiKey-Guide#355]
hi,

i followed this guide several years ago and added subkeys to two yubikeys, has been working fine. recently my subkeys expired so i'm now trying to rotate them, however `keytocard` now fails with `gpg: key operation not possible: not an OpenGPG card`

the card can be read ok with `pgp --card-status` and my expired keys are visible and usable

i guess some version update of pgp has caused this? i am sure this was how i added the keys initially. currently i am using version `2.3.7`

**Comment by mwette** [comment]
How did you do this?  
 I have gpg version 2.2.27 and I can get to the command and it shows the card info.
```
$ gpg --card-status
...
ssb> rsa4096/<key> created:...
...
$ gpg --edit-key <key>
...
gpg> help
...
keytocard   move a key to a smartcard
...
```

**Comment by iandstanley** [comment]
I assume that no configuration changes to your machine have occurred (not a new machine without the drivers/software; Yubikey was working with the old keys so you haven't changed the Yubikey settings). 

I've had this issue in the when I have rebuilt a freebsd machine where Yubikeys are a bit awkward to get setup correctly)


Don't know if any of this is relevant ...

https://support.yubico.com/hc/en-us/articles/360013714479-Troubleshooting-Issues-with-GPG

**Comment by drduh** [comment]
Please reopen or send a PR if you find more information or a resoltion to your issue. Thanks!
