### ISSUE TITLE
MACOS IKEv2 auth with yubikey 

### ISSUE THREAD

**Issue by MartinBrook123** [drduh/YubiKey-Guide#357]
Hi, All,   I've invested nearly a month in searching for IKEv2 vpn auth with yubikey on macos. I try to choose the cert in yubikey , but failed to prompt every time when i started IKEv2 vpn connection. 

I am wondering if there's any possibilities to do it ?  Could anybody advise on this issue ?  appreciated in advance. 

PS: 
1. SSH auth works fine with yubikey on my macos. But there's no command like 'enable-ssh-support' for IKEv2 VPN.
2. I've achieved IKEv2 vpn auth with yubikey on windows. It seems windows can interact with Yubikey perfectly but not on macos.

**Comment by drduh** [comment]
If this is possible, please reopen or better send a PR. Thank you.
