### ISSUE TITLE
Good guide: But it should be implemented in used friendly software

### ISSUE THREAD

**Issue by hollaho** [drduh/YubiKey-Guide#36]
Please don't see this as a rant - I really appreciate that good, detailed and working guides like this are around.

But the real major issue (which the author of this guide is not to blame for) with pgp / email encryption and such things as the yubikey is the "user-experience", which is just horrible. The yubikey is a good step forward in many things, but implementing / using the smart-card function as it is now is something only a few nerds and power users will do.

What we really need is to obsolete such guides by making it easy and intuitive to use the yubikey for pgp keys from kleopatra and other key management software. This is when we will see more adoption.

**Comment by robison** [comment]
I'm not sure why you would open this as an issue; there is no substantive value in you stating "What we really need is to obsolete such guides". While that may or may not be true, I can't understand how that's worthy of discussion in a venue like this one.

**Comment by drduh** [comment]
Agreed and wish I had the time and skills to do more.
