### ISSUE TITLE
ECC rather than RSA

### ISSUE THREAD

**Issue by btlogy** [drduh/YubiKey-Guide#365]
As discussed previously in #52 and #270, now might be a better time to document ECC by default rather than RSA.

See a proposal in #362.

PS: Thank you @drduh for this very useful guide BTW.

**Comment by L-Schwarz** [comment]
As mentioned in this article: https://security.stackexchange.com/questions/255358/why-does-ecc-not-have-an-encrypt-capability-in-gpg-but-rsa-does the usage of ECC is a bit more complicated but the combination of this article and the guide, a setup with ECC should be possible. I am gonna try it in the next months, when i have time for it

**Comment by smlx** [comment]
ECC subkey handling is currently rather broken in gnupg - see, for example, https://dev.gnupg.org/T5555

**Comment by drduh** [comment]
Until there's a compelling reason offered to use ECC for Yubikeys, let's stick to tried and true RSA for defaults. As before, anyone is welcome to add an additional section on generating ECC keys instead and using them - please send a PR.
