### ISSUE TITLE
Confusion regarding the key generation and use process

### ISSUE THREAD

**Issue by AliSajid** [drduh/YubiKey-Guide#366]
Hi.

Thank you for this really detailed guide. It has been very helpful and instrumental in me getting YubiKeys for myself and my family. I am the only one that does a lot of the work that requires GPD keys and SSH keys so I had some questions. These me sound stupid or obvious but I am learning and would appreciate the help.

I am in the process of generating the keys on a Live Disk environment. I am able to generate keys and save the master key and subkeys and other stuff on my External SD Card as well. Here are my questions:

* Am I correct in understanding that once I move my secret keys to the YubiKey using `keytocard`, I would have to have my key plugged in for it to be usable?
* I have the public keys and they can be uploaded to servers. Do I need to import my secret keys separately into each device as well? I have Two macbooks, one PC and A Linux laptop as my regular setup.
* I am unclear about which password I could use to unlock my GPG keys once it is connected to my computer. There was a password set up for the master key. Do I need to memorize that or just the physical presence of the key is sufficient?

Thank you.

**Comment by ParkerK** [comment]
>Am I correct in understanding that once I move my secret keys to the YubiKey using keytocard, I would have to have my key plugged in for it to be usable?  
Yes. The only way would be to insert the key, or use a backed up copy of the key (which would defeat the purpose of using a hardware key though)

>  I have the public keys and they can be uploaded to servers. Do I need to import my secret keys separately into each device as well? I have Two macbooks, one PC and A Linux laptop as my regular setup.  
The secret/private keys are stored on your Yubikey, when you sign something, it's done on the keys hardware itself. 

>  I am unclear about which password I could use to unlock my GPG keys once it is connected to my computer. There was a password set up for the master key. Do I need to memorize that or just the physical presence of the key is sufficient?   
You'll need the password to do things like renewing subkeys. Not sure otherwise. 

I'm still learning all the ins and outs, so hopefully someone with better knowledge can correct me if I'm wrong

**Comment by AliSajid** [comment]
Thank you. This clears things up.
