### ISSUE TITLE
Bad file descriptor when trying to change Admin PIN

### ISSUE THREAD

**Issue by harmtemolder** [drduh/YubiKey-Guide#367]
I'm not sure where this error originates from, so I'll describe the context:

- I set up GPG on two YubiKeys a year ago, following this guide, one as a backup to the other
- Two months ago I updated their expiration dates as described [here](https://github.com/drduh/YubiKey-Guide#renewing-sub-keys)
- Yesterday I entered the GPG pin incorrectly 3 times when trying to open Password Store on my Android phone, so now `gpg -card-status` says `0 0 3`
  - I'm 99% sure the 2nd and 3rd times were correct, but that's a different issue
- This morning I'm trying to unblock the PIN using the admin PIN as described [here](https://github.com/drduh/YubiKey-Guide#change-pin)
  - `gpg --card-edit`
  - `admin`
  - `passwd`
  - `2`

The first time I pasted in the admin password, which must have added a space or something, because I got

```
Error unblocking the PIN: Bad PIN
```

I then tried the admin PIN of my backup YubiKey, thinking I mixed them up. So I'm down to `0 0 1`

But when typing the correct one in manually, 100% sure it matches what I have written down I got

```
Error changing the PIN: Bad file descriptor
```

On my backup YubiKey (so the one that isn't blocked) I tried changing the admin PIN (option `3`), typing it manually as well, and received the same error.

One thing I can think of is that both admin PINs are alphanumeric, so including numbers and lower- and uppercase letters. No symbols.

```
$ gpg --version
gpg (GnuPG) 2.2.40
libgcrypt 1.10.1-unknown
...
```

What could be causing this, and how can I fix it?

Edit: I'm on Manjaro Linux

**Comment by drduh** [comment]
I can only suggest resetting the card and provisioning it from backup if you're locked out. Otherwise, it's not clear what caused this issue. The guide could benefit from additional guidance on selecting secure and usable PINs, however.
