### ISSUE TITLE
Yubikey ssh on iOS or Android? Any apps compatible?

### ISSUE THREAD

**Issue by Danrancan** [drduh/YubiKey-Guide#368]
I would like to ssh into my server using gpg-agent on either iOS or Android, but can't find any compatible apps that support NFC Yubikeys for ssh public key authentication. If the Yubico forums weren't read only, I would post on there since this isn't completely relevant for drduh (although maybe it could be noted somewhere in the tutorial). My question is, are there any apps (primarily terminal emulators) on either iOS or android that support ssh with a yubikey? Any help or links would be appreciated.

**Comment by lxhom** [comment]
Yes! Here's me logging into GH on my Android phone via my Yubikey on Termux:

![Screenshot_20230203-012007](https://user-images.githubusercontent.com/73352734/216480694-e322ff6a-da62-4fe7-a097-f617c9cd9634.jpg)

[OpenKeychain](https://www.openkeychain.org/) is your friend. You need to install it (I reccomend
getting it from [F-Droid](https://f-droid.org/app/org.sufficientlysecure.keychain)).
Then you click on Use Security Token. If your key is already in a couple of keybases, it will handle the rest, or you will get this screen that looks like an error:

![Screenshot_20230203-012649](https://user-images.githubusercontent.com/73352734/216483705-8fdaf5e9-54f4-446a-8f0c-62e18ff18ff1.jpg)

Just click on Load from file and select your public key. Then you click on Import, and you're almost done.

Now you need to install [OkcAgent](https://github.com/DDoSolitary/OkcAgent) (again,
install it via [F-Droid](https://f-droid.org/packages/org.ddosolitary.okcagent/)). Open the app and select a GPG and SSH key.

Now you just need a terminal. You could try using others, but [Termux](https://termux.dev) is the de facto standard for Android terminals. (Again, get it from [F-Droid](https://f-droid.org/en/packages/com.termux/). Especially avoid the Play Store version, it is unmaintained.)

Once you have that installed, you need to install okc-agent by running `pkg install okc-agent`. Then you need to run the agent by running `eval $(okc-ssh-agent)`, and you can use SSH with `ssh` and (a limited version of) GPG with `okc-gpg`.

If you use SSH/GPG now, you will get a notification fron okc-agent, and clicking it causes the OpenKeychain window to pop up. Simply follow the instructions for NFC or plug it in via USB & touch your key if neccesary and you're in!

Also, pro tip: Add `eval $(okc-ssh-agent)` to your `.bashrc` file to avoid having to type it every time.

Side note: You might get an error like this if you use termux-chroot:

> unix_listener: path "/data/data/com.termux/files/home/.ssh/control-master/sock-f3fdaffef437e1af146dae6b743e620af8ec06a9.scgIhHKkqNQHDuzf" too long for Unix domain socket

You can either configure the socket path, or add this hack to your shells .rc: `ssh() { bash -c "ssh $@" }` Works for me on ZSH + termux-chroot.

**Comment by drduh** [comment]
@lxhom thanks for sharing - we would greatly appreciate a PR to add your process to the guide.

**Comment by intertree** [comment]
So. I can get the pop up to come up and request a tap from the yubikey to continue to try and establish an ssh connection to my remote server, but it doesn't seem to actually use the yubikey itself as the ssh credentials. 

This is after I copied the output of sharing as a public ssh key using the openkeychain app and pasted it into my remote server's authorized_keys file. 

Is there anything additional I need to add to the:

ssh username@remote.server.ip.address 

To make it explicitly use the yubikey's identity subkey?

Note: I also installed Okcagent and selected the yubikey's identity subkey as the one to use.

**Comment by matrixes** [comment]
There seems to be cloudy weather ahead when it comes to Yubikey-support using OpenKeychain/OkcAgent for this use case on newer versions of Android; https://github.com/termux/termux-api/issues/393#issuecomment-1855842492

**Comment by Paraphraser** [comment]
I can't say I've used Termius+YubiKey but I do use Termius extensively from iOS (mainly iPad, occasionally iPhone). It claims [YubiKey support](https://www.yubico.com/works-with-yubikey/catalog/termius/). Does that help?

**Comment by sevmonster** [comment]
Terminus only supports local 2FA when connecting to sessions.

**Comment by drduh** [comment]
Thank you all for the discussion and suggestions. Let's move this to a PR if enough people are interested in this topic.

**Comment by architomsn** [comment]
> 
> As right now all I'm getting is the 'Permission denied (publickey)' error each time I try to connect.
> 

Same here. 

It should be noted that the key from Yubikey works: I tried the key with termbot and it worked immediately with the ssh-server.
