### ISSUE TITLE
"Prepare environment" suggests use of "Debian Live or Tails", but the commands and env setup have no support for Tails.

### ISSUE THREAD

**Issue by Danrancan** [drduh/YubiKey-Guide#369]
In the "Prepare Environment" section, drduh suggests using a debian live usb, or a Tails usb. Using tails is probably a bit more secure than debian live, and I suggest that the tutorial includes the proper commands (most debian commands don't directly work with tails at the moment due to amnesia) to setup the right environment for creating gpg keys on the yubikey. Last time I checked, Tails didn't have most of the required packages installed, and some weren't installable due to repository issued with amnesia. Maybe someone (Me, but I won't have the time for a few months) could try following the tutorial using the latest version of tails, and document all the differences between commands and environment setup in order to make this tutorial fully compatible with tails. If you ask me, Tails SHOULD absolutely be the default secure environment to set up a Yubikey, because it is more secure by default, and it is Amnesia. There should be extra instructions for Tails and setting up the proper environment and downloading the proper packages. What does everyone think?

**Comment by ParkerK** [comment]
Amnesia only applies to when you reboot the system. You should still be able to install all of the required packages on Tails, the same you would on debian.

**Comment by lxhom** [comment]
Can confirm that it works. Installing pip3 packages is a tiny bit more complicated (you need to proxy it through Tor or disable the firewall, the easiest way is using `torsocks pip3 install whatever` on a non-root terminal), but otherwise it's smooth sailing.

**Comment by Danrancan** [comment]
> Can confirm that it works. Installing pip3 packages is a tiny bit more complicated (you need to proxy it through Tor or disable the firewall, the easiest way is using `torsocks pip3 install whatever` on a non-root terminal), but otherwise it's smooth sailing.

I guess my personal reference to doing this on tails is a bit outdated since last time I booted tails for a yubikey was over a year ago, and I ended up giving up because it was too undocumented of a process on the older version of tails and not all packages could be obtained easily. I didn't know about the torsocks pip3 trick. I will try this next time I build some yubikeys.

**Comment by Danrancan** [comment]
> You should still be able to install all of the required packages on Tails, the same you would on debian.

Is this in theory, or has this actually been tested by someone contributing to the guide?

**Comment by iandstanley** [comment]
Debian is the parent distro for Tails. Tails is basically just a set of scripts sitting on top of a custom install of tails, a carefully configured TOR and firewall plus whatever proxy configs the applications require and finally add a few application packages from the Debian repo (plus a couple of specially written Tails packages like the Tails Installer)On 16 Feb 2023, at 22:07, Dan Ran ***@***.***> wrote:﻿

You should still be able to install all of the required packages on Tails, the same you would on debian.

Is this in theory, or has this actually been tested by someone contributing to the guide?

**Comment by Danrancan** [comment]
> Debian is the parent distro for Tails. Tails is basically just a set of scripts sitting on top of a custom install of tails, a carefully configured TOR and firewall plus whatever proxy configs the applications require and finally add a few application packages from the Debian repo (plus a couple of specially written Tails packages like the Tails Installer)On 16 Feb 2023, at 22:07, Dan Ran ***@***.***> wrote:﻿ You should still be able to install all of the required packages on Tails, the same you would on debian. Is this in theory, or has this actually been tested by someone contributing to the guide? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Some instructions that aren't included off the top of my head when using tails, is to create an admin password on boot because otherwise amnesia won't give you root access to download from repositories. I'm going to try and do a full walkthrough in tails in the next couple of days and post the log and notes about any differences to debian.

**Comment by drduh** [comment]
@Danrancan any notable differences between Debian Live and Tails to note?

**Comment by drduh** [comment]
The guide tries to balance security with usability and I believe Debian Live is a good match for generating secure credentials in a convenient way. While Tails could be better under certain circumstances, it would not significantly benefit most users as the default. If anyone would like to document steps to use it, and compelling reasons to, please send a PR.
