### ISSUE TITLE
NixOS Build Broken

### ISSUE THREAD

**Issue by ParkerK** [drduh/YubiKey-Guide#370]
While following the NixOS build instructions I came across a few issues:

Building initially gave an error 
> error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

I was able to fix this by using ` nix --extra-experimental-features nix-command build -f yubikey-installer.nix -o installer nixos-yubikey`

The next issue was I got an error about yubioath-desktop being deprecated
>error: yubioath-desktop has been deprecated by upstream in favor of yubioath-flutter

I was able to fix that by replacing `yubioath-desktop` with `yubioath-flutter`

The final issue I have is 
>error: builder for '/nix/store/g7pw6yjayp9qxmbh72b8pwx82j1jxq2v-hopenpgp-tools-0.23.7.drv' failed with exit code 1;
       last 10 log lines:
       >     In an equation for ‘spGetSCT’:
       >         Patterns of type ‘Pkt’ not matched:
       >             PKESKPkt _ _ _ _
       >             SKESKPkt _ _ _ _
       >             OnePassSignaturePkt _ _ _ _ _ _
       >             SecretKeyPkt _ _
       >             ...
       >     |
       > 211 | spGetSCT (SignaturePkt s) = fmap fromIntegral (sigCT s)
       >     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       For full logs, run 'nix log /nix/store/g7pw6yjayp9qxmbh72b8pwx82j1jxq2v-hopenpgp-tools-0.23.7.drv'.

It looks like `hopengpg-tools` is broken for nix? https://github.com/NixOS/nixpkgs/blob/6f3728df507fd1683cf16e49a0078dc800330259/pkgs/development/haskell-modules/configuration-hackage2nix/broken.yaml

https://github.com/NixOS/nixpkgs/search?q=hopenpgp&type=issues

I just wanted to open this issue to see if anyone has solved this. In the meantime, I'll keep researching and if I can get it working, I'll post a PR.

Thanks for this great guide drduh! And thanks to everyone else who has contributed

**Comment by ParkerK** [comment]
It looks like the current airgapped NixOS config was based on https://github.com/dhess/nixos-yubikey (according to https://github.com/drduh/YubiKey-Guide/pull/342)

Some files of interest
https://github.com/dhess/nixos-yubikey/blob/master/nix/sources.json
https://github.com/dhess/nixos-yubikey/blob/master/lib/default.nix
https://github.com/dhess/nixos-yubikey/blob/master/default.nix

In that repo, it looks like specific versions are being targeted to prevent hopengpg from breaking?


I have no experience with NixOS, so I just wanted to document what I've found so far, in case it helps save time for someone who knows NixOS better.

**Comment by ParkerK** [comment]
It looks like the current airgapped NixOS config was based on https://github.com/dhess/nixos-yubikey (according to https://github.com/drduh/YubiKey-Guide/pull/342)

Some files of interest
https://github.com/dhess/nixos-yubikey/blob/master/nix/sources.json
https://github.com/dhess/nixos-yubikey/blob/master/lib/default.nix
https://github.com/dhess/nixos-yubikey/blob/master/default.nix

In that repo, it looks like specific versions are being targeted to prevent hopengpg from breaking?


I have no experience with NixOS, so I just wanted to document what I've found so far, in case it helps save time for someone who knows NixOS better.

Looping in @zeorin @rvl @reissmann as you three have all made nice contributions to the Nix build. Sorry to bother you, just wanted to loop you in in case you were interested

**Comment by nodupe** [comment]
Hi,
I've managed to make it work using a dirty workaround. I did three main things:

1 - Changed the desktop package to the flutter one,
yubioath-flutter
2 - Pinned the version of the Haskel program to one that compiles properly:
`    pkgs = import (builtins.fetchTarball {
        url = "https://github.com/NixOS/nixpkgs/archive/3b05df1d13c1b315cecc610a2f3180f6669442f0.tar.gz";
    }) {};                                                                         

      myPkg = pkgs.haskellPackages.hopenpgp-tools;`

and removed:
`        # Testing
        ent
        (haskell.lib.justStaticExecutables haskellPackages.hopenpgp-tools)`
3 - Forced the kernel of the image to be a ZFS compatible to avoid some weird license issues.
`boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;`

It booted and I've managed to prepare my yubikey.

Note that this is my first week in nixos, I am not sure I am doing all as it is supposed to be done.
The modified file is below for inspection. Hope it helps.
[yubikey-installer.nix.txt](https://github.com/drduh/YubiKey-Guide/files/11186003/yubikey-installer.nix.txt)

**Comment by pkel** [comment]
A simple workaround is to use the stable `nixos-22.05` channel:

```shell
nix build -f yubikey-installer.nix -o installer nixos-yubikey -I nixpkgs=channel:nixos-22.05
```

As noted above, you might have to temporarily enable `nix-command`, but that's a separate issue.

```shell
nix build --extra-experimental-features nix-command -f yubikey-installer.nix -o installer nixos-yubikey -I nixpkgs=channel:nixos-22.05
```

**Comment by NotAShelf** [comment]
Nixos 22.05 is now deprecated (and so is 22.11 at the time of writing, long live 23.05!)

If it is desirable, I will make a PR to pin nixpkgs to the current stable version of Nixos.

**Comment by rda716** [comment]
Apparently neither the updated version from @nodupe of `yubikey-installer.nix`, nor the additional command-line options for `nix build` from @pkel work anymore:

```
[vagrant@nixbox:~]$ time nix build -f yubikey-installer.nix -o installer nixos-yubikey -I nixpkgs=channel:nixos-22.05
warning: unable to download 'https://nixos.org/channels/nixos-22.05/nixexprs.tar.xz': Peer certificate cannot be authenticated with given CA certificates (60); retrying in 332 ms
warning: unable to download 'https://nixos.org/channels/nixos-22.05/nixexprs.tar.xz': Peer certificate cannot be authenticated with given CA certificates (60); retrying in 692 ms
warning: unable to download 'https://nixos.org/channels/nixos-22.05/nixexprs.tar.xz': Peer certificate cannot be authenticated with given CA certificates (60); retrying in 1040 ms
warning: unable to download 'https://nixos.org/channels/nixos-22.05/nixexprs.tar.xz': Peer certificate cannot be authenticated with given CA certificates (60); retrying in 2352 ms
warning: Nix search path entry 'channel:nixos-22.05' cannot be downloaded, ignoring
error: anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/release.nix:1:1 called with unexpected argument 'configuration', at /home/vagrant/yubikey-installer.nix:165:11

real    0m4.917s
user    0m0.075s
sys     0m0.031s

[vagrant@nixbox:~]$
```

Any ideas on how to get this working are welcome.

**Comment by MaienM** [comment]
This looks like there's something wrong with your environment preventing it from verifying the certificates (or there were issues with `nixos.org` when you tried it that have since cleared up). The URL it complains about (`https://nixos.org/channels/nixos-22.05/nixexprs.tar.xz`) resolves and has a valid certificate, and the command works fine on my machine.

**Comment by rda716** [comment]
The certificate for nixos.org is expired:

```
[nix-shell:~]$ wget https://nixos.org/channels/nixos-22.05/nixexprs.tar.xz
--2023-06-28 13:56:23--  https://nixos.org/channels/nixos-22.05/nixexprs.tar.xz
Resolving nixos.org (nixos.org)... 35.229.48.116, 54.84.236.175, 2600:1f18:2489:8201::c8, ...
Connecting to nixos.org (nixos.org)|35.229.48.116|:443... connected.
ERROR: cannot verify nixos.org's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to nixos.org insecurely, use `--no-check-certificate'.
```

The same command works when run directly on the machine that is hosting the Vagrant VM.

For some reason, the certificate for nixos.org cannot be updated.

Output of `nix-info`:

```
[vagrant@nixbox:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by rda716** [comment]
> Nixos 22.05 is now deprecated (and so is 22.11 at the time of writing, long live 23.05!)
> 
> If it is desirable, I will make a PR to pin nixpkgs to the current stable version of Nixos.

That would be very helpful, but not sure how easy that is to do.

**Comment by kaikikokuke** [comment]
> 

First off thanks to all the contributers to this repo. It is a really well documented guide.

In order for nix build to complete without issues, a certain version of `nixpkgs` should be used. The easiest way is to use the `-I` flag (As mentioned by @pkel). It is also possible to update this code and use a `nix flake`, which has a pinned version of `nixpkgs` in its `inputs` section. If I understood correctly, this shouldn't be a problem as it is intended for a complete offline installation. 

@drduh is it acceptible if someone created a pull request with the simple solution (using -I to set nixpgks version)?

**Comment by motiejus** [comment]
> In order for nix build to complete without issues, a certain version of `nixpkgs` should be used. The easiest way is to use the `-I` flag (As mentioned by @pkel). It is also possible to update this code and use a `nix flake`

I spent some time trying to make `yubikey-installer.nix` work with flakes, but to no avail: I could not find a signature similar to this one:

```
nix-repl> builtins.functionArgs (import <nixpkgs/nixos/release.nix>)         
{ configuration = true; nixpkgs = true; stableBranch = true; supportedSystems = true; }
```

... when nixpkgs is imported via a flake.

I think it we need to *at least* specify `-I`  to make sure this keeps building when nixpkgs evolves, especially across releases/breaking changes. I would personally also favor flakes, since that adds full determinism, and the trade-offs, in my view, seem to be OK with the nature of this image.

@kaikikokuke do you have an example you could share that makes this work with flakes?

**Comment by zeorin** [comment]
Hey all, :wave: 

Sorry for the radio silence on this issue. I kept meaning to get round to fixing this, but my bandwidth for OSS has been really low recently. Anyway, my GPG key expired :joy: and I need to extend/renew it so this suddenly became a pressing issue.

PR is up at https://github.com/drduh/YubiKey-Guide/pull/396. Please try it out and let me know how it goes.

**Comment by bphd** [comment]
> Apparently neither the updated version from @nodupe of `yubikey-installer.nix`, nor the additional command-line options for `nix build` from @pkel work anymore:
> 
> ```
> warning: Nix search path entry 'channel:nixos-22.05' cannot be downloaded, ignoring
> ```
> 
> Any ideas on how to get this working are welcome.

Experiencing the same with 23.05, but it's more about `       at «none»:0: (source not available)`

**Comment by zeorin** [comment]
@bphd Would you be able to copy/paste your command line input together with its output here? I just ran `nix-build yubikey-installer.nix --out-link installer --attr nixos-yubikey` with [the current `yubikey-installer.nix`](https://github.com/drduh/YubiKey-Guide/blob/c41729520faf06c352510118ec9bb042bf4a40e7/README.md#nixos) and it built just fine.

**Comment by bphd** [comment]
> @bphd Would you be able to copy/paste your command line input together with its output here? I just ran `nix-build yubikey-installer.nix --out-link installer --attr nixos-yubikey` with [the current `yubikey-installer.nix`](https://github.com/drduh/YubiKey-Guide/blob/c41729520faf06c352510118ec9bb042bf4a40e7/README.md#nixos) and it built just fine.

I've figured that I was asking 25.03 instead of 23.05, hence the problem

**Comment by EricWardner** [comment]
My attempt to build is failing with

```
error: cannot download optparse-applicative-0.18.1.0-r1.cabal from any mirror
error: builder for '/nix/store/ym132z6q999lplzw22y9zyji6w5as1w2-optparse-applicative-0.18.1.0-r1.cabal.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/revision/1.cabal
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0    77    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download optparse-applicative-0.18.1.0-r1.cabal from any mirror
       For full logs, run 'nix-store -l /nix/store/ym132z6q999lplzw22y9zyji6w5as1w2-optparse-applicative-0.18.1.0-r1.cabal.drv'.
```

**Comment by zeorin** [comment]
@EricWardner the version number it's trying to download there doesn't seem correct… Not sure where it would get that from, the version in the `README.md` is `0.18.1.0`, not `0.18.1.0-r1.cabal`.

**Comment by thomaseizinger** [comment]
I attempted the conversion to a flake. See https://github.com/drduh/YubiKey-Guide/issues/406. Feedback is much appreciated :)

**Comment by motiejus** [comment]
Regenerating doesn't work for me :(

```
$ maintainers/scripts/haskell/regenerate-hackage-packages.sh
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
these 2 paths will be fetched (2.43 MiB download, 15.92 MiB unpacked):
  /nix/store/7h0wrvl3ckgx2hc5460mjja3w7jijq6i-cabal2nix-unstable-2023-11-02
  /nix/store/2572jl8vhhimwcdy0rj5qq230l4ynw4z-distribution-nixpkgs-1.7.0.1-data
copying path '/nix/store/2572jl8vhhimwcdy0rj5qq230l4ynw4z-distribution-nixpkgs-1.7.0.1-data' from 'https://cache.nixos.org'...
copying path '/nix/store/7h0wrvl3ckgx2hc5460mjja3w7jijq6i-cabal2nix-unstable-2023-11-02' from 'https://cache.nixos.org'...
maintainers/scripts/haskell/regenerate-hackage-packages.sh: line 71: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
Obtaining Hackage data …
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
this derivation will be built:
  /nix/store/cbz1ki2rngmdgyz8fsg395inxsvsldy0-unpacked-cabal-hashes.drv
this path will be fetched (65.43 MiB download, 66.95 MiB unpacked):
  /nix/store/87bg2gniirfrz4qr1lfiw9iyb6dq07v6-all-cabal-hashes-def4ad9.tar.gz
copying path '/nix/store/87bg2gniirfrz4qr1lfiw9iyb6dq07v6-all-cabal-hashes-def4ad9.tar.gz' from 'https://cache.nixos.org'...
building '/nix/store/cbz1ki2rngmdgyz8fsg395inxsvsldy0-unpacked-cabal-hashes.drv'...
Generating compiler configuration …
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
Running hackage2nix to regenerate pkgs/development/haskell-modules/hackage-packages.nix …
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
hackage2nix: /home/motiejus/code/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix: withFile: invalid argument (cannot encode character '\8211')

[motiejus@fwminex:~/code/nixpkgs]$ git diff --stat
 pkgs/development/haskell-modules/hackage-packages.nix | 321918 +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 file changed, 1 insertion(+), 321917 deletions(-)
```
