### ISSUE TITLE
Key Server links broken

### ISSUE THREAD

**Issue by PhilipMay** [drduh/YubiKey-Guide#373]
The 2 links in this text seem to be broken:

> After some time, the public key will propagate to [other](https://pgp.key-server.io/pks/lookup?search=doc%40duh.to&fingerprint=on&op=vindex) [servers](https://pgp.mit.edu/pks/lookup?search=doc%40duh.to&op=index).

**Comment by drduh** [comment]
That's too bad, anyone know what happened to these two keyservers?
