### ISSUE TITLE
Display link to validate identity when pushing to keyserver

### ISSUE THREAD

**Issue by withinboredom** [drduh/YubiKey-Guide#374]
When sending keys to openpgp.org, user identity is stripped until verified. In order to verify, it is handy to do so immediately after sending the key:

`gpg --send-key $KEYID | curl -T - https://keys.openpgp.org`

**Comment by drduh** [comment]
@withinboredom would you mind documenting this detail with a PR? Would be glad to review and merge it. Thanks!
