### ISSUE TITLE
Complement guide for how to use yubikey on two computers

### ISSUE THREAD

**Issue by Yrlish** [drduh/YubiKey-Guide#382]
I found this about using the same yubikey on multiple computers: https://www.reddit.com/r/yubikey/comments/etj43j/yubikey_with_gpg_on_two_machines/

But I thought it would be great if your guide complemented with a section about this, so we can have it all in the same place. :slightly_smiling_face:

**Comment by RichardJActon** [comment]
This would be a very helpful addition and I think it relates to #381, I've read a number of Yubikey + GPG guides trying to find one which includes instructions on using a computer other than the one that you setup the Yubikey on. I think is an important step given that one might want generate keys in a temporary disposable environment like tails then use them elsewhere day to day.

**Comment by dkarlovi** [comment]
I'm not sure what issue you have on using the Yubikey on two computers, I use mine on two (desktop and laptop) and it all just works?

**Comment by iandstanley** [comment]
According to the Reddit thread you are just asking how to use your key on a second computer. 


It's quite simple really. 

Starting with a properly setup Yubikey GPG key as per instructions, you need to do 2 things to get it working on a second:

1. Get the public key onto the second computer (either by copying or importing from your key server)

2. Create the local stub for the private key (gpg --card-status should suffice to generate the stub)

If you have the url set to your public key, you can also _gpg --card-edit_, then issue the _fetch_ command to retrieve your public key.

**Comment by Paraphraser** [comment]
Another approach is to export your public key on your first machine:

```
$ gpg --export --armor «yourKeyID» >my.public.key.txt
```

Then, on the second machine:

```
$ gpg --import my.public.key.txt 
```

If you want to silence trust warnings like these:

```
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

you can set trust on the public key after you import it:

```
$ gpg --edit-key «yourKeyID»
gpg> trust
Your decision? 5
Do you really want to set this key to ultimate trust? (y/N) y
gpg> quit
```

Once you have set up trust the first time using `--edit-key`, you can export it:

```
$ gpg --export-ownertrust >gpg-owner-trust.txt
```

Then, you can import trust on any new machine:

```
$ gpg --import-ownertrust <gpg-owner-trust.txt
```

> That saves/restores trust for **all** keys in your keychain which have trust levels but it's just a text file so you can remove any unwanted lines.

So, bottom line, providing you have your YubiKey, `my.public.key.txt` and `gpg-owner-trust.txt`, setting up a new machine is:

1. Stick the YubiKey in the USB port.
2. Run:

	```
	$ gpg --import my.public.key.txt
	$ gpg --import-ownertrust <gpg-owner-trust.txt
	$ gpg --card-status
	```

**Comment by Yrlish** [comment]
@iandstanley Correct. I am asking to add these steps to the full guide for how to step up usage of your GPG keys from your Yubikey on a new computer.

As you say, the steps aren't that hard or many. But it would be nice having them written down on the same place to where the instructions to set up the key is located.

**Comment by iandstanley** [comment]
I've never set the url filed for the command line. An alternative is to use the --edit-card and then the url command

**Comment by Paraphraser** [comment]
Sorry. I probably did not explain the problem clearly.

Consider the following command:

```
$ gpg --keyserver hkps://keyserver.ubuntu.com:443 --recv "$KEYID"
```

That will go off to `keyserver.ubuntu.com`, search for the key with that ID and, if successful, will download and add it to the keychain. Agreed?

Now consider this sequence:

```
$ gpg --edit-card
gpg/card> admin
gpg/card> url
URL to retrieve public key: «URL-goes-here»
``` 

What I *was* trying to figure out was the correct string for `«URL-goes-here»` which would have the same behaviour as the `--keyserver` command above.

But please note the past tense. That was last night (UTC+10). This morning I tried a different approach and Googled RFCs that explained the hkp/hkps protocol.

**Qapla'**

Here's the magic incantation (from [Shaw 2003](https://datatracker.ietf.org/doc/html/draft-shaw-openpgp-hkp-00)):

```
$ [[ ! "$KEYID" =~ ^"0x" ]] && KEYID="0x${KEYID}"
$ URL="hkps://keyserver.ubuntu.com:443/pks/lookup?op=get&search=${KEYID}"
$ echo $URL
```

In words, make sure KEYID is formally described as a hex value, then tack it onto that basic URL. Copy the result and then paste it into the URL field on the card.

With that in place on the card, the `fetch` command works. Plus, a side-effect of the `fetch` command is to bring in the stubs for the private key so there's no need for the `--card-status` step. Setting up a new host becomes:

1. Stick the YubiKey in the port.
2. Fetch the public key using the URL stored on the card:

	```
	$ gpg --edit-card
	…
	URL of public key : hkps://keyserver.ubuntu.com:443/pks/lookup?op=get&search=0xFF3E7D88647EBCDB
	…
	
	gpg/card> fetch
	gpg: requesting key from 'hkps://keyserver.ubuntu.com:443/pks/lookup?op=get&search=0xFF3E7D88647EBCDB'
	gpg: /home/pi/.gnupg/trustdb.gpg: trustdb created
	gpg: key FF3E7D88647EBCDB: public key "Dr Duh <doc@duh.to>" imported
	gpg: Total number processed: 1
	gpg:               imported: 1
	
	gpg/card> quit
	```

3. Define the KEYID (which is helpfully displayed in three places in the previous command):

	```
	$ KEYID=0xFF3E7D88647EBCDB
	```

4. Set trust:

	```
	$ gpg --edit-key $KEYID 
	gpg> trust
	Your decision? 5
	Do you really want to set this key to ultimate trust? (y/N) y
	gpg> quit
	```

**Comment by Yrlish** [comment]
@Paraphraser Seems good to me!
