### ISSUE TITLE
yubikey don't ask for press the button

### ISSUE THREAD

**Issue by critkitten** [drduh/YubiKey-Guide#384]
hello,

first thank you for this nice guide i follow it and it work flawless.
this is obvious as question and no bug i guess.

but i notice when i decrypt with gpg i have to insert my yubikey, then i enter my user pin and i get the decrypted. but shouldn't i have to press the yubikey button after i enter my pin and after first time pin enter everytime?

it can't be safe if i enter the pin once i can decrypt everything without user interaction.

ssh works as it should. generate ed25519-sk and if i connect everytime i have to touch the yubikey.

am im missing something? i set `ykman config usb -a`

**Comment by sza-1** [comment]
Run `gpg --edit-card ...` and execute `uif N on` when B is 1, 2 or 3 (ask touch for sign, decrypt or auth).

**Comment by critkitten** [comment]
okay thank you for support but my gpg(2) on debian and archlinux. both don't know the command uif.
i search more and found a solution.
i'm using 
```
ykman openpgp keys set-touch aut on
ykman openpgp keys set-touch enc on
ykman openpgp keys set-touch sig on
```
