### ISSUE TITLE
Private key backup when renewing sub-keys

### ISSUE THREAD

**Issue by kplattret** [drduh/YubiKey-Guide#385]
I went through the process of renewing my sub-keys and realised that the [renewing section of the guide](https://github.com/drduh/YubiKey-Guide#renewing-sub-keys) doesn't mention anything about taking a new backup of the private keys after extending the sub-keys' expiration date.

It seems to me that it would be important to take a new backup of the temporary folder containing the private keys, so that the offline backups reflect the new expiry date. Or does it not matter? Would importing the new public key at anytime in the future be enough for the private key to be updated properly?

Thank you so much for putting this resource together, it's a true gem. 🙏

**Comment by hvhaugwitz** [comment]
The information about the expiry date of your primary and sub keys is stored in the public key. Basically you create new signatures for your primary or sub-keys when extending the expiry date (see `gpg --list-signatures <pub-key-fingerprint>`) This is why you only need your main private key to extend the expiry dates.

The subtitle `Renewing sub-keys` might be a bit misleading here, as you do not renew the sub keys themselves but only extend the expiry dates.

**Comment by kplattret** [comment]
@hvhaugwitz okay, very neat. Thanks for the explanation, that makes perfect sense.
