### ISSUE TITLE
hopenpgp-tools not available on Debian Bookworm

### ISSUE THREAD

**Issue by Paraphraser** [drduh/YubiKey-Guide#389]
I am doing some testing on a Raspberry Pi, starting with [Raspberry Pi OS Debian Bullseye](https://www.raspberrypi.com/software/operating-systems/) and [upgrading to Bookworm](https://www.linuxcapable.com/how-to-upgrade-from-debian-11-bullseye-to-debian-12-bookworm/).

When my build process attempts to add the prerequisites stipulated in this repo:

```
$ sudo apt install -y hopenpgp-tools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package hopenpgp-tools
```

I think this is the same problem reported by #370 but I have not explored any of the workarounds discussed in that issue to see whether they are suitable for Raspberry Pi OS Debian Bookworm.

According to ["2.4 Removed packages" of Bookworm upgrade](https://anarc.at/services/upgrades/bookworm/#removed-packages), the reason for the omission is "CI regression on armel", with more information available at at [tracker.debian.org](https://tracker.debian.org/pkg/haskell-hopenpgp-tools). I must admit that most of the information at that last link makes my eyes glaze over but the gist seems to be:

> Migration status: Blocked. Can't migrate due to a non-migratable dependency

According to the [hopenpgp-tools](https://hackage.haskell.org/package/hopenpgp-tools) home page, the package provides the executables:

* `hop` - hOpenPGP Validator Tool
* `hkt` - hOpenPGP Keyring Tool
* `hokey` - hOpenPGP Key utility
* `hot` - hOpenPGP OpenPGP-message Tool

As far as I can tell, `hokey` is the only executable used by this repo (at the "tip" under [Verify](https://github.com/drduh/YubiKey-Guide/tree/fec6e92b8f05c899eccc7f2f2b273d609ed6094e#verify)).

As (1) Bookend is quickly becoming all the rage, (2) the future of `hopenpgp-tools` seems uncertain and (3) `hokey` is not critical, it seems to me that we have a several options:

1. Do nothing in the hope that the maintainers of `hopenpgp-tools` will soon be able to resolve whatever is preventing that package from becoming part of Bookworm; or
2. Remove the requirement to install `hopenpgp-tools` from the various prerequisites lists and delete the "tip"; or
3. Add a note at the top of [Required Software](https://github.com/drduh/YubiKey-Guide/tree/fec6e92b8f05c899eccc7f2f2b273d609ed6094e#required-software) to the effect that `hopenpgp-tools` is not currently available for Bookworm, plus a similar note that, until further notice, the tip won't work on Bookworm.

Thoughts?

**Comment by drduh** [comment]
I'm just upgrading to Debian 12 now and also noticed this. Since it's not mission critical, we should 
 remove it from the Required Software section and possibly caveat the Verify section.

**Comment by drduh** [comment]
Thanks to @Xronophobe we now have a workaround available for Debian 12.
