### ISSUE TITLE
Other subkey generation method

### ISSUE THREAD

**Issue by dangoncalves** [drduh/YubiKey-Guide#390]
First, many thanks for this useful guide that helped me a lot in order to configure my yubikeys.

There exist another method to generate subkeys and this is a more secure way: generating subkeys from the yubikey. With this method, the subkeys is every time on the yubikey from generation to storage which is more secure. The drawback comparing to the original method is that there is no way to backup subkey. 

This issue's purpose is to discuss about how to contribute to this guide in order to provide this method. Should we give user the choice between the 2 methods? If not, the guide relies a lot on the subkeys backups so what will be the implications of giving just this new method?

**Comment by drduh** [comment]
This has been discussed in the past and a decision was made for portable keys for reliability/durability reasons. Certainly it's worth mentioning there exists the other method, and what its possible advantages are. Please create a PR for that.
