### ISSUE TITLE
can one use openssl to decrypt files

### ISSUE THREAD

**Issue by Loki-Afro** [drduh/YubiKey-Guide#392]
using yubikey for many years now, having my gpg key on it, doing ssh stuff.

someone encoded a file using openssl with my derived ssh pub key - can i decrypt that?

the script uses the following command:
`openssl pkeyutl -decrypt -inkey $sshkey -in $password_file -out whatever`

where inkey is the ssh rsa private key 

**can one use openssl to decrypt files as well?**

i know, probably the wrong place to ask, but maybe one where i know there is experience :)

**Comment by FundzZaddy** [comment]
Need help it's a new user and I promise to keep tight to rules

**Comment by drduh** [comment]
Closing to inactivity. You may want to check openssl forums about this question.
