### ISSUE TITLE
https://github.com/drduh/YubiKey-Guide#yubikey has predictable components

### ISSUE THREAD

**Issue by MidgetAteMyMom** [drduh/YubiKey-Guide#394]
Maybe I am wrong about this but it seems like 
`$ echo "SCD RANDOM 512" | gpg-connect-agent | sudo tee /dev/random | hexdump -C` will neither produce 512 bytes of output nor make this output completely random. I guess there are additional characters in gpg-connect-agents output.

```
% echo "SCD RANDOM 512" | gpg-connect-agent | hexdump -C
00000000  44 20 f0 c0 b2 e6 15 eb  75 75 bc 21 db 0c 54 75  |D ......uu.!..Tu|
00000010  7f f6 09 13 25 32 35 3c  3c a8 8c 7f b3 15 cf f8  |....%25<<.......|
00000020  cc e6 d8 34 4f 2d 1e 3c  58 3b ee 1b ff 7f 04 94  |...4O-.<X;......|
00000030  78 f9 85 4e d4 93 2f 38  e5 1f d7 51 4d da b7 9f  |x..N../8...QM...|
00000040  9c e6 f9 f9 a5 8a 52 f8  37 63 ed 3f 78 60 14 d2  |......R.7c.?x`..|
00000050  29 6d 4b 80 7c d1 a3 90  c3 0b 78 6e 56 1f fa 26  |)mK.|.....xnV..&|
00000060  d2 6e be cd df 79 a1 1e  63 7e 0b c1 25 30 41 2b  |.n...y..c~..%0A+|
00000070  16 1c 68 8f 46 e8 5d 96  22 14 a9 d1 32 1c 4a 37  |..h.F.]."...2.J7|
00000080  09 90 5d 3c 96 bf 93 fd  35 83 5f 0f 92 0f 8f f2  |..]<....5._.....|
00000090  40 aa b6 08 02 1b e0 4c  2c a5 6f d0 9c 38 63 b2  |@......L,.o..8c.|
000000a0  7f 44 75 f4 3f c0 bc 0c  89 2d 91 d3 4a d7 70 4e  |.Du.?....-..J.pN|
000000b0  40 7a 94 a1 be c4 a3 db  e8 c6 9f e7 41 48 80 0b  |@z..........AH..|
000000c0  58 0f 89 ba 7d ba d4 a7  31 a1 b1 3e dc dc 42 48  |X...}...1..>..BH|
000000d0  32 37 99 0b f1 ce 71 13  b8 3d e3 6d ab f8 78 b2  |27....q..=.m..x.|
000000e0  8c 69 f3 1e d1 de bd 3c  a5 59 25 32 35 c6 43 f4  |.i.....<.Y%25.C.|
000000f0  50 f4 f0 15 e1 9e bd f4  32 e8 9f 2a 30 a1 79 25  |P.......2..*0.y%|
00000100  32 35 f3 e7 e6 9e 7c 1a  66 a8 c9 e5 c9 90 8b 60  |25....|.f......`|
00000110  17 19 ca 03 bb 3e 06 13  d4 79 f1 6e e1 a2 26 a7  |.....>...y.n..&.|
00000120  c3 05 78 5e a3 c9 c5 7b  65 27 47 7c 9a 8f e1 2f  |..x^...{e'G|.../|
00000130  cf 61 b2 4d bb 8f 65 ca  0e 89 e5 16 e0 c9 70 5e  |.a.M..e.......p^|
00000140  61 18 93 c5 55 8d 5f b9  19 cc 88 e2 45 85 bb 51  |a...U._.....E..Q|
00000150  25 30 41 d1 cc c8 29 5f  40 99 f4 02 4e 64 c1 08  |%0A...)_@...Nd..|
00000160  8e b3 47 27 d8 31 5b 54  4a 8f 27 9d 3a 03 d0 d0  |..G'.1[TJ.'.:...|
00000170  33 d0 b7 c5 02 df 82 a8  d8 f1 e2 fb 6c a2 20 99  |3...........l. .|
00000180  5d fc 3d 25 30 44 39 90  fd a3 c7 ee 60 8a 35 d4  |].=%0D9.....`.5.|
00000190  72 de 59 c8 2b d1 a1 b7  ef 38 80 6d 8a 22 2c c7  |r.Y.+....8.m.",.|
000001a0  15 57 64 3d e0 9e 9f 43  43 19 f2 f1 34 2e ee 03  |.Wd=...CC...4...|
000001b0  f2 ff 47 2f 10 3a 8b 93  bb a4 7a c0 d8 ba c0 cf  |..G/.:....z.....|
000001c0  3b 56 b4 fe b3 9f 44 e9  82 42 7a 47 0c 9e 40 d2  |;V....D..BzG..@.|
000001d0  e2 71 ff 78 57 60 6e f1  4f 68 fa 00 f7 62 ba a4  |.q.xW`n.Oh...b..|
000001e0  3a 1b 49 61 3a b8 c5 d0  69 e1 57 00 1b 4a ed c5  |:.Ia:...i.W..J..|
000001f0  16 e8 db a9 40 2a 5e af  39 65 13 5e 9e 30 e8 6b  |....@*^.9e.^.0.k|
00000200  fa f2 c1 89 6c be c4 42  e8 f8 ad 4f b3 bc 0a 4f  |....l..B...O...O|
00000210  4b 0a                                             |K.|
```
There are 18 additional bytes and at least the first two "44 20" and last four "0a 4f 4b 0a" are predictable. The other, additional bytes are most likely also predictable. 

I think this is a bad seed for the kernels prng which is used in other operations requiring randomness, too.

**Comment by Paraphraser** [comment]
I think this is the expected output. Perhaps see [Assuan server responses](https://www.gnupg.org/documentation/manuals/assuan/Server-responses.html#Server-responses) and, in particular, the section on "D &lt;raw data&gt;".

Try running this command several times in succession:

```
$ gpg-connect-agent --hex "SCD RANDOM 32" /bye
```

In the situation where the output contains **no** characters that need to be percent-escaped, you'll get this pattern:

```
D[0000]  B1 F3 5F 14 9D 3E B6 19  EC 4C 80 1F 5C 88 F7 0C   .._..>...L..\...
D[0010]  6C 12 54 10 D1 90 37 8F  B8 6C E7 86 CA E3 BE E3   l.T...7..l......
OK
```

There are four groups of eight bytes yielding the expected 32.

In the situation where the output contains characters that **do** need to be escaped, you'll get this pattern:

```
D[0000]  D1 58 1C 8A D5 5D 27 1C  0F F9 D0 6C 42 DC 1C 9D   .X...]'....lB...
D[0010]  AE 30 B9 12 01 2D 25 32  35 25 30 44 54 EC 28 90   .0...-%25%0DT.(.
D[0020]  2B A9 0C 82                                        +...            
OK
```

You can see the "%25" in there (escaping a "%") plus a "%0D" (escaping a "&#x240D;"). Each character that needs to be escaped turns into three so we wind up with four extra bytes.

Next, set up a TTY variable like this:

```
$ TTY=$(tty)
```

and then run this command repeatedly:

```
$ gpg-connect-agent "SCD RANDOM 32" /bye | tee $TTY | hexdump -C
```

That gets you both the raw and dumped output. The corresponding patterns where there are …

* … no characters being percent-escaped:

	```
	D }JG?????8?
	            ??V?9?
	                  ?'?ñ?7/???
	OK
	00000000  44 20 7d 4a 47 c1 b1 b8  f8 1d 85 38 f2 0c 1b 29  °D ñJG......8...)°
	00000010  5a e1 e5 56 bb 39 aa 0c  fd 27 ce 7d 98 37 2f a2  °Z..V.9...'.ñ.7/.°
	00000020  3f 91 0a 4f 4b 0a                                 °?..OK.°
	00000026
	```
	
	26<sub>16</sub> (the count at the end) is 38<sub>10</sub>. Subtract two characters for the "D&#x2420;" at the start, one for the &#x240A; at the end of the data line, and three characters for the "OK" plus its &#x240A;, and you have 32 bytes of random payload.

	> the line jumps in the raw data are caused by the presence of the 0x0C "&#x240C;" form-feed characters. 

* … characters being percent-escaped:

	```
	D ?u????%0A?f??황5*??
	                     Kod?$??%0D
	OK
	00000000  44 20 02 b7 75 ab 06 c8  19 f0 87 25 30 41 97 66  |D ..u......%0A.f|
	00000010  3f b2 ed 99 a9 35 2a ff  8a 03 0b 4b 15 6f 64 a5  |?....5*....K.od.|
	00000020  24 ce e6 25 30 44 0a 4f  4b 0a                    |$..%0D.OK.|
	0000002a
	```
	
	2a<sub>16</sub> is 42<sub>10</sub>. Subtracting three for the "D&#x2420;" and its &#x240A;, then another three for the "OK" and its &#x240A;, leaves us with 36. There are two percent-escaped characters, each occupying 3 bytes which, when de-escaped, will become one byte each, and we're at 32 bytes of random payload.
	
	> in this case, the line jump is caused by the 0x0B "&#x240C;" vertical tab character.

I'm no guru in any of this stuff so I really don't know whether it would be "better" to post-process the output to remove the leading "D&#x2420;" and trailing "&#x240A;OK&#x240A;", then de-escape any percent sequences before sending this to the RNG. I just sort of take it on faith that, even if some of the bytes are predictable, they don't let you predict anything else about the payload. There are still 512 bytes of random data being generated by the YubiKey which are being used to seed the host system's RNG.

Anyway, that's my 2 cents on the topic. I could easily be wrong.

**Comment by drduh** [comment]
@mirko https://github.com/drduh/YubiKey-Guide/pull/209

**Comment by drduh** [comment]
This comes from Yubico documentation at https://support.yubico.com/hc/en-us/articles/360016649139-YubiKey-5-2-Enhancements-to-OpenPGP-3-4-Support:

> The Get Challenge command generates a random number of a specific byte length. This is useful for using the YubiKey as a hardware based random number generator to create highly sophisticated random numbers. The maximum length of a random number which can be generated is listed in Extended Capabilities. The Get Challenge is listed in section 7.2.15 of the OpenPGP Smart Card 3.4 spec.

However, until it can be demonstrated seeding the rng with this output is beneficial in some way, it should not be in the guide.
