### ISSUE TITLE
keytocard: Key does not match the card's capability.

### ISSUE THREAD

**Issue by Werewolf-Cat** [drduh/YubiKey-Guide#4]
When I try run the command
gpg> keytocard
Signature key ....: [none]
Encryption key....: [none]
Authentication key: [none]

Please select where to store the key:
   (1) Signature key
   (3) Authentication key
Your selection? 1
Key does not match the card's capability.
Your selection?

I get this error.

I did a search on this and according to this article (link below in quotes) the error is a result of keysize apparently. 

"http://forum.yubico.com/viewtopic.php?f=26&t=1832&p=7191&hilit=keytocard#p7191"

The article says that Yubikey only allows 2048 keysize. However it seems 4096 worked for you. 

Please help. Also please know, I am very noobish with gpg and advanced yubikey configuration.

Probably a simple explanations/fix 

Thanks

**Comment by drduh** [comment]
Which hardware are you using? I believe only YubiKey 4 (late 2015) supports RSA keys over 2048 bits.

**Comment by Werewolf-Cat** [comment]
Ok that makes sense. I am using the Yubikey Neo. On the product page it states "the YubiKey 4 or YubiKey 4 Nano, our latest generation YubiKey, [includes] faster and strong crypto compared to the YubiKey NEO."

"https://www.yubico.com/products/yubikey-hardware/yubikey-neo/"

I guess I'm stuck with 2048.

**Comment by JackHowa** [comment]
I'm confused because the recent YubiKey 4 I bought only seems to support 2048 bits? 

Key attributes ...: 2048R 2048R 2048R
