### ISSUE TITLE
Unable to get keytocard subcerts to yubikey 5 NFC (piv) :-/

### ISSUE THREAD

**Issue by mannp** [drduh/YubiKey-Guide#402]
Hi there

Struggling to get anything to work with gpg, but trying to get my PIV sub certs onto the Yubikey for use with NixOS.

I have changed my 3 passwords for PIV in the yubikey manager  gui (cli's just crashed for me) and protected the management password with the admin pin.

Anyway, when doing a keytocard export I am entering my Yubikey management key and admin code (PUK) as specified, and it rejects the passwords and codes each time.

Driving me nuts, as not sure what I am doing wrong.

Also tried with the admin pin and then user pin, but that also failed, as well as the key password itself, all failed.

I've reset PIV a good few times due to password issues.

Any help or direction would be much appreciated :)

**Comment by drduh** [comment]
Try Resetting the card and provisioning it with default PIN values and using a simple password for GnuPG. Also try provisioning it on a different system.

**Comment by gagandeepb** [comment]
Hi there

@drduh Thanks for this nice guide. 

However, I also struggled with this problem for a while. (Incidentally, also on NixOS.)
My understanding after [reading this issue](https://github.com/Yubico/yubico-piv-tool/issues/58) is that RSA4096 keys are not supported by Yubikey 5 NFC's PIV. 

I wonder if this limitation of the Yubikey should be dealt with in this guide?
