### ISSUE TITLE
Request: upload protonmail private key to yubikey

### ISSUE THREAD

**Issue by DrCapricorn** [drduh/YubiKey-Guide#422]
Hello,

Thank you for this work. I would like to use the protonca to verify my identity and safe the extracted proton private key to a yubikey. I have tried several hours  to achieve this but I didn't get it to work.
https://proton.me/support/download-public-private-key

If you could find the time to add this to your manual, I think it would be helpfull to some people.

Thanks.

**Comment by leohidalgo** [comment]
Could you specify that it does not work, does it give you any error?

**Comment by leohidalgo** [comment]
As a tip, I would manage the protonmail KEY in protonmail and the yubikey from an offline KEY created as recommended in the guide.

**Comment by drduh** [comment]
As @leohidalgo said, please specify the issue so we can help get it working for you.
