### ISSUE TITLE
gpg-agent with OpenSSH_7.6p1

### ISSUE THREAD

**Issue by hoegertn** [drduh/YubiKey-Guide#43]
When using the gpg-agent as describen on macOS High Sierra with OpenSSH_7.6p1 it fails with 

`error fetching identities: Invalid key length`

Any idea how to fix this?

**Comment by hoegertn** [comment]
I am using a YubiKey 4c with a 4096bit key. When I start the gpg-agent as described I get the following error when calling `ssh-add -L` or when trying to connect to any server.

**Comment by the-pete** [comment]
What is the length of the server key?  I've seen this before on older boxes where the key was generated a while ago.  May need to regenerate that key.

**Comment by hoegertn** [comment]
I fixed it by cleaning my `.gnupg` folder. Maybe something old was there preventing the agent from working correctly.
--> Close

**Comment by thardie** [comment]
This case can also be produced by adding a SSH Certificate to your agent. gpg-agent will accept it, but doesn't know how to read it back.

**Comment by reelsense** [comment]
I use SSH certs all the time with my Yubikey without issue.

**Comment by thardie** [comment]
> I use SSH certs all the time with my Yubikey without issue.

Do you do this with gpg-agent? When I add an ssh cert to my gpg-agent, I run into this bug: https://dev.gnupg.org/T1756

**Comment by reelsense** [comment]
@thardie I'm following the [drduh Yubikey-Guide](https://github.com/drduh/YubiKey-Guide) so I must be using the gpg-agent. I'm using ssh certs for the client, not the server. I need to confirm I haven't added my public key to the servers authorized keys file. I've been using a SSH CA reliably for years, even with my yubikeys.

**Comment by thardie** [comment]
@reelsense Do you mind running an "ssh-add -l" and seeing if you have any (RSA-CERT) entries listed with the gpg-agent? I can add the cert to the GPG agent, but thereafter, "ssh-add -l" reports the error @hoegertn mentioned.

**Comment by claviola** [comment]
I have the same issue, by the way. Everything seems to work, but `ssh-add -l` will report `error fetching identities: Invalid key length` and I am unable to actually use the identities.

**Comment by reelsense** [comment]
>_"@reelsense Do you mind running an "`ssh-add -l`" and seeing if you have any (RSA-CERT) entries listed with the gpg-agent?"_

When I run `ssh-add -l` I only see my Yubikey. I'm only allowed into my servers because my Yubikey's public key is signed. 

>_"I can add the cert to the GPG agent, but thereafter, "`ssh-add -l`" reports the error @hoegertn mentioned."_

I've never adde my cert file to gpg-agent. I just put the cert file in `~/.ssh/` and give it a name that looks like a cert vs a pub key: `~/.ssh/id_rsa-cert.pub`. ssh sends _any and all_ of your keys/certs to every server you attempt a connection to.

When I ssh to my server; `ssh examplehost -v`, I can see: 

```
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: cardno:0123456789 RSA SHA256:YTRmMTAwNDU2YzhlMGU5YjUwMjg3ZDdjMThkNGJlMjY1Y2JiYzViZTMwMGNkYWQyYzhhYjQzOWFiODMzOTE3Nw== agent
debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/exampleuser/.ssh/id_rsa
debug1: Offering public key: /Users/exampleuser/.ssh/id_rsa RSA-CERT SHA256:YTRmMTAwNDU2YzhlMGU5YjUwMjg3ZDdjMThkNGJlMjY1Y2JiYzViZTMwMGNkYWQyYzhhYjQzOWFiODMzOTE3Nw==
debug1: Server accepts key: /Users/exampleuser/.ssh/id_rsa RSA-CERT SHA256:YTRmMTAwNDU2YzhlMGU5YjUwMjg3ZDdjMThkNGJlMjY1Y2JiYzViZTMwMGNkYWQyYzhhYjQzOWFiODMzOTE3Nw==
```

And on the server side I see:

`/var/log/auth.log`

```
Mar 10 00:10:23 examplehost sshd[4400]: Accepted publickey for exampleuser from 169.169.169.256 port 53040 ssh2: RSA-CERT ID exampleuser (serial 0123456789) CA RSA SHA256:YTRmMTAwNDU2YzhlMGU5YjUwMjg3ZDdjMThkNGJlMjY1Y2JiYzViZTMwMGNkYWQyYzhhYjQzOWFiODMzOTE3Nw==
Mar 10 00:10:23 examplehost sshd[4400]: pam_unix(sshd:session): session opened for user exampleuser by (uid=0)
Mar 10 00:10:23 examplehost systemd-logind[781]: New session 3800 of user exampleuser.
Mar 10 00:10:28 examplehost sshd[4513]: Received disconnect from 169.169.169.256 port 53040:11: disconnected by user
Mar 10 00:10:28 examplehost sshd[4513]: Disconnected from user exampleuser 169.169.169.256 port 53040
Mar 10 00:10:28 examplehost systemd-logind[781]: Removed session 3800.
Mar 10 00:10:28 examplehost sshd[4400]: pam_unix(sshd:session): session closed for user exampleuser
Mar 10 00:10:37 examplehost sshd[4540]: Accepted publickey for exampleuser from 169.169.169.256 port 53050 ssh2: RSA-CERT ID exampleuser (serial 0123456789) CA RSA SHA256:YTRmMTAwNDU2YzhlMGU5YjUwMjg3ZDdjMThkNGJlMjY1Y2JiYzViZTMwMGNkYWQyYzhhYjQzOWFiODMzOTE3Nw==
Mar 10 00:10:37 examplehost sshd[4540]: pam_unix(sshd:session): session opened for user exampleuser by (uid=0)
Mar 10 00:10:37 examplehost systemd-logind[781]: New session 3801 of user exampleuser.
```

---

>_"Also, what version of gpg-agent are you using?"_

`gpg-agent 2.2.17`

**Comment by thardie** [comment]
Thanks for the answer. In my case, I cannot put the certs in my .ssh directory, as they are short lived and issued by Gravitational Teleport, which adds them to the local ssh-agent (or in this case, gpg-agent)

**Comment by mike2194** [comment]
just to add to this:
i was able to resolve this issue by modifying file ~/.gnupg/sshcontrol  and removing the offending key.
