### ISSUE TITLE
`GNUPGHOME` should be exported

### ISSUE THREAD

**Issue by aleprovencio** [drduh/YubiKey-Guide#434]
Since [this commit](https://github.com/drduh/YubiKey-Guide/commit/b2959d075b8a89e3b5f36cea224347654871258e) the `export` instructions have been removed from the `GNUPGHOME` definitions. I guess this is wrong because `gnupg` won't recognize this new configuration path and will use its default `~/.gnupg` instead.

**Comment by drduh** [comment]
Which system are you on? It did not appear necessary when I tested the instructions on the latest Debian.
