### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by markfaine** [drduh/YubiKey-Guide#44]
Two suggestions:

1.  If you want to add your keys to multiple yubikeys you will need to restore a copy of your backup and repeat the process.  This would have been nice if it was mentioned in the guide.
1. The guide should also show how to add multiple identities.  Often times with version control systems your primary email for the version control system must be in the key or you will get an "Unverified " badge on commit signing.  This should be addressed in the guide.

**Comment by drduh** [comment]
See #21 for the second point.
