### ISSUE TITLE
Issue with fdisk 

### ISSUE THREAD

**Issue by DrCapricorn** [drduh/YubiKey-Guide#441]
```
`Create a small (at least 20 Mb is recommended to account for the LUKS header size) partition for storing secret materials:

sudo fdisk /dev/sdc <<EOF
n


+20M
w
`EOF``
```
doesn't work anymore. Fdisk asks for a partition number in Debian and Fedora 40. 

(Thank you for your guide.)

**Comment by drduh** [comment]
Can you share the OS and fdisk versions? The newlines are supposed to be for accepting default options and were tested on Debian 12.

**Comment by drduh** [comment]
Please reopen with steps to reproduce this issue. Thanks!
