### ISSUE TITLE
Problem with renewing expired subkeys

### ISSUE THREAD

**Issue by knazarov** [drduh/YubiKey-Guide#442]
I've followed the guide for renewing the subkeys that I've generated a year ago, and which have expired.
It seems like this command that is mentioned in the guide only works for the subkeys that haven't already expired:

```
gpg --batch --pinentry-mode=loopback \
  --passphrase "$CERTIFY_PASS" --quick-set-expire "$KEYFP" "$EXPIRATION" "*"
```

This is because the `*` in this expression only matches active subkeys.

In order to make things work, I had to manually list the fingerprints by doing the following:

```
gpg -Kv --with-subkey-fingerprints
```

And then putting the fingerprints separated by spaces instead of the `*`. I probably would've contributed a pull request to the README, but it's not clear yet to me how to make this "pretty".

**Comment by drduh** [comment]
@knazarov thank you for catching that, it is my mistake for trying to simplify commands without testing that particular condition. Please feel free to correct my mistake in a PR as you describe, even if breaks any idiomatic conventions.

**Comment by drduh** [comment]
@knazarov I tested this condition and the following command appears to work for modifying subkey expirations:

https://github.com/drduh/YubiKey-Guide/tree/wip-30jun24?tab=readme-ov-file#renew-subkeys
