### ISSUE TITLE
thunderbird integration incompatible with armor keyword in gpg.conf

### ISSUE THREAD

**Issue by snqk** [drduh/YubiKey-Guide#448]
See context here: https://thunderbird.topicbox.com/groups/e2ee/T98c38d698d7fc1aa

TL;DR: when setting up decryption for emails in the thunderbird client, the armor keyword caused decryption attempts to fail as TB expects a dearmored output.

I'd propose adding a warning for anyone who stumbles onto this issue.

**Comment by drduh** [comment]
That would be good information to include in the Email section, along with the `throw-keyids` option notice for Mailvelope.

Can you send a PR?

**Comment by snqk** [comment]
@drduh thanks, this is ready for a review
