### ISSUE TITLE
Use secure location for GNUPGHOME

### ISSUE THREAD

**Issue by brempusz** [drduh/YubiKey-Guide#45]
Maybe instead of local temp directory (and later backup/secure delete) use safe storage from the start? "Safe storage" can be encrypted USB (prepared according to the guide) or hardware-encrypted external drive.

Just start the guide with **Prepare safe storage location** (now named **Backup everything**) and then use it:
```
$ export GNUPGHOME=$(mktemp -d -p /path/to/safe/storage); echo $GNUPGHOME
```
You will still need to create backup copy before moving keys to card but it will be as simple as using `tar` in place. But "secure delete" will not be required anymore.

**Comment by peckeltw** [comment]
For security reasons I'd recommend you to use a live Linux distribution with NO connection to the public internet to setup the YubiKey as described. I always use [Tails](https://tails.boum.org/index.en.html) which out of the box has all the packages one usually needs to install:

`$ sudo apt-get install -y gnupg2 gnupg-agent pinentry-curses scdaemon pcscd yubikey-personalization libusb-1.0-0-dev`

As far as I remember, only yubikey-personalization is missing in Tails, but this is only required for older YubiKeys and can easily be used on a different machine.

As the live Linux distribution runs from RAM, everything is cleaned anyways after a reboot. I don't see why temp files should be stored at all. The guide is really good; just backup externally what you really need.

**Comment by peckeltw** [comment]
@drduh can you close that one?
