### ISSUE TITLE
sed Error for CERTIFY_PASS command?

### ISSUE THREAD

**Issue by bsodmike** [drduh/YubiKey-Guide#454]
This is in the docs but I'm getting a `sed` error?

```bash
CERTIFY_PASS=$(LC_ALL=C tr -dc 'A-Z1-9' < /dev/urandom | \
  tr -d "1IOS5U" | fold -w 30 | sed "-es/./ /"{1..26..5} | \
  cut -c2- | tr " " "-" | head -1) ; echo "\n$CERTIFY_PASS\n"
```

```
sed: 1: "s/./ /{1..26..5}
": bad flag in substitute command: '{'
```

**Comment by Paraphraser** [comment]
You didn't say what platform you are running on but, at a guess, I'd say it's a Mac. Am I right? If yes then please study the screenshot:

<img width="1253" alt="Screenshot 2024-08-04 at 23 47 11" src="https://github.com/user-attachments/assets/063af7e4-2bf0-41e2-8d70-74dc7952348f">

What it shows is:

1. The command running **successfully** on macOS (in this case an Intel iMac running Ventura).
2. The version of the `bash` shell interpreter that has just run the command successfully (5.2.26).
3. The output from `which -a bash` showing that two instances of `bash` are in my search path (the first path is the one that launches when I launch Terminal).
4. Explicitly launching the second version at `/bin/bash`. Even though there is no obvious change, that second version takes control at that point.
5. The version that is running now is 3.2.57.
6. The result of running the command using version 3.2.57 of `bash` - the same error as you are getting.

Why is this so? Well, I don't claim to know all the ins and outs of this and I certainly can't speak from certain knowledge so please take this with several grains of salt. What I have read in a few places on the web ([example](https://news.ycombinator.com/item?id=27543407)) is that the licence conditions for `bash` changed in a way that troubled Apple. The upshot is that macOS ships with an obsolete version of `bash` (3.2.57), and I understand that's also the reason why macOS now defaults to `zsh`.

I am not a fan of `zsh` so I used HomeBrew to install an up-to-date version of `bash`. You could do the same.

That said, `zsh` will execute the command without error so if that's all you want to do:

```
$ /bin/zsh
$ CERTIFY_PASS= ...
```

<hr>

If my original guess was incorrect (you aren't using a Mac) then "obsolete version of `bash`" is still the most-likely answer. You'll just have to figure out how to upgrade.

**Comment by bsodmike** [comment]
Thanks so much, I installed an upgraded version of bash although I mainly use fish shell now, having moved on from zsh.

Added one small tweak though see the `-e` at the bottom

```bash
CERTIFY_PASS=$(LC_ALL=C tr -dc 'A-Z1-9' < /dev/urandom | \
  tr -d "1IOS5U" | fold -w 30 | sed "-es/./ /"{1..26..5} | \
  cut -c2- | tr " " "-" | head -1) ; echo -e "\n$CERTIFY_PASS\n"
```

**Comment by drduh** [comment]
Please reopen if this is still an issue with the more portable printf change.
