### ISSUE TITLE
ubuntu 24,  gpg: KEYTOCARD failed: Invalid time

### ISSUE THREAD

**Issue by g2f4u** [drduh/YubiKey-Guide#459]
I'm having trouble transferring the key to the device on ubuntu 24, following this guide.

It fails with 
`gpg: KEYTOCARD failed: Invalid time`

Is this happening for others?

**Comment by jishnunb0** [comment]
I followed the interactive way, using 
```
gpg --edit-key $KEYID
```
then selected each key and executed keytocard. 
It worked for me. I looked up an old  version of the readme and followed it, pleae find it [here](https://github.com/drduh/YubiKey-Guide/tree/1ad37577db92726eadde4dc302a6f982ba7e82dc?tab=readme-ov-file)

**Comment by drduh** [comment]
Please use Debian Live and reopen the issue if the problem occurs there.
