### ISSUE TITLE
ECC partly for key creation instead of RSA.

### ISSUE THREAD

**Issue by knaggit** [drduh/YubiKey-Guide#52]
I was wondering about the selection for encryption keys on the creation part of the tutorial. Isn't it a better idea to recommend here ECC keys instead of RSA? There is a lot of discussion I remember about RSA which is going to be kind of deprecated. Honestly, I have to research it again, but my gut tells me it makes more sense. Is there a good reason, not to do it?

**Comment by drduh** [comment]
I selected RSA for compatibility, as GnuPG 2.1 (which added ECC supported) had not been the default installation at the original time of writing the guide. The 2015 paper [A Riddle Wrapped in an Enigma](https://eprint.iacr.org/2015/1018.pdf) is a good additional reading on the subject. This [analysis](https://safecurves.cr.yp.to/) by DJB is another to consider and personally gives me pause about using Yubikey's supported ECC algorithms (p256, p384). There is nothing I'm aware of that would characterize RSA with sufficient key length as being or soon to be deprecated, however.

**Comment by knaggit** [comment]
I found a talk from "[Rüdiger Weiß](http://public.beuth-hochschule.de/~rweis/)" who is professor researching in cryptology from Germany. His talk from a slightly older c3 gave me the hint, that using RSA is still a good idea and ECC has a lot of flaws actually.

**Comment by basbebe** [comment]
ECC has beenout there for a while and Curve25519 is being used by Signal Messenger and many others.
I think it would be fair to reconsider.

see:
- https://en.wikipedia.org/wiki/Curve25519
- https://ianix.com/pub/curve25519-deployment.html
- https://zach.codes/ultimate-yubikey-setup-guide/
