### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by markfaine** [drduh/YubiKey-Guide#58]
Is this information still accurate after two years?  

Also, could there be a section on getting SSH authentication to work with Putty and Git Bash.  I've been fighting that for nearly two weeks now with no luck.

Thanks for putting this together.  I originally used Simon Josefsson's blog post that you referenced but your information seemed more up-to-date the last time I needed to do it.  I know this is a moving target and I'd be willing to help test any of the steps.  I'd also be willing to help script some of it if you think we could automate the process.

**Comment by drduh** [comment]
I haven't used the instructions in a while to create new keys, but they definitely work for using existing keys. Sorry, I can't help with Putty since I don't use my keys on Windows. What errors are you seeing?

**Comment by markfaine** [comment]
I've been trying to use my gpg keys for ssh authentication everywhere, so I don't have ssh keys here and gpg keys there and just to generally consolidate my access requirements to just needing my yubikey with me.   I've since determined the cuase of the issue but I doubt there is anything that can be done about it.  It seems that Git4Windows uses a different mechanism for sockets than is used by git on Linux.  Apparently, it's not compatible.  I asked a git4windows dev about it but he could not be bothered, to say the least.  Thanks for your info.

**Comment by drduh** [comment]
If you do get it working with Windows and can add the needful to this guide, I would appreciate it.

**Comment by markfaine** [comment]
Thanks, I agree. I have no idea why almost every open source dev has to be such a jerk.  You'd think it must be a requirement of the GPL at this point.

I was never able to get it to work the way I wanted, or really at all.  I've seen that error before, I'm not sure and can't really remember if I fixed it.  My guess would be maybe a missing SSH_AUTH_SOCK socket, it would be nice if it would give you a little more information.

Sorry, I couldn't be of more help, though if you do figure it out, I'd love to know how you managed to do it.

-Mark

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rcdailey** [comment]
I did find a satisfactory solution to this. I'll explain:

1. Per the guide, make sure `enable-putty-support` is set up in your `gpg-agent.conf`
1. Do *not* use mingw's built-in `gpg` or `gpg-agent` executable. You *must* stick to the Gpg4Win executables.
1. Use `gpg --export-ssh-key` to get a public SSH key
1. Add the public SSH key to your server's `~/.ssh/authorized_keys` file
1. Make sure `gpg-agent` (from Gpg4Win!) is started by doing `gpg-connect-agent /bye`. I also added this to my Startup folder on Windows, per the guide.
1. Use Putty to log into your SSH server with your Yubikey plugged in. You will be prompted to enter a PIN.

**Comment by markfaine** [comment]
Thanks!  I will definitely give this a try.  One problem I have is that I also use a smartcard at work to login to my workstation.  In the past, I've always had issues with it conflicting with the smartcard on my yubikey.  Apparently, Windows has trouble with more than one smartcard.  It's been a while though since I gave it a try so maybe this time it will work.

Thanks again,
-Mark

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BriceGagnageRenault** [comment]
Hi, if you have troube with multiple smartcard, this might be the same issue as the one mentionned [here](https://github.com/drduh/YubiKey-Guide#windows). The Windows and WSL section of this guide have been updated very recently, perhaps you'll find additional information.

**Comment by markfaine** [comment]
Thanks, at first glance it looks like I'm already doing that but I'll take a closer look and see if I'm missing anything.  Unfortunately, I don't think gpg-agent supports CAPI certificates so now I'm use a custom version of pageant because we use PIV-SSH for access to our servers.  Which wouldn't be a problem except that you can't have both pageant and gpg-agent running simultaneously.  That's the last issue I'll have to resolve, at least that I'm aware of.

-Mark

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
