### ISSUE TITLE
Windows key export command

### ISSUE THREAD

**Issue by joko11** [drduh/YubiKey-Guide#67]
The mention windows command for exporting the keys didn't work for me using powershell or cmd.
The command should be the same as the Linux command using a ">" instead of "-o".

Just for your information.

Regards,
joko

**Comment by drduh** [comment]
paging @jholtmann

**Comment by jholtmann** [comment]
@joko11 What about the command did not work?

**Comment by joko11** [comment]
Well, I am unable to reproduce the problem now. Executing the command "gpg --armor --export-secret-keys $KEYID -o C:\temp\mastersub.gpg" yesterday just printed the key to the console instead like intended to the specified file. Now it works just fine.

I think I messed something up yesterday, sorry for wasting your time with my incompetence. 0.o
