### ISSUE TITLE
Difficulty with Windows integration

### ISSUE THREAD

**Issue by rat** [drduh/YubiKey-Guide#75]
I followed the tutorial carefully and even then when I try to use SSH with a program other than PuTTY nothing works.

The image below shows me using SSH in 3 programs. Has anyone ever experienced this? Do you know how to solve it?

!["img"](https://i.imgur.com/dAhTOQ4.png)

**Comment by drduh** [comment]
Hi @rat 

The middle screen appears to show a successful ssh connection using ssh-agent, no? On the right screen, you're using the username `roo` - not `root`, maybe that's a problem?

**Comment by BriceGagnageRenault** [comment]
Hi @drduh, I just managed to make ssh forwarding work with yubikey + gpg4win + weasel-agent => linux machines under WSL, would you be interested by a contribution on this topic ?

**Comment by drduh** [comment]
@BriceGagnageRenault Absolutely! Please send a PR.
