### ISSUE TITLE
Specify "default-key" in gpg.conf

### ISSUE THREAD

**Issue by wsargent** [drduh/YubiKey-Guide#8]
Examples should specify default key in gpg.conf, in full fingerprint mode rather than specifying it on the command line.  Specifying it on the command line means people without coffee will (incorrectly) copy and paste without checking the key id is correct.

```
echo "default-key <myfingerprint>" >> ~/.gnupg/gpg.conf
```

**Comment by drduh** [comment]
It has worked well for me without this option.

**Comment by ljodea** [comment]
Why is there a `default-key 0xFF3E7D88647EBCDB` and a `trusted-key 0xFF3E7D88647EBCDB` hardcoded at the end of http://raw.githubusercontent.com/drduh/config/master/gpg.conf ?

They're not in the text of README.md, but they're in the config file that you recommend using.

**Comment by Paraphraser** [comment]
Good question. It isn't in my copy but I downloaded that a fair while ago.

Nosing through the repository suggests it was added 15 days ago:

> [https://github.com/drduh/config/blame/master/gpg.conf](https://github.com/drduh/config/blame/master/gpg.conf)

Probably a mistake. If it were me, I'd either delete the line or replace it with my own fingerprint.
