### ISSUE TITLE
Error when attempting to disable OTP via USB

### ISSUE THREAD

**Issue by jsatk** [drduh/YubiKey-Guide#81]
I only use YubiKeys for GPG. Since OTP via YubiKey isn't supported in Firefox or Safari as of this writing I don't use it. Unfortunately when I attempt to disable OTP via USB it throws this error.

```
$ ykman config usb --disable OTC
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: No PyUSB backend detected!
```

I tried to follow the instructions at the bottom of the README to disable it but failed. After much internet searching I'm still at a loss on how to disable OTC via USB (I keep accidentally touching the YubiKey and it prints all those characters and it's driving me mad!)

I was hoping you could update the README with instructions on how to turn this off that won't cause this error.

**Comment by epje** [comment]
Have you got the latest version of YubiKey manager?
I can't speak for any other OS but I'm running version 1.0.1 on Windows and it works fine, both by command line and GUI.

You can check your ykman version with either of the following:
`ykman -v` or `ykman --version`

> [https://www.yubico.com/products/services-software/download/yubikey-manager/](url)

**Comment by jsatk** [comment]
https://github.com/Yubico/yubikey-manager/issues/185#issuecomment-446379356
