### ISSUE TITLE
Broken command for sending key to specific public key server

### ISSUE THREAD

**Issue by pmotch** [drduh/YubiKey-Guide#86]
In the section https://github.com/drduh/YubiKey-Guide#export-public-key I ran into an issue when using the example command for sending the public key to a specific public key server host:

```
gpg --send-key $KEYID --keyserver pgp.mit.edu
gpg: Note: '--keyserver' is not considered an option
gpg: "--keyserver" not a key ID: skipping
gpg: "pgp.mit.edu" not a key ID: skipping
gpg: sending key 0x90F75EF0DED58298 to hkps://hkps.pool.sks-keyservers.net
```

I wonder if this is an issue with newer version of GPG perhaps. This may not be an issue for others. It did work when I ran this instead: `gpg --send-key --keyserver pgp.mit.edu $KEYID`.

**Comment by drduh** [comment]
Thanks @netflash
