### ISSUE TITLE
Generate Keys on Yubikey

### ISSUE THREAD

**Issue by danieldjewell** [drduh/YubiKey-Guide#97]
Hi! 

Just a suggestion -- maybe mention the possibility of generating keys directly on the Yubikey?

As noted in the support article, this *does* come with limitations -- e.g. you can never backup the keys. But this is also part of the point of generating keys on the YubiKey: you can never backup the keys... meaning they never exist anywhere else at any time (e.g. even in memory while you're generating the keys and before you transfer them to the Yubikey). 

Part of the beauty of hardware cryptography (whether a smart card or a Yubikey) is the very ability to have keys that *only exist on that device* and cannot be retrieved. (And further, having strong locking policies that cause the device to erase or destroy itself if a PIN/PUK is entered too many times incorrectly.) 

Just a thought :)  

https://support.yubico.com/support/solutions/articles/15000006420-using-your-yubikey-with-openpgp#Generating_Your_PGP_Key_Directly_on_Your_YubiKey8gpnr

**Comment by drduh** [comment]
I mentioned this possibility in the key generation section with a recent commit, but personally would not recommend doing it.

**Comment by danieldjewell** [comment]
> but personally would not recommend doing it.

@drduh Any particular reason you wouldn't recommend it? I mean, I fully understand the argument that if the key is generated on the YubiKey - or any other PIV/Smartcard - you can't ever back it up or access it ... but that's also kinda the point: that (a) the device will protect the private key, preferentially destroying itself (and the key) if you tamper with it and (b) performing signing/encryption operations on-device [e.g. data-to-be-encrypted goes in, ciphertext comes out] , such that the private key is never ever transferred. Granted, the "price" for this is the loss in flexibility/backup if the  YubiKey (or other PIV/Smartcard) is lost/stolen/damaged... 

Perhaps I'm mistaken or am missing something here about how the YubiKey is designed or functions -- is it possible that the on-device key generation doesn't have sufficient entropy for randomness? (From a cryptographic perspective, I'm unsure how the YubiKey's hardware stacks up against others in terms of secure key generation and storage...)

**Comment by drduh** [comment]
Agree there is a valuable use case in creating keys such that no copies exist. This is already feasible by using a secure environment and discarding backups though. I'm against generating keys on the device exactly for the same reasons you give: I don't know how well vetted and trustworthy that process is. https://www.yubico.com/support/security-advisories/ysa-2017-01/ is a recent vulnerability that comes to mind. Overall, there seems to be little benefit to using on-key generation. If anyone is more informed about the process, please let us know, of course.
